/* RC39 machine-credential revocation regressions. Synthetic data only.
 * JSON uses the existing one-service-writer contract; fresh processes test
 * restart reads, not unsupported simultaneous JSON service writers.
 * PostgreSQL uses fresh local databases and two actual row-lock orderings.
 * No HTTP, signing, broadcast, production credentials or owner data.
 */
'use strict';
const {test,before,after}=require('node:test');
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..');
const platform=require('../../server/src/platform-store');
const mi=require('../../server/src/machine-identity');
const {Categories:C,getPlatformStore}=platform;const clone=x=>JSON.parse(JSON.stringify(x));
const barrier=()=>{let resolve;return{promise:new Promise(r=>resolve=r),resolve:(...a)=>resolve(...a)};};
const next=()=>new Promise(r=>setImmediate(r));
const PG={host:process.env.POLICYVAULT_TEST_PG_HOST||'127.0.0.1',port:Number(process.env.POLICYVAULT_TEST_PG_PORT||0),user:process.env.POLICYVAULT_TEST_PG_USER,database:process.env.POLICYVAULT_TEST_PG_DATABASE};
const usePg=Boolean(PG.port&&PG.user&&PG.database);let admin;const stores=[],dirs=[],dbs=[];
before(async()=>{if(usePg){assert.ok(['127.0.0.1','localhost','::1'].includes(PG.host),'isolated loopback test PostgreSQL only');const {Pool}=require(root+'/sdk/node_modules/pg');admin=new Pool({host:PG.host,port:PG.port,user:PG.user,database:PG.database});}});
after(async()=>{for(const store of stores)await store.close();if(admin){for(const db of dbs)await admin.query(`DROP DATABASE ${db} WITH (FORCE)`);await admin.end();}for(const dir of dirs)fs.rmSync(dir,{recursive:true,force:true});});
async function fixture(backend){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rc39-revocation-'));fs.chmodSync(dir,0o700);dirs.push(dir);let config={persistenceBackend:'json',networkId:'mainnet',dataRoot:dir};let sdkStore=null;if(backend==='postgres'){const db='pv_rc39_revoke_'+process.pid+'_'+dbs.length;await admin.query(`CREATE DATABASE ${db}`);dbs.push(db);config=require(root+'/sdk/src/config').loadConfig({persistenceBackend:'postgres',networkId:'testnet-10',pgHost:PG.host,pgPort:PG.port,pgUser:PG.user,pgDatabase:db,pgNoTls:true,authMode:'enabled',authCookieInsecure:true,dataRoot:dir});sdkStore=await require(root+'/sdk/src/store').openPgStore(config,{migrate:true});stores.push(sdkStore);}const creatorXOnly=crypto.randomBytes(32).toString('hex'),store=getPlatformStore(config);const created=await mi.createIdentity(config,{creatorXOnly,label:'synthetic RC39 credential',scopes:['read:network']});return{config,store,sdkStore,creatorXOnly,created,identityId:created.identity.identityId,credentialId:created.credential.record.credentialId,key:created.credential.record.tokenHashKey,token:created.credential.token};}
async function accepted(f){try{const result=await mi.resolveBearerToken(f.config,'Bearer '+f.token);assert.deepEqual(result.identity.scopes,['read:network']);return true;}catch(e){assert.equal(e.status,401);assert.equal(e.code,'MACHINE_TOKEN_INVALID');return false;}}
const FRESH_RESOLVE="'use strict';\n// Synthetic token is delivered in memory on stdin, never process arguments/output.\nconst root=process.argv[1],machine=require(root+'/server/src/machine-identity');\nlet raw='';process.stdin.setEncoding('utf8');process.stdin.on('data',x=>raw+=x);process.stdin.on('end',async()=>{let store;try{const x=JSON.parse(raw);raw='';if(x.config.persistenceBackend==='postgres')store=await require(root+'/sdk/src/store').openPgStore(x.config,{migrate:false});try{const result=await machine.resolveBearerToken(x.config,'Bearer '+x.token);process.stdout.write(JSON.stringify({accepted:true,scope:result.identity.scopes}));}catch(e){if(e.status!==401||e.code!=='MACHINE_TOKEN_INVALID')throw e;process.stdout.write(JSON.stringify({accepted:false,status:401}));}await new Promise(r=>setImmediate(r));if(store)await store.close();}catch{process.stderr.write('SYNTHETIC_FRESH_RESOLVE_FAILED\\n');process.exitCode=1;}});\n";
async function fresh(f){return new Promise((resolve,reject)=>{const child=cp.spawn(process.execPath,['-e',FRESH_RESOLVE,root],{env:{PATH:process.env.PATH},stdio:['pipe','pipe','pipe']});let out='',err='';child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);child.on('error',reject);child.on('close',code=>{try{assert.equal(code,0,'fresh process must complete without errors');assert.equal(err,'');resolve(JSON.parse(out));}catch(e){reject(e);}});const config={persistenceBackend:f.config.persistenceBackend,networkId:f.config.networkId,dataRoot:f.config.dataRoot,...(f.config.pg?{pg:{host:f.config.pg.host,port:f.config.pg.port,user:f.config.pg.user,database:f.config.pg.database,ssl:false,poolMax:4,connectTimeoutMs:5000}}:{})};child.stdin.end(JSON.stringify({config,token:f.token}));});}
const revoke=f=>mi.revokeCredential(f.config,{identityId:f.identityId,credentialId:f.credentialId,creatorXOnly:f.creatorXOnly});
function holdTouch(f){const entered=barrier(),resume=barrier();let pending,held=false;const method=typeof f.store.touchMachineCredential==='function'?'touchMachineCredential':'write';const original=f.store[method].bind(f.store);f.store[method]=(...args)=>{const usage=method==='touchMachineCredential'||args[0]===C.MACHINE_CREDENTIAL&&args[2]?.status==='ACTIVE'&&args[2]?.lastUsedAt;if(usage&&!held){held=true;const captured=clone(args);pending=(async()=>{entered.resolve();await resume.promise;return original(...captured);})();return pending;}return original(...args);};return{entered:entered.promise,release:async()=>{resume.resolve();return pending;},restore:()=>{f.store[method]=original;}};}
for(const backend of usePg?['json','postgres']:['json']){
 test(`${backend}: delayed usage cannot resurrect a revoked credential, including fresh processes`,async(t)=>{const f=await fixture(backend);const hold=holdTouch(f);assert.equal(await accepted(f),true);await hold.entered;const revoked=await revoke(f);assert.equal(revoked.status,'REVOKED');assert.equal((await fresh(f)).accepted,false);const before=await f.store.read(C.MACHINE_CREDENTIAL,f.key);await hold.release();hold.restore();const after=await f.store.read(C.MACHINE_CREDENTIAL,f.key);const freshAfter=await fresh(f);t.diagnostic(JSON.stringify({persistedStatusAfterDelayedTouch:after.status,freshProcessAcceptedAfterDelayedTouch:freshAfter.accepted}));assert.equal(after.status,'REVOKED');assert.deepEqual(after,before,'delayed usage must leave revoked record byte-equivalent');assert.equal(freshAfter.accepted,false);assert.equal(await accepted(f),false);});
 test(`${backend}: delayed usage cannot recreate a removed credential`,async()=>{const f=await fixture(backend);const hold=holdTouch(f);assert.equal(await accepted(f),true);await hold.entered;await f.store.remove(C.MACHINE_CREDENTIAL,f.key);await hold.release();hold.restore();assert.equal(await f.store.read(C.MACHINE_CREDENTIAL,f.key),null);assert.equal((await fresh(f)).accepted,false);});
 test(`${backend}: parent revocation remains authoritative across delayed usage and repeated revoke`,async()=>{const f=await fixture(backend);const hold=holdTouch(f);assert.equal(await accepted(f),true);await hold.entered;const first=await mi.revokeIdentity(f.config,{identityId:f.identityId,creatorXOnly:f.creatorXOnly});await hold.release();hold.restore();const second=await mi.revokeIdentity(f.config,{identityId:f.identityId,creatorXOnly:f.creatorXOnly});assert.deepEqual(second,first);assert.equal((await fresh(f)).accepted,false);assert.equal(await accepted(f),false);});
 test(`${backend}: missing parent denies future resolution after an in-flight usage update`,async()=>{const f=await fixture(backend);const hold=holdTouch(f);assert.equal(await accepted(f),true);await hold.entered;await f.store.remove(C.MACHINE_IDENTITY,f.identityId);await hold.release();hold.restore();assert.equal((await fresh(f)).accepted,false);assert.equal(await accepted(f),false);});
 test(`${backend}: ordinary lastUsedAt persists without changing credential fields or scope`,async()=>{const f=await fixture(backend);const before=await f.store.read(C.MACHINE_CREDENTIAL,f.key);let pending;const original=f.store.touchMachineCredential.bind(f.store);f.store.touchMachineCredential=(...a)=>pending=original(...a);assert.equal(await accepted(f),true);assert.equal(await pending,true);const after=await f.store.read(C.MACHINE_CREDENTIAL,f.key);assert.match(after.lastUsedAt,/^\d{4}-.*Z$/);assert.deepEqual({...after,lastUsedAt:null},before);assert.equal((await fresh(f)).accepted,true);});
 test(`${backend}: out-of-order usage never regresses lastUsedAt or changes unrelated fields`,async()=>{const f=await fixture(backend);const before=await f.store.read(C.MACHINE_CREDENTIAL,f.key);before.extension={retained:['unchanged']};await f.store.write(C.MACHINE_CREDENTIAL,f.key,before);const expected={identityId:f.identityId,credentialId:f.credentialId};assert.equal(await f.store.touchMachineCredential(f.key,{...expected,lastUsedAt:'2099-02-01T00:00:00.002Z'}),true);assert.equal(await f.store.touchMachineCredential(f.key,{...expected,lastUsedAt:'2099-02-01T00:00:00.001Z'}),false);const after=await f.store.read(C.MACHINE_CREDENTIAL,f.key);assert.equal(after.lastUsedAt,'2099-02-01T00:00:00.002Z');assert.deepEqual({...after,lastUsedAt:null},before);});
 test(`${backend}: concurrent credential revocation is idempotent and siblings still resolve`,async()=>{const f=await fixture(backend);const sibling=await mi.mintCredential(f.config,{identityId:f.identityId,creatorXOnly:f.creatorXOnly,label:'sibling'});await Promise.all([revoke(f),revoke(f)]);const first=await f.store.read(C.MACHINE_CREDENTIAL,f.key);assert.equal(first.status,'REVOKED');assert.deepEqual(await revoke(f),first);assert.equal(await accepted(f),false);assert.equal((await mi.resolveBearerToken(f.config,'Bearer '+sibling.token)).credential.credentialId,sibling.record.credentialId);await next();});
 test(`${backend}: usage telemetry failure does not grant new scope or fail valid authentication`,async()=>{const f=await fixture(backend);f.store.touchMachineCredential=async()=>{throw new Error('synthetic touch failure');};assert.equal(await accepted(f),true);await next();const durable=await f.store.read(C.MACHINE_CREDENTIAL,f.key);assert.equal(durable.status,'ACTIVE');assert.equal(durable.lastUsedAt,null);});
 test(`${backend}: stale IDs, network mismatch, revoked status and malformed timestamps cannot be touched`,async()=>{const f=await fixture(backend);const baseline=await f.store.read(C.MACHINE_CREDENTIAL,f.key);const expected={identityId:f.identityId,credentialId:f.credentialId,lastUsedAt:'2099-02-01T00:00:00.001Z'};assert.equal(await f.store.touchMachineCredential(f.key,{...expected,identityId:crypto.randomUUID()}),false);assert.equal(await f.store.touchMachineCredential(f.key,{...expected,credentialId:crypto.randomUUID()}),false);assert.equal(await f.store.touchMachineCredential(f.key,{...expected,lastUsedAt:'not-a-date'}),false);assert.deepEqual(await f.store.read(C.MACHINE_CREDENTIAL,f.key),baseline);await f.store.write(C.MACHINE_CREDENTIAL,f.key,{...baseline,networkId:'wrong-network'});assert.equal(await f.store.touchMachineCredential(f.key,expected),false);await f.store.write(C.MACHINE_CREDENTIAL,f.key,{...baseline,status:'REVOKED',revokedAt:'2026-09-13T00:00:00.000Z'});assert.equal(await f.store.touchMachineCredential(f.key,expected),false);assert.equal((await f.store.read(C.MACHINE_CREDENTIAL,f.key)).lastUsedAt,null);});
 test(`${backend}: malformed stored usage types are preserved rather than coerced`,async()=>{const f=await fixture(backend);const expected={identityId:f.identityId,credentialId:f.credentialId,lastUsedAt:'2099-02-01T00:00:00.001Z'};const original=await f.store.read(C.MACHINE_CREDENTIAL,f.key);for(const value of [0,true,{},[]]){const record={...original,lastUsedAt:value};await f.store.write(C.MACHINE_CREDENTIAL,f.key,record);assert.equal(await f.store.touchMachineCredential(f.key,expected),false);assert.deepEqual(await f.store.read(C.MACHINE_CREDENTIAL,f.key),record);}});
 test(`${backend}: foreign creator cannot revoke and wrong-network bearer cannot resolve`,async()=>{const f=await fixture(backend);await assert.rejects(mi.revokeCredential(f.config,{identityId:f.identityId,credentialId:f.credentialId,creatorXOnly:'ff'.repeat(32)}),e=>e.status===404&&e.code==='MACHINE_IDENTITY_NOT_FOUND');const value=await f.store.read(C.MACHINE_CREDENTIAL,f.key);await f.store.write(C.MACHINE_CREDENTIAL,f.key,{...value,networkId:'wrong-network'});assert.equal(await accepted(f),false);assert.equal((await fresh(f)).accepted,false);});
}
if(usePg)test('postgres: queued conditional touch rechecks a concurrently committed revocation',async()=>{const f=await fixture('postgres');const hold=holdTouch(f);assert.equal(await accepted(f),true);await hold.entered;const pool=f.sdkStore.pool(),client=await pool.connect(),query=pool.query.bind(pool);let heldRevoke=false;
 try{await client.query('BEGIN');pool.query=(sql,args)=>{if(!heldRevoke&&sql.includes('INSERT INTO machine_credentials')&&JSON.parse(args[2]).status==='REVOKED'){heldRevoke=true;return client.query(sql,args);}return query(sql,args);};const revoked=await revoke(f);assert.equal(heldRevoke,true);const touch=hold.release();let waiting=false;for(let i=0;i<100;i++){const r=await query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid() AND wait_event_type='Lock' AND query LIKE 'UPDATE machine_credentials%'");if(r.rows[0].n){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'real conditional UPDATE must wait behind the row-lock revocation');await client.query('COMMIT');assert.equal(await touch,false);hold.restore();pool.query=query;assert.deepEqual(await f.store.read(C.MACHINE_CREDENTIAL,f.key),revoked);assert.equal((await fresh(f)).accepted,false);}finally{pool.query=query;try{await client.query('ROLLBACK');}catch{}client.release();}});

if(usePg)test('postgres: revocation queued behind an in-flight touch cannot resurrect authority',async()=>{const f=await fixture('postgres'),pool=f.sdkStore.pool(),client=await pool.connect(),query=pool.query.bind(pool);let boundTouch=false;
 try{await client.query('BEGIN');pool.query=(sql,args)=>{if(!boundTouch&&sql.startsWith('UPDATE machine_credentials')){boundTouch=true;return client.query(sql,args);}return query(sql,args);};assert.equal(await f.store.touchMachineCredential(f.key,{identityId:f.identityId,credentialId:f.credentialId,lastUsedAt:'2099-02-01T00:00:00.001Z'}),true);const pending=revoke(f);let waiting=false;for(let i=0;i<100;i++){const r=await query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid() AND wait_event_type='Lock' AND query LIKE 'INSERT INTO machine_credentials%'");if(r.rows[0].n){waiting=true;break;}await new Promise(r=>setTimeout(r,10));}assert.equal(waiting,true,'real revocation must wait behind the in-flight metadata update');await client.query('COMMIT');const revoked=await pending;assert.equal(revoked.status,'REVOKED');pool.query=query;assert.equal((await fresh(f)).accepted,false);assert.equal((await f.store.read(C.MACHINE_CREDENTIAL,f.key)).status,'REVOKED');}finally{pool.query=query;try{await client.query('ROLLBACK');}catch{}client.release();}});
