"use strict";

/*
 * MCP shared-core packaging sync — the ONE mechanism by which the npm
 * package `policyvault-mcp` carries the shared deterministic core modules
 * its runtime needs.
 *
 * WHY: the published 1.4.0 tarball required `../../core/model/canonical-json`
 * (a monorepo sibling path) and was therefore broken for every clean
 * npm/npx consumer. The canonical implementation of every deterministic
 * PolicyVault semantic stays in `core/` (never duplicated, never edited
 * here); this tool copies a CLOSED list of core files VERBATIM
 * (byte-identical) into `mcp/core/` — the same precedent as the browser
 * `web/core-bundle.js` (generated verbatim packaging of core sources with
 * recorded sha256 and a regenerate-and-compare gate).
 *
 * Determinism contract: same input bytes => same output bytes; no
 * timestamps, no absolute paths. `mcp/core/MANIFEST.json` records the
 * sha256 of every packaged file and of its canonical source.
 *
 * Usage: node mcp/tools/sync-core.js           (write mcp/core/)
 *        node mcp/tools/sync-core.js --check   (exit 1 on ANY drift)
 * `npm run prepack` runs --check so a drifted package can never be packed.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const MCP_ROOT = path.join(__dirname, "..");
const REPO_ROOT = path.join(MCP_ROOT, "..");
const OUT_ROOT = path.join(MCP_ROOT, "core");
const MANIFEST_PATH = path.join(OUT_ROOT, "MANIFEST.json");

/* CLOSED list: the exact shared-core files the MCP runtime closure needs.
 * Adding a file is an explicit, reviewed change here AND in the package
 * closure test (mcp/test/package-closure.test.js). */
const CORE_FILES = ["core/model/canonical-json.js"];

function sha256(buf) {
  return crypto.createHash("sha256").update(buf).digest("hex");
}

function expected() {
  return CORE_FILES.map((rel) => {
    const canonicalPath = path.join(REPO_ROOT, rel);
    if (!fs.existsSync(canonicalPath)) {
      /* Packing outside the repository (no canonical sources) is refused:
       * nothing can prove the packaged copy is byte-identical. */
      return { canonical: rel, packaged: rel.replace(/^core\//, ""), sha256: null, bytes: null };
    }
    const src = fs.readFileSync(canonicalPath);
    return { canonical: rel, packaged: rel.replace(/^core\//, ""), sha256: sha256(src), bytes: src };
  });
}

function manifestFor(entries) {
  return (
    JSON.stringify(
      {
        manifest: "policyvault-mcp-core-sync/1",
        rule: "VERBATIM byte-identical copies of the canonical shared-core sources; never edited here; regenerated by mcp/tools/sync-core.js; drift fails `npm run prepack` and mcp/test/core-sync.test.js",
        files: entries.map((e) => ({ canonical: e.canonical, packaged: e.packaged, sha256: e.sha256 }))
      },
      null,
      2
    ) + "\n"
  );
}

function check() {
  const problems = [];
  const entries = expected();
  for (const e of entries) {
    const outPath = path.join(OUT_ROOT, e.packaged);
    if (e.sha256 === null) {
      problems.push(`canonical source missing: ${e.canonical} (sync-core must run inside the PolicyVault repository)`);
      continue;
    }
    if (!fs.existsSync(outPath)) {
      problems.push(`missing packaged copy ${e.packaged}`);
      continue;
    }
    if (sha256(fs.readFileSync(outPath)) !== e.sha256) problems.push(`drift: mcp/core/${e.packaged} != canonical ${e.canonical}`);
  }
  if (entries.every((e) => e.sha256 !== null) && (!fs.existsSync(MANIFEST_PATH) || fs.readFileSync(MANIFEST_PATH, "utf8") !== manifestFor(entries))) problems.push("mcp/core/MANIFEST.json is missing or stale");
  /* nothing else may live under mcp/core (no ad-hoc files, no edits) */
  const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => (d.isDirectory() ? walk(path.join(dir, d.name)) : [path.join(dir, d.name)]));
  if (fs.existsSync(OUT_ROOT)) {
    const allowed = new Set([MANIFEST_PATH, path.join(OUT_ROOT, "README.md"), ...entries.map((e) => path.join(OUT_ROOT, e.packaged))]);
    for (const f of walk(OUT_ROOT)) if (!allowed.has(f)) problems.push(`unexpected file in mcp/core: ${path.relative(OUT_ROOT, f)}`);
  }
  return problems;
}

function write() {
  const entries = expected();
  for (const e of entries) {
    const outPath = path.join(OUT_ROOT, e.packaged);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, e.bytes);
  }
  fs.writeFileSync(MANIFEST_PATH, manifestFor(entries));
  fs.writeFileSync(
    path.join(OUT_ROOT, "README.md"),
    "# GENERATED — do not edit\n\nVerbatim, byte-identical copies of shared-core sources from `core/` (the ONE canonical implementation), packaged so the npm artifact `policyvault-mcp` is self-contained. Regenerate with `node mcp/tools/sync-core.js`; `MANIFEST.json` records every sha256; `npm run prepack` and `mcp/test/core-sync.test.js` fail on any drift.\n"
  );
}

if (require.main === module) {
  if (process.argv.includes("--check")) {
    const problems = check();
    if (problems.length) {
      console.error("sync-core: DRIFT\n  " + problems.join("\n  "));
      process.exit(1);
    }
    /* stderr, never stdout: `npm pack --json` must keep a clean JSON stdout */
    console.error(`sync-core: OK (${CORE_FILES.length} file(s) byte-identical to canonical)`);
  } else {
    if (expected().some((e) => e.sha256 === null)) {
      console.error("sync-core: canonical sources not found — run inside the PolicyVault repository");
      process.exit(1);
    }
    write();
    console.error(`sync-core: wrote ${CORE_FILES.length} file(s) into mcp/core/`);
  }
}

module.exports = { CORE_FILES, check, write, MCP_ROOT, REPO_ROOT, OUT_ROOT, MANIFEST_PATH };
