"use strict";
const {test,before,after}=require('node:test');const A=require('node:assert/strict');const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const idem=require('../src/idempotency');const {getPlatformStore,Categories}=require('../src/platform-store');
const pgEnabled=Boolean(process.env.POLICYVAULT_TEST_PG_PORT&&process.env.POLICYVAULT_TEST_PG_USER&&process.env.POLICYVAULT_TEST_PG_DATABASE);
let pgConfig,pgStore,admin,db,census;
before(async()=>{if(!pgEnabled)return;const {Pool}=require('pg');const connection={host:process.env.POLICYVAULT_TEST_PG_HOST||'127.0.0.1',port:Number(process.env.POLICYVAULT_TEST_PG_PORT),user:process.env.POLICYVAULT_TEST_PG_USER,database:process.env.POLICYVAULT_TEST_PG_DATABASE};A.deepEqual(connection,{host:'127.0.0.1',port:55438,user:'idempotency_review',database:'postgres'},'this suite requires its dedicated isolated cluster');admin=new Pool(connection);census=(await admin.query('SELECT oid,datname FROM pg_database ORDER BY datname')).rows;db='idem_'+crypto.randomBytes(8).toString('hex');await admin.query('CREATE DATABASE '+db);pgConfig=require('../../sdk/src/config').loadConfig({authMode:'enabled',authCookieInsecure:true,persistenceBackend:'postgres',pgHost:connection.host,pgPort:connection.port,pgUser:connection.user,pgDatabase:db,pgNoTls:true,dataRoot:fs.mkdtempSync(path.join(os.tmpdir(),'idem-pg-'))});pgStore=await require('../../sdk/src/store').openPgStore(pgConfig,{migrate:true});});
after(async()=>{if(!admin)return;if(pgStore)await pgStore.close();if(db)await admin.query('DROP DATABASE '+db);A.deepEqual((await admin.query('SELECT oid,datname FROM pg_database ORDER BY datname')).rows,census);await admin.end();console.log('IDEMPOTENCY_PG_CLEANUP exact database names/OIDs restored; all owned pools closed');});
function fixture(backend){const config=backend==='postgres'?pgConfig:{persistenceBackend:'json',networkId:'testnet-10',dataRoot:fs.mkdtempSync(path.join(os.tmpdir(),'idem-json-'))};const args={rawKey:crypto.randomUUID(),principal:{xOnlyPubkey:'aa'.repeat(32)},method:'POST',segments:['synthetic'],query:{},body:{amount:'1'}};return{config,args,store:getPlatformStore(config),key:idem.scopeForPrincipal(args.principal)+':'+args.rawKey};}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};}
for(const backend of ['json','postgres']){
 const options={skip:backend==='postgres'&&!pgEnabled?'set dedicated isolated POLICYVAULT_TEST_PG_* variables':false};
 test(backend+': delayed real handler cannot be reclaimed by age',options,async(t)=>{
  const f=fixture(backend),entered=deferred(),finish=deferred();let calls=0;const run=async()=>{calls++;entered.resolve();await finish.promise;return{status:201,body:{effect:1}};};const first=idem.withIdempotency(f.config,f.args,run);await entered.promise;const original=await f.store.read(Categories.IDEMPOTENCY,f.key);const now=Date.now();t.mock.method(Date,'now',()=>now+600001);
  let second;try{second=await idem.withIdempotency(f.config,f.args,async()=>{calls++;return{status:201,body:{effect:2}};});}catch(e){second=e;}finally{finish.resolve();await first;}
  A.equal(calls,1,'a genuinely active delayed handler must not execute twice');A.equal(second.code,'IDEMPOTENCY_IN_PROGRESS');const saved=await f.store.read(Categories.IDEMPOTENCY,f.key);A.equal(saved.createdAtMs,original.createdAtMs,'completion preserves original claim birth');A.equal(saved.response.body.effect,1);
 });
 test(backend+': stale different-body collision preserves claim and never dispatches',options,async(t)=>{
  const f=fixture(backend),entered=deferred(),finish=deferred();const first=idem.withIdempotency(f.config,f.args,async()=>{entered.resolve();await finish.promise;return{status:201,body:{effect:'original'}};});await entered.promise;const before=await f.store.read(Categories.IDEMPOTENCY,f.key);t.mock.method(Date,'now',()=>before.createdAtMs+600001);let calls=0,error;try{await idem.withIdempotency(f.config,{...f.args,body:{amount:'2'}},async()=>{calls++;return{status:200,body:{effect:'foreign'}};});}catch(e){error=e;}const after=await f.store.read(Categories.IDEMPOTENCY,f.key);finish.resolve();await first;A.equal(calls,0);A.equal(error?.code,'IDEMPOTENCY_KEY_CONFLICT');A.deepEqual(after,before);
 });
 for(const status of [undefined,503])test(backend+': unknown-effect throw '+String(status)+' preserves claim and refuses replay',options,async()=>{
  const f=fixture(backend);let effects=0;const effectDir=path.join(f.config.dataRoot,'effects',f.args.rawKey);const run=async()=>{effects++;require('../../sdk/src/durable-json').persistJsonDurably({filePath:path.join(effectDir,String(effects)+'.json'),value:{syntheticEffect:effects},createOnly:true});const e=Error('synthetic failure after durable effect');if(status)e.status=status;throw e;};await A.rejects(idem.withIdempotency(f.config,f.args,run));let error;try{await idem.withIdempotency(f.config,f.args,run);}catch(e){error=e;}A.equal(effects,1,'an error is not evidence that the effect did not occur');A.equal(fs.readdirSync(effectDir).length,1);A.ok(await f.store.read(Categories.IDEMPOTENCY,f.key));A.equal(error.code,'IDEMPOTENCY_OUTCOME_UNKNOWN');
 });
 test(backend+': late completion never overwrites a different claim owner',options,async()=>{
  const f=fixture(backend),entered=deferred(),finish=deferred();const first=idem.withIdempotency(f.config,f.args,async()=>{entered.resolve();await finish.promise;return{status:200,body:{winner:'old'}};});await entered.promise;const original=await f.store.read(Categories.IDEMPOTENCY,f.key);const foreign={...original,claimId:crypto.randomUUID(),status:'COMPLETE',response:{kind:'success',status:200,body:{winner:'new'}},completedAtMs:Date.now()};await f.store.write(Categories.IDEMPOTENCY,f.key,foreign);finish.resolve();let error;try{await first;}catch(e){error=e;}A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),foreign,'privileged synthetic replacement must not be overwritten by a late winner');A.equal(error?.code,'IDEMPOTENCY_OUTCOME_UNKNOWN');
 });
 test(backend+': unacknowledged claim creation never dispatches and remains uncertain',options,async(t)=>{
  const f=fixture(backend),create=f.store.createExclusive.bind(f.store);t.mock.method(f.store,'createExclusive',async(...a)=>{await create(...a);throw Error('synthetic lost INSERT acknowledgement');});let calls=0;await A.rejects(idem.withIdempotency(f.config,f.args,async()=>{calls++;return{status:200,body:{}};}),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');A.equal(calls,0);A.ok(await f.store.read(Categories.IDEMPOTENCY,f.key));
 });

 test(backend+': many concurrent requests dispatch once and replay one exact result',options,async()=>{
  const f=fixture(backend);let calls=0;const results=await Promise.allSettled(Array.from({length:20},()=>idem.withIdempotency(f.config,f.args,async()=>{calls++;await new Promise(r=>setImmediate(r));return{status:201,body:{operationId:'synthetic-once'}};})));A.equal(calls,1);A.ok(results.some(r=>r.status==='fulfilled'));for(const r of results){if(r.status==='rejected')A.equal(r.reason.code,'IDEMPOTENCY_IN_PROGRESS');else A.equal(r.value.body.operationId,'synthetic-once');}const replay=await idem.withIdempotency(f.config,f.args,()=>A.fail('must not dispatch'));A.equal(replay.body.operationId,'synthetic-once');A.equal(replay.body.idempotency.replayed,true);
 });
 test(backend+': deterministic business refusal is retained and replayed',options,async()=>{
  const f=fixture(backend);let calls=0;const run=async()=>{calls++;throw Object.assign(Error('synthetic refusal'),{status:422,code:'SYNTHETIC_REFUSAL',extra:{detail:'fixed'}});};for(const replayed of [false,true])await A.rejects(idem.withIdempotency(f.config,f.args,run),e=>e.status===422&&e.code==='SYNTHETIC_REFUSAL'&&e.extra.detail==='fixed'&&e.extra.idempotency.replayed===replayed);A.equal(calls,1);
 });
 test(backend+': returned server error also preserves uncertain effects',options,async()=>{
  const f=fixture(backend);let calls=0;const run=async()=>{calls++;return{status:503,body:{message:'synthetic effect acknowledgement lost'}};};await A.rejects(idem.withIdempotency(f.config,f.args,run),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');await A.rejects(idem.withIdempotency(f.config,f.args,run),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');A.equal(calls,1);A.equal((await idem.inspectIdempotency(f.config,f.args)).state,'UNRESOLVED');
 });
 test(backend+': prepared response survives failed completion and supports inspection/recovery without replay',options,async(t)=>{
  const f=fixture(backend),cas=f.store.compareIdempotency.bind(f.store);let calls=0;t.mock.method(f.store,'compareIdempotency',async(key,before,next)=>{if(next.status==='COMPLETE')throw Error('synthetic completion unavailable before write');return cas(key,before,next);});await A.rejects(idem.withIdempotency(f.config,f.args,async()=>{calls++;return{status:201,body:{sensitiveSyntheticResponse:'retained-original'}};}),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');const before=await f.store.read(Categories.IDEMPOTENCY,f.key);const view=await idem.inspectIdempotency(f.config,f.args);A.equal(view.state,'COMPLETION_AVAILABLE');A.equal(view.recoverable,true);A.equal(JSON.stringify(view).includes('retained-original'),false);A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),before,'inspection is read-only');t.mock.restoreAll();const recovered=await idem.recoverIdempotency(f.config,f.args);A.equal(recovered.state,'COMPLETE');A.equal(recovered.recoverable,false);const after=await f.store.read(Categories.IDEMPOTENCY,f.key);A.deepEqual(after.completionReceipt,before.completionReceipt);A.equal(after.createdAtMs,before.createdAtMs);const replay=await idem.withIdempotency(f.config,f.args,()=>A.fail('recovery must not dispatch'));A.equal(replay.body.sensitiveSyntheticResponse,'retained-original');A.equal(calls,1);
 });
 for(const phase of ['prepared','complete'])test(backend+': '+phase+' write executes but acknowledgement/readback are lost',options,async(t)=>{
  const f=fixture(backend),cas=f.store.compareIdempotency.bind(f.store),read=f.store.read.bind(f.store);let armed=false,calls=0;t.mock.method(f.store,'compareIdempotency',async(key,before,next)=>{const r=await cas(key,before,next);if((phase==='prepared'&&next.completionReceipt&&next.status==='IN_PROGRESS')||(phase==='complete'&&next.status==='COMPLETE')){armed=true;throw Error('synthetic write acknowledgement lost');}return r;});t.mock.method(f.store,'read',async(...a)=>{if(armed)throw Error('synthetic read unavailable');return read(...a);});await A.rejects(idem.withIdempotency(f.config,f.args,async()=>{calls++;return{status:201,body:{original:phase}};}),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');t.mock.restoreAll();A.equal((await idem.inspectIdempotency(f.config,f.args)).state,phase==='prepared'?'COMPLETION_AVAILABLE':'COMPLETE');const r=await idem.withIdempotency(f.config,f.args,()=>A.fail('uncertain write must not dispatch again'));A.equal(r.body.original,phase);A.equal(r.body.idempotency.replayed,true);A.equal(calls,1);A.equal((await idem.inspectIdempotency(f.config,f.args)).state,'COMPLETE');
 });
 test(backend+': exact readback resolves an unacknowledged completed update',options,async(t)=>{
  const f=fixture(backend),cas=f.store.compareIdempotency.bind(f.store);t.mock.method(f.store,'compareIdempotency',async(...a)=>{const r=await cas(...a);if(a[2].status==='COMPLETE')throw Error('synthetic completed update acknowledgement lost');return r;});const r=await idem.withIdempotency(f.config,f.args,async()=>({status:201,body:{committed:true}}));A.equal(r.body.committed,true);A.equal(r.body.idempotency.replayed,false);A.equal((await idem.inspectIdempotency(f.config,f.args)).state,'COMPLETE');
 });
 test(backend+': legacy unfinished claims stay protected while legacy completed responses still replay',options,async()=>{
  const f=fixture(backend);const legacy={schema:idem.SCHEMA,status:'IN_PROGRESS',requestFingerprint:idem.requestFingerprint(f.args),response:null,createdAtMs:1,completedAtMs:null};await f.store.createExclusive(Categories.IDEMPOTENCY,f.key,legacy);await A.rejects(idem.withIdempotency(f.config,f.args,()=>A.fail('legacy age never authorizes replay')),e=>e.code==='IDEMPOTENCY_IN_PROGRESS');const view=await idem.inspectIdempotency(f.config,f.args);A.equal(view.legacy,true);A.equal(view.recoverable,false);await A.rejects(idem.recoverIdempotency(f.config,f.args),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),legacy);
  const g=fixture(backend);await g.store.createExclusive(Categories.IDEMPOTENCY,g.key,{...legacy,requestFingerprint:idem.requestFingerprint(g.args),status:'COMPLETE',response:{kind:'success',status:200,body:{historical:true}},completedAtMs:2});const replay=await idem.withIdempotency(g.config,g.args,()=>A.fail('legacy completion must replay'));A.equal(replay.body.historical,true);A.equal(replay.body.idempotency.replayed,true);
 });
 test(backend+': recovery rejects forged receipt bindings and changed request inputs',options,async(t)=>{
  const f=fixture(backend),cas=f.store.compareIdempotency.bind(f.store);t.mock.method(f.store,'compareIdempotency',async(k,a,b)=>b.status==='COMPLETE'?false:cas(k,a,b));await A.rejects(idem.withIdempotency(f.config,f.args,async()=>({status:201,body:{original:true}})));t.mock.restoreAll();const prepared=await f.store.read(Categories.IDEMPOTENCY,f.key);
  for(const patch of [{claimId:crypto.randomUUID()},{networkId:'mainnet'},{compositeKey:'wallet:foreign:key'},{requestFingerprint:'b'.repeat(64)},{createdAtMs:0},{response:{kind:'success',status:503,body:{forged:true}}}]){const corrupt={...prepared,completionReceipt:{...prepared.completionReceipt,...patch}};await f.store.write(Categories.IDEMPOTENCY,f.key,corrupt);await A.rejects(idem.recoverIdempotency(f.config,f.args),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');await A.rejects(idem.withIdempotency(f.config,f.args,()=>A.fail('corrupt receipt must never dispatch')),e=>e.code==='IDEMPOTENCY_OUTCOME_UNKNOWN');A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),corrupt);}
  await f.store.write(Categories.IDEMPOTENCY,f.key,prepared);for(const patch of [{method:'PUT'},{segments:['other']},{query:{x:'y'}},{body:{amount:'2'}}])await A.rejects(idem.recoverIdempotency(f.config,{...f.args,...patch}),e=>e.code==='IDEMPOTENCY_KEY_CONFLICT');A.equal((await idem.inspectIdempotency(f.config,{...f.args,principal:{xOnlyPubkey:'bb'.repeat(32)}})).state,'ABSENT');A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),prepared);
 });
 test(backend+': conditional update arbitrates concurrent snapshots without insertion or completion reset',options,async()=>{
  const f=fixture(backend),claim={schema:idem.SCHEMA,status:'IN_PROGRESS',claimId:crypto.randomUUID(),requestFingerprint:idem.requestFingerprint(f.args),response:null,createdAtMs:Date.now(),completedAtMs:null};A.equal(await f.store.compareIdempotency(f.key,claim,{...claim,outcomeState:'UNKNOWN'}),false);await f.store.createExclusive(Categories.IDEMPOTENCY,f.key,claim);const next=[{...claim,outcomeState:'UNKNOWN',syntheticRace:'a'},{...claim,outcomeState:'UNKNOWN',syntheticRace:'b'}];const result=await Promise.all(next.map(n=>f.store.compareIdempotency(f.key,claim,n)));A.equal(result.filter(Boolean).length,1);A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),next[result[0]?0:1]);const complete={...claim,status:'COMPLETE',response:{kind:'success',status:201,body:{}},completedAtMs:Date.now()};await f.store.write(Categories.IDEMPOTENCY,f.key,complete);A.equal(await f.store.compareIdempotency(f.key,complete,claim),false);A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),complete);
 });

 test(backend+': fresh process recovers only the retained completion receipt',options,async(t)=>{
  const f=fixture(backend),cas=f.store.compareIdempotency.bind(f.store);t.mock.method(f.store,'compareIdempotency',async(k,a,b)=>b.status==='COMPLETE'?false:cas(k,a,b));await A.rejects(idem.withIdempotency(f.config,f.args,async()=>({status:201,body:{restartProof:'original-result'}})));t.mock.restoreAll();const c={persistenceBackend:backend,networkId:f.config.networkId,dataRoot:f.config.dataRoot,authMode:'enabled',authCookieInsecure:true,pgHost:'127.0.0.1',pgPort:55438,pgUser:'idempotency_review',pgDatabase:db,pgNoTls:true};
  const script=`const A=require('node:assert/strict'),input=JSON.parse(process.argv[1]);(async()=>{let store;try{const config=input.config.persistenceBackend==='postgres'?require('./sdk/src/config').loadConfig(input.config):input.config;if(config.persistenceBackend==='postgres')store=await require('./sdk/src/store').openPgStore(config);const m=require('./server/src/idempotency');const before=await m.inspectIdempotency(config,input.args);A.equal(before.state,'COMPLETION_AVAILABLE');const recovered=await m.recoverIdempotency(config,input.args);const replay=await m.withIdempotency(config,input.args,()=>A.fail('restart recovery cannot invoke a handler'));console.log(JSON.stringify({before,recovered,replay}));}finally{if(store)await store.close();}})().catch(e=>{console.error(e);process.exitCode=1;});`;
  const result=JSON.parse(require('node:child_process').execFileSync(process.execPath,['-e',script,JSON.stringify({config:c,args:f.args})],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8',timeout:15000}));A.equal(result.recovered.state,'COMPLETE');A.equal(result.replay.body.restartProof,'original-result');A.equal(result.replay.body.idempotency.replayed,true);
 });

 // IDEM-01: presence of any new-format field must never downgrade a record
 // into legacy compatibility merely because an owner or receipt is falsy.
 for(const [label,owner] of [['absent',undefined],['null',null],['empty',''],['false',false],['zero',0]])test(backend+': IDEM-01 retained receipt with '+label+' owner refuses every entry point',options,async()=>{
  const f=fixture(backend);await idem.withIdempotency(f.config,f.args,async()=>({status:201,body:{original:'synthetic-private-response'}}));const corrupt=await f.store.read(Categories.IDEMPOTENCY,f.key);if(owner===undefined)delete corrupt.claimId;else corrupt.claimId=owner;corrupt.completionReceipt.compositeKey='wallet:other-owner:other-key';await f.store.write(Categories.IDEMPOTENCY,f.key,corrupt);let dispatches=0;const observations=[];
  for(const [entry,call] of [['replay',()=>idem.withIdempotency(f.config,f.args,()=>{dispatches++;throw Error('must not dispatch');})],['inspect',()=>idem.inspectIdempotency(f.config,f.args)],['recover',()=>idem.recoverIdempotency(f.config,f.args)]]){try{await call();observations.push({entry,refused:false});}catch(error){observations.push({entry,refused:error.code==='IDEMPOTENCY_OUTCOME_UNKNOWN',code:error.code});}A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),corrupt,'all entry points preserve malformed bytes');}
  console.log('IDEM_01_OWNER '+JSON.stringify({backend,label,observations}));A.equal(dispatches,0);A.ok(observations.every(x=>x.refused),'new receipt owner must not bypass validation');
 });
 const malformedIndicators=[['owner-null',{claimId:null}],['owner-empty',{claimId:''}],['owner-false',{claimId:false}],['owner-zero',{claimId:0}],['owner-array',{claimId:[]}],['owner-object',{claimId:{}}],['receipt-null',{completionReceipt:null}],['receipt-false',{completionReceipt:false}],['receipt-zero',{completionReceipt:0}],['receipt-array',{completionReceipt:[]}],['receipt-object',{completionReceipt:{}}],['outcome-only',{outcomeState:'UNKNOWN'}]];
 for(const state of ['COMPLETE','IN_PROGRESS'])for(const [label,indicator]of malformedIndicators)test(backend+': IDEM-01 '+state+' '+label+' is new format and cannot be adopted as legacy',options,async()=>{
  const f=fixture(backend);const corrupt={schema:idem.SCHEMA,status:state,requestFingerprint:idem.requestFingerprint(f.args),createdAtMs:1,completedAtMs:state==='COMPLETE'?2:null,response:state==='COMPLETE'?{kind:'success',status:201,body:{syntheticLegacyShape:true}}:null,...indicator};await f.store.createExclusive(Categories.IDEMPOTENCY,f.key,corrupt);const observations=[];let dispatches=0;
  for(const [entry,call] of [['replay',()=>idem.withIdempotency(f.config,f.args,()=>{dispatches++;throw Error('must not dispatch');})],['inspect',()=>idem.inspectIdempotency(f.config,f.args)],['recover',()=>idem.recoverIdempotency(f.config,f.args)]]){try{await call();observations.push({entry,refused:false});}catch(error){observations.push({entry,refused:error.code==='IDEMPOTENCY_OUTCOME_UNKNOWN',code:error.code});}A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),corrupt);}
  console.log('IDEM_01_PRESENCE '+JSON.stringify({backend,state,label,observations}));A.equal(dispatches,0);A.ok(observations.every(x=>x.refused),'new-format field presence requires a valid owner, even when the field value is falsy');
 });
 test(backend+': IDEM-01 genuine original v1 completion has no new markers and supports all entry points unchanged',options,async()=>{
  const f=fixture(backend);const legacy={schema:idem.SCHEMA,status:'COMPLETE',requestFingerprint:idem.requestFingerprint(f.args),createdAtMs:1,completedAtMs:2,response:{kind:'success',status:201,body:{originalLegacy:true}}};await f.store.createExclusive(Categories.IDEMPOTENCY,f.key,legacy);const replay=await idem.withIdempotency(f.config,f.args,()=>A.fail('legacy response replay only'));A.equal(replay.body.originalLegacy,true);A.equal(replay.body.idempotency.replayed,true);const view=await idem.inspectIdempotency(f.config,f.args);A.equal(view.state,'COMPLETE');A.equal(view.legacy,true);A.deepEqual(await idem.recoverIdempotency(f.config,f.args),view);A.deepEqual(await f.store.read(Categories.IDEMPOTENCY,f.key),legacy);
 });
}
