"use strict";
/*
 * UNIT — core/explain/org-root-kas-explain.js over REAL SDK-built fixtures
 * (core/explain/test/fixtures/v7-kas-manifests.json, generated by
 * sdk/tools/gen-v7-kas-explain-fixtures.js): every owner operation and every
 * delegate payment renders VERIFIED_EXACT with the facts a signer must see
 * (ownership statement, principal/reserve, fee, approvals tier, delegate
 * rules, terminal payout to the pinned key, lock time); every tamper renders
 * a DO-NOT-SIGN refusal naming the failing check; wrong families and missing
 * inputs refuse; rendering is deterministic and total.
 */
const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const E = require("../org-root-kas-explain");
const { computeManifestHashV1 } = require("../../intent/canonical");

const FX = JSON.parse(fs.readFileSync(path.join(__dirname, "fixtures", "v7-kas-manifests.json"), "utf8"));
const org = (name) => { const f = FX.manifests.find((m) => m.name === name); assert.ok(f, name); return f; };
const spend = (name) => { const f = FX.spends.find((m) => m.name === name); assert.ok(f, name); return f; };
const clone = (v) => JSON.parse(JSON.stringify(v));
function tamper(manifest, mutate) { const { manifestHash, ...body } = clone(manifest); void manifestHash; mutate(body); return { ...body, manifestHash: computeManifestHashV1(body) }; }
function rehashOp(m, i = 0) { const { manifestHash, ...body } = m.vaultOperations[i].manifest; void manifestHash; m.vaultOperations[i].manifest = { ...body, manifestHash: computeManifestHashV1(body) }; }

test("every owner operation fixture renders VERIFIED_EXACT with the KAS facts (ownership, principal/reserve, approvers, rules, terminal payout) and fixed warnings", () => {
  const expectations = {
    vault_owner_pause: { warn: [], line: /Paused: 0 -> 1/ },
    vault_emergency_pause: { warn: ["EMERGENCY_QUORUM", "LANDS_FROZEN"], line: /EMERGENCY-pause/ },
    vault_owner_top_up: { warn: ["PRINCIPAL_FUNDED"], line: /Protected principal: 100 KAS -> 110 KAS/ },
    vault_owner_top_up_reserve: { warn: ["RESERVE_FUNDED"], line: /Fee reserve: 5 KAS -> 7 KAS/ },
    vault_owner_set_approvers: { warn: ["APPROVER_SET_CHANGES"], line: /Approver tier AFTER: 1 of 1 approver/ },
    vault_owner_set_agent_root: { warn: ["DELEGATE_RULES_REPLACED"], line: /New delegate rules \(1 policy\)/ },
    vault_recover: { warn: ["TERMINAL_KAS_VAULT_OPERATION"], line: /TERMINAL: this vault is CLOSED\. Payout 105 KAS \(its ENTIRE balance\) to the genesis-pinned recovery key 5151/ }
  };
  for (const f of FX.manifests) {
    const doc = E.structured({ manifest: f.manifest, redeemScripts: f.redeemScripts });
    assert.equal(doc.verdict, "VERIFIED_EXACT", `${f.name}: ${JSON.stringify(doc.refusal)}`);
    assert.equal(doc.explanationVersion, E.ORG_ROOT_KAS_EXPLANATION_VERSION_1);
    assert.equal(doc.ownership.statement, E.KAS_OWNERSHIP_STATEMENT);
    assert.equal(doc.vaultOperations.length, 1);
    const v = doc.vaultOperations[0];
    assert.equal(v.kas.protectedBefore.kas, "100");
    assert.equal(v.kas.feeReserveBefore.kas, "5");
    assert.equal(v.recoveryPk, "51".repeat(32));
    const lines = E.humanReadable({ manifest: f.manifest, redeemScripts: f.redeemScripts });
    assert.ok(lines.some((l) => l.includes(E.KAS_OWNERSHIP_STATEMENT)), `${f.name}: the ownership statement is rendered`);
    assert.ok(lines.some((l) => /Network fee of this transaction: .* KAS, paid by the fee payer/.test(l)), `${f.name}: the fee line`);
    const exp = expectations[f.name];
    assert.ok(exp, `expectation for ${f.name}`);
    for (const w of exp.warn) assert.ok(doc.warnings.some((x) => x.code === w), `${f.name}: warning ${w}`);
    assert.ok(lines.some((l) => exp.line.test(l)), `${f.name}: expected line ${exp.line} in\n${lines.join("\n")}`);
    assert.deepEqual(E.humanReadable({ manifest: f.manifest, redeemScripts: f.redeemScripts }), lines, "deterministic");
    assert.ok(lines.every((l) => !l.includes("undefined") && !l.includes("[object")), `${f.name}: no undefined rendering`);
  }
});

test("the set-agent-root operation lists every installed rule with cap / budget / threshold / fee cap / recipients in KAS; the set-approvers operation lists the tier before and after", () => {
  const sa = E.humanReadable(org("vault_owner_set_agent_root"));
  assert.ok(sa.some((l) => /delegate 6666.*: up to 2 KAS per payment, 20 KAS per 1000 DAA .*payments above 2 KAS need the vault's approvers, network fee per payment at most 0\.1 KAS/.test(l)), sa.join("\n"));
  assert.ok(sa.some((l) => /may pay ONLY these 1 recipient\(s\): 6363/.test(l)));
  const ap = E.humanReadable(org("vault_owner_set_approvers"));
  assert.ok(ap.some((l) => /Approver tier before: 1 of 2 approver\(s\): 9191/.test(l)));
  assert.ok(ap.some((l) => /Approver tier AFTER: 1 of 1 approver\(s\): 9393/.test(l)));
});

test("every tamper of an owner operation renders a DO-NOT-SIGN refusal naming the failing check: recovery redirect, successor script substitution, withheld redeem, foreign root pin, payment-family relabel", () => {
  const rec = org("vault_recover");
  const rows = [
    ["recovery destination + declared pin redirected", tamper(rec.manifest, (m) => { m.vaultOperations[0].manifest.vault.recoveryPk = "65".repeat(32); m.vaultOperations[0].manifest.policy.recoveryPk = "65".repeat(32); rehashOp(m); const f = JSON.parse(m.transaction.frozenCanonicalJson); f.outputs[0].scriptPublicKey.scriptHex = `20${"65".repeat(32)}ac`; m.transaction.frozenCanonicalJson = JSON.stringify(f); }), rec.redeemScripts, "vault[44444444].templatePinsBound"],
    ["successor script substituted on a pause", tamper(org("vault_owner_pause").manifest, (m) => { const f = JSON.parse(m.transaction.frozenCanonicalJson); const i = f.outputs.findIndex((o) => o.covenant && o.covenant.covenantId === "44".repeat(32)); f.outputs[i].scriptPublicKey.scriptHex = `aa20${"0d".repeat(32)}87`; m.transaction.frozenCanonicalJson = JSON.stringify(f); }), org("vault_owner_pause").redeemScripts, "vault[44444444].successorScriptReconstructed"],
    ["redeem withheld", org("vault_owner_pause").manifest, {}, "vault[44444444].vaultRedeemPresent"],
    ["foreign root pin", tamper(org("vault_owner_pause").manifest, (m) => { m.vaultOperations[0].manifest.vault.orgRootCovenantId = "7a".repeat(32); rehashOp(m); }), org("vault_owner_pause").redeemScripts, "vaultOp[44444444]rootPin"]
  ];
  for (const [label, manifest, redeemScripts, expected] of rows) {
    const doc = E.structured({ manifest, redeemScripts });
    assert.equal(doc.verdict, "REFUSED", label);
    assert.ok(doc.refusal.failingChecks.includes(expected), `${label}: expected ${expected}, got ${doc.refusal.failingChecks.join(",")}`);
    assert.equal(doc.vaultOperations, null, `${label}: no amounts are rendered for a refused manifest`);
    const lines = E.humanReadable({ manifest, redeemScripts });
    assert.equal(lines[0], "!! DO NOT SIGN !!");
    assert.ok(lines.some((l) => l.includes(expected)));
  }
  const payment = { ...clone(org("vault_owner_pause").manifest), manifestVersion: "policyvault-org-root-manifest/1" };
  assert.equal(E.structured({ manifest: payment }).refusal.failingChecks[0], "manifestVersion");
  const standaloneOwner = clone(org("vault_owner_pause").manifest.vaultOperations[0].manifest);
  assert.ok(E.structured({ manifest: standaloneOwner }).refusal.failingChecks.includes("verifyWithinParent"));
  assert.equal(E.structured({}).verdict, "REFUSED");
  assert.equal(E.structured(null).verdict, "REFUSED");
});

test("every delegate payment fixture renders VERIFIED_EXACT with amount / recipient / rules / fee source / approvals tier / lock time; tampers and missing inputs refuse", () => {
  const below = spend("delegate_spend_below_threshold");
  const d1 = E.structuredSpend({ manifest: below.manifest, frozen: below.frozenCanonicalJson, redeemHex: below.redeemHex });
  assert.equal(d1.verdict, "VERIFIED_EXACT", JSON.stringify(d1.refusal));
  assert.equal(d1.explanationVersion, E.KAS_SPEND_EXPLANATION_VERSION_1);
  assert.equal(d1.spend.payment.amount.kas, "1");
  assert.equal(d1.spend.payment.recipient, "63".repeat(32));
  assert.equal(d1.spend.approvals.aboveThreshold, false);
  assert.equal(d1.spend.fee.fuelFunded, false);
  assert.equal(d1.spend.policy.periodSpentAfter.kas, "1");
  assert.equal(d1.spend.policy.remainingBudgetAfter.kas, "19");
  assert.ok(d1.warnings.some((w) => w.code === "RESERVE_PAYS_FEE"));
  const l1 = E.humanReadableSpend({ manifest: below.manifest, frozen: below.frozenCanonicalJson, redeemHex: below.redeemHex });
  assert.match(l1[0], /^DELEGATE PAYMENT — 1 KAS from KAS vault 4444/);
  assert.ok(l1.some((l) => /at or below the delegate's threshold of 2 KAS — the delegate's own signature is sufficient/.test(l)));
  assert.ok(l1.some((l) => /paid from the vault's fee reserve/.test(l)));
  const above = spend("delegate_spend_above_threshold");
  const d2 = E.structuredSpend({ manifest: above.manifest, frozen: above.frozenCanonicalJson, redeemHex: above.redeemHex });
  assert.equal(d2.verdict, "VERIFIED_EXACT");
  assert.equal(d2.spend.approvals.aboveThreshold, true);
  assert.equal(d2.spend.approvals.requiredM, "1");
  assert.deepEqual(d2.spend.approvals.activeApprovers, ["91".repeat(32), "92".repeat(32)]);
  assert.ok(typeof d2.spend.approvals.approvalPackageCommitment === "string" && d2.spend.approvals.approvalPackageCommitment.length > 0, "the approval package commitment travels");
  assert.ok(d2.warnings.some((w) => w.code === "ABOVE_THRESHOLD"));
  const l2 = E.humanReadableSpend({ manifest: above.manifest, frozen: above.frozenCanonicalJson, redeemHex: above.redeemHex });
  assert.ok(l2.some((l) => /ABOVE the delegate's threshold of 2 KAS — 1 of 2 vault approver\(s\) must co-sign/.test(l)));
  const roll = spend("delegate_spend_period_rollover");
  const d3 = E.structuredSpend({ manifest: roll.manifest, frozen: roll.frozenCanonicalJson, redeemHex: roll.redeemHex });
  assert.equal(d3.verdict, "VERIFIED_EXACT");
  assert.equal(d3.spend.lockTime, "6000");
  assert.ok(d3.warnings.some((w) => w.code === "PERIOD_ROLLOVER"));
  assert.ok(E.humanReadableSpend({ manifest: roll.manifest, frozen: roll.frozenCanonicalJson, redeemHex: roll.redeemHex }).some((l) => /Lock time: 6000/.test(l)));
  /* refusals */
  const noFrozen = E.structuredSpend({ manifest: below.manifest, redeemHex: below.redeemHex });
  assert.equal(noFrozen.verdict, "REFUSED"); assert.ok(noFrozen.refusal.failingChecks.includes("frozenSupplied"));
  const noRedeem = E.structuredSpend({ manifest: below.manifest, frozen: below.frozenCanonicalJson });
  assert.ok(noRedeem.refusal.failingChecks.includes("vault[44444444].vaultRedeemPresent"));
  const recipientSwap = tamper(below.manifest, (m) => { m.policy.recipient = "65".repeat(32); });
  assert.ok(E.structuredSpend({ manifest: recipientSwap, frozen: below.frozenCanonicalJson, redeemHex: below.redeemHex }).refusal.failingChecks.includes("vault[44444444].outputZeroIsRecipient"));
  const capLie = tamper(below.manifest, (m) => { m.policy.agentPolicy.maxPerSpend = "1"; });
  assert.ok(E.structuredSpend({ manifest: capLie, frozen: below.frozenCanonicalJson, redeemHex: below.redeemHex }).refusal.failingChecks.includes("vault[44444444].spendWithinCap"));
  const badSucc = JSON.parse(below.frozenCanonicalJson); badSucc.outputs[1].scriptPublicKey.scriptHex = `aa20${"0d".repeat(32)}87`;
  assert.ok(E.structuredSpend({ manifest: below.manifest, frozen: badSucc, redeemHex: below.redeemHex }).refusal.failingChecks.includes("vault[44444444].successorScriptReconstructed"));
  const ownerAsSpend = clone(org("vault_owner_pause").manifest.vaultOperations[0].manifest);
  assert.ok(E.structuredSpend({ manifest: ownerAsSpend, frozen: JSON.parse(org("vault_owner_pause").frozenCanonicalJson) }).refusal.failingChecks.includes("verifyWithinParent"));
  assert.equal(E.humanReadableSpend({ manifest: recipientSwap, frozen: below.frozenCanonicalJson, redeemHex: below.redeemHex })[0], "!! DO NOT SIGN !!");
});
