//! VM layer — PRODUCTION CANDIDATE `contracts/PolicyVault.v0.7-kas.sil`
//! (contract `PolicyVaultRootedKas`, generated by `tools/gen_v7_kas.js` as an
//! exact-match delta over the FROZEN `contracts/PolicyVault.v0.4.1.sil`)
//! driven through the real TxScriptEngine (covenants enabled, real Schnorr),
//! together with the PRODUCTION root `contracts/PolicyVault.v0.7-root.sil`.
//!
//! This is the ROOTED KAS SAFE-PAYMENT PROFILE: the SAME byte-level
//! root-successor pinning as `v7_payment_production.rs`
//! (`requireRootAuthorization`, the ROOT_TAIL constants,
//! `requireOnlyRootCovenantInputs`), applied to the frozen v0.4.1 plain-KAS
//! covenant instead of the frozen v0.5 token controller. Every v0.4.1
//! delegate-side rule (per-spend cap, period budget + rollover, recipient
//! Merkle allowlist, vault-level M-of-N approvals above a threshold, agent
//! Merkle set, fee-reserve conservation, exact successor value, pause) is
//! carried byte-for-byte; the root replaces the removed owner key for every
//! owner-side operation (ownerControl selectors 0..6, ownerRecover).
//!
//! `contracts/PolicyVault.v0.4.1.sil` and `contracts/PolicyVault.v0.7-root.sil`
//! are opened READ-ONLY as production baselines; neither is ever modified.

use std::sync::OnceLock;

use secp256k1::Keypair;
use sha2::{Digest, Sha256};
use silverscript_lang::ast::Expr;
use silverscript_lang::compiler::{compile_contract, struct_object, CompileOptions, CompiledContract, CovenantDeclCallOptions};

use kaspa_consensus_core::constants::STORAGE_MASS_PARAMETER;
use kaspa_consensus_core::hashing::sighash::{calc_schnorr_signature_hash, SigHashReusedValuesUnsync};
use kaspa_consensus_core::hashing::sighash_type::{
    SigHashType, SIG_HASH_ALL, SIG_HASH_ANY_ONE_CAN_PAY, SIG_HASH_NONE, SIG_HASH_SINGLE,
};
use kaspa_consensus_core::mass::units::{ComputeBudget, ScriptUnits};
use kaspa_consensus_core::mass::{transaction_estimated_serialized_size, MassCalculator};
use kaspa_consensus_core::subnets::SubnetworkId;
use kaspa_consensus_core::tx::{
    ComputeCommit, CovenantBinding, MutableTransaction, PopulatedTransaction, ScriptPublicKey, Transaction, TransactionId,
    TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
};
use kaspa_consensus_core::Hash;
use kaspa_txscript::opcodes::codes::OpCheckSig;
use kaspa_txscript::script_class::ScriptClass;
use kaspa_txscript::{pay_to_script_hash_script, post_toccata_p2sh_sig_scanner, script_builder::ScriptBuilder, EngineFlags};
use kaspa_txscript_errors::TxScriptError;
use policyvault_vm_tests::{execute_input_measured, execute_input_measured_priced};

/* ================================================================== */
/* constants                                                           */
/* ================================================================== */

const N_SLOTS: usize = 12; // root owner slots
const SIG_BLOB_LEN: usize = N_SLOTS * 65; // 780
const ROOT_TAIL_LEN: usize = 11;
const N_APPROVERS: usize = 10; // vault-level approver slots (unchanged from v0.4.1)

const COV_ROOT: Hash = Hash::from_bytes(*b"ROOTROOTROOTROOTROOTROOTROOTROOT");
const COV_ROOT_B: Hash = Hash::from_bytes(*b"ROOTBROOTBROOTBROOTBROOTBROOTBRO");
const COV_VAULT: Hash = Hash::from_bytes(*b"KASVLKASVLKASVLKASVLKASVLKASVLKA");
const COV_ALIEN: Hash = Hash::from_bytes(*b"ALIENALIENALIENALIENALIENALIENAL");

const ZERO32: [u8; 32] = [0u8; 32];
const ORG_ID: [u8; 32] = [0xa7u8; 32];
const ORG_ID_B: [u8; 32] = [0xb7u8; 32];
const VAULT_ID: [u8; 32] = [0x44u8; 32];
const AGENT_DOMAIN: [u8; 4] = [0x50, 0x56, 0x34, 0x01];
const RECIP_DOMAIN: [u8; 4] = [0x50, 0x56, 0x33, 0x01];

const KAS: i64 = 100_000_000;
const ROOT_KAS: i64 = 3 * KAS;
const ROOT_MAX_FEE: i64 = 200_000;
const ROOT_FEE_PAID: i64 = 50_000;
const RECOVERY_DELAY: i64 = 1_000;
const SUCCESSION_DELAY: i64 = 2_000;

const PROTECTED: i64 = 10_000 * KAS;
const RESERVE: i64 = 5 * KAS;

const MAX_STANDARD_P2SH_SIG_OPS: u64 = 15;

const OWNER_SEEDS: [u8; N_SLOTS] = [0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c];
const SUCCESSOR_SEED: u8 = 0x7f;
const OUTSIDER_SEED: u8 = 0x6f;
const RECOVERY_SEED: u8 = 0x51;

/* ================================================================== */
/* generic helpers (profile-agnostic; identical to v7_payment_production.rs) */
/* ================================================================== */

fn kp(seed: u8) -> Keypair {
    let secp = secp256k1::Secp256k1::new();
    let sk = secp256k1::SecretKey::from_slice(&[seed; 32]).expect("seed key");
    Keypair::from_secret_key(&secp, &sk)
}
fn xonly32(k: &Keypair) -> [u8; 32] {
    k.x_only_public_key().0.serialize()
}
fn hx(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}
fn sha256(parts: &[&[u8]]) -> [u8; 32] {
    let mut h = Sha256::new();
    for p in parts {
        h.update(p);
    }
    h.finalize().into()
}
fn num8(v: i64) -> [u8; 8] {
    (v as u64).to_le_bytes()
}
fn leak(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}
fn load(rel: &str) -> String {
    let path = format!("{}/{rel}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"))
}
/// THE PRODUCTION ROOT.
fn src_root() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../contracts/PolicyVault.v0.7-root.sil")))
}
/// THE PRODUCTION ROOTED KAS PROFILE.
fn src_kas_raw() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../contracts/PolicyVault.v0.7-kas.sil")))
}

#[derive(Clone)]
struct Template {
    prefix: Vec<u8>,
    state_len: usize,
    suffix: Vec<u8>,
    hash: [u8; 32],
}
fn template_of(c: &CompiledContract<'_>) -> Template {
    let l = c.state_layout;
    let prefix = c.script[..l.start].to_vec();
    let suffix = c.script[l.start + l.len..].to_vec();
    let h = blake2b_simd::Params::new().hash_length(32).to_state().update(&prefix).update(&suffix).finalize();
    let mut hash = [0u8; 32];
    hash.copy_from_slice(h.as_bytes());
    Template { prefix, state_len: l.len, suffix, hash }
}

fn push_redeem(script: &[u8]) -> Vec<u8> {
    ScriptBuilder::with_flags(EngineFlags { covenants_enabled: true, ..Default::default() }).add_data(script).unwrap().drain()
}
fn cov_call_opt(c: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>, is_leader: bool) -> Vec<u8> {
    let mut s = c.build_sig_script_for_covenant_decl(f, args, CovenantDeclCallOptions { is_leader }).unwrap_or_else(|e| panic!("call {f}: {e:?}"));
    s.extend_from_slice(&push_redeem(&c.script));
    s
}
fn cov_call(c: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>) -> Vec<u8> {
    cov_call_opt(c, f, args, false)
}
/// Build the call for `c`'s ABI but append a DIFFERENT contract's redeem — the
/// "revealed redeem does not match this input's own P2SH" substitution the
/// byte-level pin must refuse before it reads a single tail byte.
fn cov_call_with_decoy_redeem(c: &CompiledContract<'_>, decoy: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>) -> Vec<u8> {
    let mut s = c.build_sig_script_for_covenant_decl(f, args, CovenantDeclCallOptions { is_leader: false }).unwrap_or_else(|e| panic!("call {f}: {e:?}"));
    s.extend_from_slice(&push_redeem(&decoy.script));
    s
}
fn tx_input(id: u8, sigscript: Vec<u8>, sequence: u64, budget: u16) -> TransactionInput {
    TransactionInput::new_with_mass(
        TransactionOutpoint { transaction_id: TransactionId::from_bytes([id; 32]), index: 0 },
        sigscript,
        sequence,
        ComputeCommit::ComputeBudget(ComputeBudget(budget)),
    )
}
fn cov_out(value: i64, c: &CompiledContract<'_>, auth: u16, covid: Hash) -> TransactionOutput {
    TransactionOutput {
        value: value as u64,
        script_public_key: pay_to_script_hash_script(&c.script),
        covenant: Some(CovenantBinding { authorizing_input: auth, covenant_id: covid }),
    }
}
fn cov_utxo(value: i64, c: &CompiledContract<'_>, covid: Hash) -> UtxoEntry {
    UtxoEntry::new(value as u64, pay_to_script_hash_script(&c.script), 0, false, Some(covid))
}
fn p2pk_spk(pk: &[u8; 32]) -> ScriptPublicKey {
    ScriptPublicKey::new(0, ScriptBuilder::new().add_data(pk).unwrap().add_op(OpCheckSig).unwrap().drain().into())
}
fn p2pk_out(pk: &[u8; 32], value: i64) -> TransactionOutput {
    TransactionOutput { value: value as u64, script_public_key: p2pk_spk(pk), covenant: None }
}
fn p2pk_sigscript(sig: Vec<u8>) -> Vec<u8> {
    ScriptBuilder::new().add_data(&sig).unwrap().drain()
}
fn build_tx(inputs: Vec<TransactionInput>, outputs: Vec<TransactionOutput>) -> Transaction {
    Transaction::new(1, inputs, outputs, 0, SubnetworkId::default(), 0, vec![])
}
fn sign_type(tx: &Transaction, entries: &[UtxoEntry], idx: usize, k: &Keypair, ht: SigHashType) -> Vec<u8> {
    let m = MutableTransaction::with_entries(tx.clone(), entries.to_vec());
    let reused = SigHashReusedValuesUnsync::new();
    let h = calc_schnorr_signature_hash(&m.as_verifiable(), idx, ht, &reused);
    let msg = secp256k1::Message::from_digest_slice(h.as_bytes().as_slice()).unwrap();
    let mut out = k.sign_schnorr(msg).as_ref().to_vec();
    out.push(ht.to_u8());
    out
}
fn sign(tx: &Transaction, entries: &[UtxoEntry], idx: usize, k: &Keypair) -> Vec<u8> {
    sign_type(tx, entries, idx, k, SIG_HASH_ALL)
}
fn placeholder_slot() -> Vec<u8> {
    let mut v = vec![0u8; 64];
    v.push(0x01);
    v
}
fn assert_rejected(result: Result<(), TxScriptError>, label: &str) {
    assert!(result.is_err(), "{label}: expected covenant rejection but the VM accepted the transaction");
}

/* ---------------- Merkle (identical construction to v0.4.1/v0.5 suites) - */

fn merkle(leaves: &[[u8; 32]], target: usize) -> ([u8; 32], Vec<u8>, u64) {
    let mut level = leaves.to_vec();
    while level.len().count_ones() != 1 {
        level.push(*level.last().unwrap());
    }
    let (mut idx, mut sibs, mut bits, mut lvl) = (target, Vec::new(), 0u64, 0);
    while level.len() > 1 {
        let s = if idx % 2 == 0 { idx + 1 } else { idx - 1 };
        sibs.extend_from_slice(&level[s]);
        if idx % 2 == 1 {
            bits |= 1 << lvl;
        }
        let mut next = Vec::with_capacity(level.len() / 2);
        for pair in level.chunks(2) {
            next.push(sha256(&[&pair[0], &pair[1]]));
        }
        idx /= 2;
        level = next;
        lvl += 1;
    }
    (level[0], sibs, bits)
}
/// Fold a leaf up a co-path (siblings + pathBits) to the root — the exact
/// covenant computeMerkleRoot, used to derive the correct successor root.
fn fold(leaf: [u8; 32], sibs: &[u8], mut bits: u64) -> [u8; 32] {
    let mut node = leaf;
    let depth = sibs.len() / 32;
    for level in 0..depth {
        let sib: [u8; 32] = sibs[level * 32..level * 32 + 32].try_into().unwrap();
        node = if bits & 1 == 1 { sha256(&[&sib, &node]) } else { sha256(&[&node, &sib]) };
        bits >>= 1;
    }
    node
}
fn recip_tree(depth: u32, target: &[u8; 32]) -> ([u8; 32], Vec<u8>, u64) {
    if depth == 0 {
        return (sha256(&[&RECIP_DOMAIN, target]), vec![], 0);
    }
    let n = 1usize << depth;
    let mut leaves: Vec<[u8; 32]> = (0..n).map(|i| sha256(&[&RECIP_DOMAIN, &(i as u64 + 900).to_le_bytes()])).collect();
    leaves[1] = sha256(&[&RECIP_DOMAIN, target]);
    merkle(&leaves, 1)
}

/* ================================================================== */
/* the PRODUCTION root covenant (the vault's owner authority)          */
/* ================================================================== */

#[derive(Clone, PartialEq, Debug)]
struct RootState {
    org_id: [u8; 32],
    owners: [[u8; 32]; N_SLOTS],
    owner_m: i64,
    emergency_k: i64,
    recovery_m: i64,
    frozen: i64,
    nonce: i64,
}
impl RootState {
    fn with(n: usize, m: i64, k: i64, r: i64) -> RootState {
        let mut owners = [ZERO32; N_SLOTS];
        for (i, o) in owners.iter_mut().enumerate().take(n) {
            *o = xonly32(&kp(OWNER_SEEDS[i]));
        }
        RootState { org_id: ORG_ID, owners, owner_m: m, emergency_k: k, recovery_m: r, frozen: 0, nonce: 0 }
    }
    fn advanced(&self) -> RootState {
        RootState { nonce: self.nonce + 1, ..self.clone() }
    }
}

#[derive(Clone)]
struct RootTemplate {
    recovery_delay: i64,
    successor_pk: [u8; 32],
    succession_delay: i64,
    max_fee: i64,
}
impl Default for RootTemplate {
    fn default() -> Self {
        RootTemplate {
            recovery_delay: RECOVERY_DELAY,
            successor_pk: xonly32(&kp(SUCCESSOR_SEED)),
            succession_delay: SUCCESSION_DELAY,
            max_fee: ROOT_MAX_FEE,
        }
    }
}

fn compile_root(s: &RootState, t: &RootTemplate) -> CompiledContract<'static> {
    let mut args: Vec<Expr<'static>> = vec![Expr::bytes(s.org_id.to_vec())];
    for o in s.owners.iter() {
        args.push(Expr::bytes(o.to_vec()));
    }
    for v in [s.owner_m, s.emergency_k, s.recovery_m] {
        args.push(Expr::int(v));
    }
    args.push(Expr::byte(s.frozen as u8));
    args.push(Expr::bytes(num8(s.nonce).to_vec()));
    args.push(Expr::int(t.recovery_delay));
    args.push(Expr::bytes(t.successor_pk.to_vec()));
    args.push(Expr::int(t.succession_delay));
    args.push(Expr::int(t.max_fee));
    compile_contract(src_root(), &args, CompileOptions::default()).unwrap_or_else(|e| panic!("compile production root: {e:?}"))
}

const ROOT_SLOT_NAMES: [&str; N_SLOTS] =
    ["owner1", "owner2", "owner3", "owner4", "owner5", "owner6", "owner7", "owner8", "owner9", "owner10", "owner11", "owner12"];

fn root_state_arg(s: &RootState) -> Expr<'static> {
    let mut f: Vec<(&'static str, Expr<'static>)> = vec![("boundOrgId", Expr::bytes(s.org_id.to_vec()))];
    for (i, n) in ROOT_SLOT_NAMES.iter().enumerate() {
        f.push((n, Expr::bytes(s.owners[i].to_vec())));
    }
    f.push(("ownerM", Expr::int(s.owner_m)));
    f.push(("emergencyK", Expr::int(s.emergency_k)));
    f.push(("recoveryM", Expr::int(s.recovery_m)));
    f.push(("frozen", Expr::byte(s.frozen as u8)));
    f.push(("rootNonce", Expr::bytes(num8(s.nonce).to_vec())));
    struct_object(f)
}

fn root_owner_blob(tx: &Transaction, entries: &[UtxoEntry], idx: usize, signers: &[usize]) -> Vec<u8> {
    let mut slots: Vec<Vec<u8>> = (0..N_SLOTS).map(|_| placeholder_slot()).collect();
    for i in signers.iter() {
        slots[*i] = sign(tx, entries, idx, &kp(OWNER_SEEDS[*i]));
    }
    let blob: Vec<u8> = slots.into_iter().flatten().collect();
    assert_eq!(blob.len(), SIG_BLOB_LEN);
    blob
}

#[derive(Clone)]
struct RootPin {
    covid: Hash,
    hash: [u8; 32],
    prefix_len: i64,
    state_len: i64,
    suffix_len: i64,
}
fn root_pin(covid: Hash, tmpl: &RootTemplate) -> RootPin {
    let sample = compile_root(&RootState::with(1, 1, 1, 0), tmpl);
    let t = template_of(&sample);
    RootPin { covid, hash: t.hash, prefix_len: t.prefix.len() as i64, state_len: t.state_len as i64, suffix_len: t.suffix.len() as i64 }
}
fn default_recovery_pk() -> [u8; 32] {
    xonly32(&kp(RECOVERY_SEED))
}
fn default_root_pin() -> RootPin {
    root_pin(COV_ROOT, &RootTemplate::default())
}

/* ================================================================== */
/* the PRODUCTION rooted KAS profile                                   */
/* ================================================================== */

#[derive(Clone, PartialEq, Debug)]
struct VaultState {
    protected: i64,
    reserve: i64,
    paused: i64,
    agent_root: [u8; 32],
    approvers: [[u8; 32]; N_APPROVERS],
    approval_m: i64,
    policy_nonce: i64,
}
fn base_vault_state(agent_root: [u8; 32]) -> VaultState {
    VaultState { protected: PROTECTED, reserve: RESERVE, paused: 0, agent_root, approvers: [ZERO32; N_APPROVERS], approval_m: 0, policy_nonce: 0 }
}

/// Exact-live-state templating — same anchors the v0.4.1 production suite
/// uses; the delta generator never touches them.
fn vault_templated(src: &str, s: &VaultState) -> String {
    let mut src = src.to_string();
    let mut r = |from: String, to: String| {
        assert!(src.contains(&from), "anchor missing: {from}");
        src = src.replacen(&from, &to, 1);
    };
    r("int protectedValue = initValue;".into(), format!("int protectedValue = {};", s.protected));
    r("int feeReserve = initFeeReserve;".into(), format!("int feeReserve = {};", s.reserve));
    r("int paused = 0;".into(), format!("int paused = {};", s.paused));
    r("byte[32] agentRoot = initAgentRoot;".into(), format!("byte[32] agentRoot = 0x{};", hx(&s.agent_root)));
    for i in 0..N_APPROVERS {
        r(format!("pubkey approver{} = initApprover{};", i + 1, i + 1), format!("pubkey approver{} = 0x{};", i + 1, hx(&s.approvers[i])));
    }
    r("int approvalM = initApprovalM;".into(), format!("int approvalM = {};", s.approval_m));
    r("int policyNonce = 0;".into(), format!("int policyNonce = {};", s.policy_nonce));
    src
}

fn compile_vault(root: &RootPin, recovery_pk: &[u8; 32], s: &VaultState) -> CompiledContract<'static> {
    let src: &'static str = leak(vault_templated(src_kas_raw(), s));
    let mut args: Vec<Expr<'static>> = vec![
        Expr::bytes(VAULT_ID.to_vec()),
        Expr::bytes(root.covid.as_bytes().to_vec()),
        Expr::bytes(root.hash.to_vec()),
        Expr::int(root.prefix_len),
        Expr::int(root.state_len),
        Expr::int(root.suffix_len),
        Expr::bytes(recovery_pk.to_vec()),
        Expr::bytes(s.agent_root.to_vec()),
        Expr::int(s.reserve),
    ];
    for i in 0..N_APPROVERS {
        args.push(Expr::bytes(s.approvers[i].to_vec()));
    }
    args.push(Expr::int(s.approval_m));
    args.push(Expr::int(s.protected));
    compile_contract(src, &args, CompileOptions::default()).unwrap_or_else(|e| panic!("compile v0.7-kas: {e:?}"))
}

const APPROVER_NAMES: [&str; N_APPROVERS] =
    ["approver1", "approver2", "approver3", "approver4", "approver5", "approver6", "approver7", "approver8", "approver9", "approver10"];

fn vault_state_arg(s: &VaultState) -> Expr<'static> {
    let mut f: Vec<(&'static str, Expr<'static>)> = vec![
        ("boundVaultId", Expr::bytes(VAULT_ID.to_vec())),
        ("protectedValue", Expr::int(s.protected)),
        ("feeReserve", Expr::int(s.reserve)),
        ("paused", Expr::int(s.paused)),
        ("agentRoot", Expr::bytes(s.agent_root.to_vec())),
    ];
    for i in 0..N_APPROVERS {
        f.push((APPROVER_NAMES[i], Expr::bytes(s.approvers[i].to_vec())));
    }
    f.push(("approvalM", Expr::int(s.approval_m)));
    f.push(("policyNonce", Expr::int(s.policy_nonce)));
    struct_object(f)
}

/// Align each signer to the slot holding its sorted key (v0.4.1 pattern).
fn approver_set(keys: &[&Keypair]) -> [[u8; 32]; N_APPROVERS] {
    let mut active: Vec<[u8; 32]> = keys.iter().map(|k| xonly32(k)).collect();
    active.sort();
    let mut a = [ZERO32; N_APPROVERS];
    for (i, k) in active.iter().enumerate() {
        a[i] = *k;
    }
    a
}
fn approvals_by_key<'a>(slots: &[[u8; 32]; N_APPROVERS], signers: &[(&'a Keypair, SigHashType)]) -> [Option<(&'a Keypair, SigHashType)>; N_APPROVERS] {
    let mut ap: [Option<(&'a Keypair, SigHashType)>; N_APPROVERS] = Default::default();
    for i in 0..N_APPROVERS {
        for (s, ty) in signers {
            if xonly32(s) == slots[i] {
                ap[i] = Some((*s, *ty));
            }
        }
    }
    ap
}

/* ================================================================== */
/* vault owner operations (root + vault, ONE transaction)               */
/* ================================================================== */

#[derive(Clone, Copy, PartialEq, Debug)]
enum VaultOp {
    /// the merged entrypoint, selectors 0..6 (6 = EMERGENCY pause under FREEZE)
    Control(i64),
    Recover,
}

#[derive(Clone)]
struct VaultCase {
    op: VaultOp,
    root_prev: RootState,
    root_new: Option<RootState>,
    root_action: i64,
    root_signers: Vec<usize>,
    root_tmpl: RootTemplate,
    root_tmpl_carried: Option<RootTemplate>,
    root_tmpl_output: Option<RootTemplate>,
    root_decoy_state: Option<RootState>,
    root_covid_carried: Hash,
    root_covid_pinned: Hash,
    root_succession: Option<u8>,
    root_sequence: u64,
    vault_prev: VaultState,
    vault_new: VaultState,
    no_root: bool,
    two_roots: bool,
    alien_rider: bool,
    vault_succ_value: Option<i64>,
    recover_dest: Option<[u8; 32]>,
    wrong_root_template: bool,
    budget: u16,
}
impl VaultCase {
    fn honest(op: VaultOp) -> VaultCase {
        let root_prev = RootState::with(3, 2, 1, 2);
        // selector 6 is the EMERGENCY pause: it must ride a root FREEZE
        let (action, signers) = match op {
            VaultOp::Control(6) => (2i64, vec![0usize]),
            _ => (0i64, vec![0usize, 1usize]),
        };
        let vault_prev = base_vault_state(ZERO32);
        let vault_new = match op {
            VaultOp::Control(0) => VaultState { agent_root: [0x99; 32], policy_nonce: vault_prev.policy_nonce + 1, ..vault_prev.clone() },
            VaultOp::Control(1) => {
                let approver_keys: Vec<Keypair> = vec![kp(0x24), kp(0x25), kp(0x26)];
                let refs: Vec<&Keypair> = approver_keys.iter().collect();
                let approvers = approver_set(&refs);
                VaultState { approvers, approval_m: 2, policy_nonce: vault_prev.policy_nonce + 1, ..vault_prev.clone() }
            }
            VaultOp::Control(2) => VaultState { protected: vault_prev.protected + KAS, ..vault_prev.clone() },
            VaultOp::Control(3) => VaultState { reserve: vault_prev.reserve + KAS, ..vault_prev.clone() },
            VaultOp::Control(4) => VaultState { paused: 1, ..vault_prev.clone() },
            VaultOp::Control(5) => VaultState { paused: 0, ..vault_prev.clone() },
            VaultOp::Control(6) => VaultState { paused: 1, ..vault_prev.clone() },
            _ => vault_prev.clone(),
        };
        let vault_prev = if op == VaultOp::Control(5) { VaultState { paused: 1, ..vault_prev } } else { vault_prev };
        VaultCase {
            op,
            root_prev,
            root_new: None,
            root_action: action,
            root_signers: signers,
            root_tmpl: RootTemplate::default(),
            root_tmpl_carried: None,
            root_tmpl_output: None,
            root_decoy_state: None,
            root_covid_carried: COV_ROOT,
            root_covid_pinned: COV_ROOT,
            root_succession: None,
            root_sequence: 0,
            vault_prev,
            vault_new,
            no_root: false,
            two_roots: false,
            alien_rider: false,
            vault_succ_value: None,
            recover_dest: None,
            wrong_root_template: false,
            budget: 400,
        }
    }
}

struct VaultOutcome {
    results: Vec<Result<(), TxScriptError>>,
    units: Vec<u64>,
    tx: Transaction,
    entries: Vec<UtxoEntry>,
    vault_redeem_len: usize,
    root_redeem_len: usize,
}

fn run_vault_owner_op(c: &VaultCase) -> VaultOutcome {
    let recovery_pk = default_recovery_pk();
    let rpin_tmpl =
        if c.wrong_root_template { RootTemplate { recovery_delay: RECOVERY_DELAY + 7, ..RootTemplate::default() } } else { c.root_tmpl.clone() };
    let rpin = root_pin(c.root_covid_pinned, &rpin_tmpl);

    let vault_prev_c = compile_vault(&rpin, &recovery_pk, &c.vault_prev);
    let vault_next_c = compile_vault(&rpin, &recovery_pk, &c.vault_new);

    let carried_tmpl = c.root_tmpl_carried.clone().unwrap_or_else(|| c.root_tmpl.clone());
    let output_tmpl = c.root_tmpl_output.clone().unwrap_or_else(|| carried_tmpl.clone());
    let root_prev_c = compile_root(&c.root_prev, &carried_tmpl);
    let expect_frozen = if c.op == VaultOp::Control(6) { 1 } else { 0 };
    let root_new = c.root_new.clone().unwrap_or(RootState { frozen: expect_frozen, ..c.root_prev.advanced() });
    let root_next_c = compile_root(&root_new, &output_tmpl);

    let vault_utxo_value = c.vault_prev.protected + c.vault_prev.reserve;
    let mut entries: Vec<UtxoEntry> = vec![cov_utxo(vault_utxo_value, &vault_prev_c, COV_VAULT)];
    let mut input_ids: Vec<(u8, u64)> = vec![(1, 0)];
    let mut outputs: Vec<TransactionOutput> = vec![];

    let root_input_idx: u16 = 1;
    if !c.no_root {
        entries.push(cov_utxo(ROOT_KAS, &root_prev_c, c.root_covid_carried));
        input_ids.push((2, c.root_sequence));
    }
    let recover_dest = c.recover_dest.unwrap_or(recovery_pk);
    match c.op {
        VaultOp::Recover => outputs.push(p2pk_out(&recover_dest, vault_utxo_value)),
        _ => outputs.push(cov_out(c.vault_succ_value.unwrap_or(c.vault_new.protected + c.vault_new.reserve), &vault_next_c, 0, COV_VAULT)),
    }
    if !c.no_root {
        outputs.push(cov_out(ROOT_KAS - ROOT_FEE_PAID, &root_next_c, root_input_idx, c.root_covid_carried));
    }

    let mut second_root_idx: Option<usize> = None;
    if c.two_roots {
        second_root_idx = Some(input_ids.len());
        entries.push(cov_utxo(ROOT_KAS, &root_prev_c, c.root_covid_carried));
        input_ids.push((4, c.root_sequence));
        outputs.push(cov_out(ROOT_KAS - ROOT_FEE_PAID, &root_next_c, second_root_idx.unwrap() as u16, c.root_covid_carried));
    }
    if c.alien_rider {
        // stand-in foreign covenant family: another compiled instance of
        // this same contract, bound to a DIFFERENT covenant id (COV_ALIEN),
        // demonstrating that requireOnlyRootCovenantInputs refuses ANY
        // covenant family other than the root, not merely a specific one.
        // Its own execution result is never checked.
        let alien_state = base_vault_state([0x55; 32]);
        let alien_c = compile_vault(&rpin, &recovery_pk, &alien_state);
        let idx = input_ids.len();
        entries.push(cov_utxo(KAS, &alien_c, COV_ALIEN));
        input_ids.push((5, 0));
        outputs.push(cov_out(KAS, &alien_c, idx as u16, COV_ALIEN));
    }

    let unsigned = build_tx(input_ids.iter().map(|(id, seq)| tx_input(*id, vec![], *seq, c.budget)).collect(), outputs.clone());

    let mut sigscripts: Vec<Vec<u8>> = input_ids.iter().map(|_| vec![]).collect();
    sigscripts[0] = match c.op {
        VaultOp::Control(sel) => cov_call(&vault_prev_c, "ownerControl", vec![vault_state_arg(&c.vault_new), Expr::int(sel)]),
        VaultOp::Recover => cov_call(&vault_prev_c, "ownerRecover", vec![Vec::<Expr<'static>>::new().into()]),
    };
    if !c.no_root {
        let root_ss = match c.root_succession {
            Some(seed) => {
                let s = sign(&unsigned, &entries, 1, &kp(seed));
                cov_call(&root_prev_c, "rootSuccession", vec![root_state_arg(&root_new), Expr::bytes(s)])
            }
            None => {
                let blob = root_owner_blob(&unsigned, &entries, 1, &c.root_signers);
                let args = vec![root_state_arg(&root_new), Expr::int(c.root_action), Expr::bytes(blob)];
                match c.root_decoy_state.as_ref() {
                    Some(decoy) => {
                        let decoy_c = compile_root(decoy, &carried_tmpl);
                        cov_call_with_decoy_redeem(&root_prev_c, &decoy_c, "rootAction", args)
                    }
                    None => cov_call(&root_prev_c, "rootAction", args),
                }
            }
        };
        sigscripts[1] = root_ss;
    }
    if let Some(i) = second_root_idx {
        let blob = root_owner_blob(&unsigned, &entries, i, &c.root_signers);
        sigscripts[i] = cov_call(&root_prev_c, "rootAction", vec![root_state_arg(&root_new), Expr::int(c.root_action), Expr::bytes(blob)]);
    }

    let inputs: Vec<TransactionInput> = input_ids.iter().zip(sigscripts).map(|((id, seq), ss)| tx_input(*id, ss, *seq, c.budget)).collect();
    let tx = build_tx(inputs, outputs);

    let mut results = vec![];
    let mut units = vec![];
    for i in 0..tx.inputs.len() {
        let (r, u) = execute_input_measured(tx.clone(), entries.clone(), i);
        results.push(r);
        units.push(u);
    }
    VaultOutcome { results, units, tx, entries, vault_redeem_len: vault_prev_c.script.len(), root_redeem_len: root_prev_c.script.len() }
}

fn accept_vault(label: &str, c: &VaultCase) -> VaultOutcome {
    let o = run_vault_owner_op(c);
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("{label}: input {i} must ACCEPT the honest case: {e:?}"));
    }
    o
}
fn refuse_vault(label: &str, c: &VaultCase) -> String {
    let o = run_vault_owner_op(c);
    match &o.results[0] {
        Ok(()) => panic!("{label}: the VAULT input accepted a case that must be refused"),
        Err(e) => format!("{e:?}"),
    }
}

/* ================================================================== */
/* the root pin this vault is compiled against                         */
/* ================================================================== */

#[test]
fn v7kas_root_pin_geometry_matches_the_production_root() {
    let tmpl = RootTemplate::default();
    let pin = root_pin(COV_ROOT, &tmpl);
    for s in [
        RootState::with(1, 1, 1, 0),
        RootState::with(12, 12, 1, 6),
        RootState { frozen: 1, nonce: 1, ..RootState::with(7, 4, 2, 3) },
    ] {
        let c = compile_root(&s, &tmpl);
        let t = template_of(&c);
        assert_eq!(t.prefix.len() as i64, pin.prefix_len, "rootPrefixLen must not depend on the live state");
        assert_eq!(t.state_len as i64, pin.state_len, "rootStateLen must be CONSTANT");
        assert_eq!(t.suffix.len() as i64, pin.suffix_len, "rootSuffixLen must not depend on the live state");
        assert_eq!(t.hash, pin.hash, "rootTemplateVmHash must not depend on the live state");
        let state = &c.script[c.state_layout.start..c.state_layout.start + c.state_layout.len];
        let tail = &state[state.len() - ROOT_TAIL_LEN..];
        let mut expect = vec![0x01u8, s.frozen as u8, 0x08u8];
        expect.extend_from_slice(&num8(s.nonce));
        assert_eq!(tail, &expect[..], "the TAIL the vault rebuilds must be 0x01||frozen||0x08||nonce8");
    }
    println!(
        "[pin] rootPrefixLen {} | rootStateLen {} | rootSuffixLen {} | TAIL_LEN {} | rootTemplateVmHash {}",
        pin.prefix_len, pin.state_len, pin.suffix_len, ROOT_TAIL_LEN, hx(&pin.hash)
    );
}

/* ================================================================== */
/* honest rooted-vault owner operations                                */
/* ================================================================== */

#[test]
fn v7kas_honest_owner_control_selectors_0_to_6() {
    for sel in 0..=6i64 {
        let c = VaultCase::honest(VaultOp::Control(sel));
        let root_path = if sel == 6 { "FREEZE (emergency quorum K=1)" } else { "AUTHORIZE (full quorum)" };
        let o = accept_vault(&format!("ownerControl selector {sel} under root {root_path}"), &c);
        println!(
            "VAULT ownerControl({sel}) under root {root_path}: vault units {} | root units {} | vault redeem {} B | root redeem {} B",
            o.units[0], o.units[1], o.vault_redeem_len, o.root_redeem_len
        );
    }
}

#[test]
fn v7kas_honest_owner_recover_to_the_genesis_pinned_destination() {
    let o = accept_vault("ownerRecover under AUTHORIZE (protected+reserve -> recoveryPk)", &VaultCase::honest(VaultOp::Recover));
    println!("VAULT ownerRecover under root AUTHORIZE: vault units {} | root units {}", o.units[0], o.units[1]);
}

#[test]
fn v7kas_honest_accepts_root_nonce_carries() {
    for nonce in [255i64, 65_535, i64::from(u32::MAX)] {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_prev = RootState { nonce, ..c.root_prev.clone() };
        accept_vault(&format!("ownerControl(4) with root nonce {nonce} -> {}", nonce + 1), &c);
    }
}

#[test]
fn v7kas_honest_accepts_a_12_of_12_root() {
    let mut c = VaultCase::honest(VaultOp::Control(0));
    c.root_prev = RootState::with(12, 12, 1, 6);
    c.root_signers = (0..12).collect();
    accept_vault("ownerControl(0) under a 12-of-12 root AUTHORIZE", &c);
}

/* ================================================================== */
/* hostile matrix — root-authority rows + KAS-specific rows            */
/* ================================================================== */

fn vault_hostile_rows() -> Vec<(&'static str, VaultCase)> {
    let mut rows: Vec<(&'static str, VaultCase)> = vec![];

    rows.push(("no root input at all (delegate/hosted admin acting as owner)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.no_root = true;
        c
    }));
    rows.push(("root of a DIFFERENT organization (cross-organization confusion)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_covid_carried = COV_ROOT_B;
        c
    }));
    rows.push(("root input with a substituted root template", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.wrong_root_template = true;
        c
    }));
    rows.push(("two inputs of the root family", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.two_roots = true;
        c
    }));
    rows.push(("foreign covenant family riding an owner operation", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.alien_rider = true;
        c
    }));
    rows.push(("root running ROTATE in the same transaction", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_action = 1;
        let mut n = c.root_prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.root_new = Some(n);
        c
    }));
    rows.push(("root running UNFREEZE in the same transaction", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_prev = RootState { frozen: 1, ..c.root_prev.clone() };
        c.root_action = 3;
        c.root_new = Some(RootState { frozen: 0, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("root running OWNER-RECOVER in the same transaction (D6: it lands FROZEN)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_prev = RootState::with(4, 4, 1, 2);
        c.root_action = 4;
        c.root_sequence = RECOVERY_DELAY as u64;
        c.root_signers = vec![0, 1];
        let mut n = c.root_prev.advanced();
        n.owners[2] = ZERO32;
        n.owners[3] = ZERO32;
        n.owner_m = 2;
        n.recovery_m = 2;
        n.frozen = 1;
        c.root_new = Some(n);
        c
    }));
    rows.push(("root running SUCCESSION under a general owner operation", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_succession = Some(SUCCESSOR_SEED);
        c.root_sequence = SUCCESSION_DELAY as u64;
        let mut n = c.root_prev.advanced();
        n.owners[0] = xonly32(&kp(0x91));
        n.frozen = 1;
        c.root_new = Some(n);
        c
    }));
    rows.push(("root running SUCCESSION under the EMERGENCY pause (selector 6)", {
        let mut c = VaultCase::honest(VaultOp::Control(6));
        c.root_succession = Some(SUCCESSOR_SEED);
        c.root_sequence = SUCCESSION_DELAY as u64;
        let mut n = c.root_prev.advanced();
        n.owners[0] = xonly32(&kp(0x91));
        n.frozen = 1;
        c.root_new = Some(n);
        c
    }));
    rows.push(("frozen root authorizing a general owner operation", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_prev = RootState { frozen: 1, ..c.root_prev.clone() };
        c.root_action = 1; // ROTATE is the only full-quorum action allowed while frozen
        let mut n = c.root_prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.root_new = Some(n);
        c
    }));
    rows.push(("EMERGENCY pause (selector 6) pinned to an AUTHORIZE root successor", {
        let mut c = VaultCase::honest(VaultOp::Control(6));
        c.root_action = 0;
        c.root_signers = vec![0, 1];
        c.root_new = Some(c.root_prev.advanced()); // frozen stays 0
        c
    }));
    for sel in 0..=5i64 {
        rows.push((
            leak(format!("ownerControl selector {sel} pinned to a FREEZE root successor")),
            {
                let mut c = VaultCase::honest(VaultOp::Control(sel));
                c.root_action = 2;
                c.root_signers = vec![0];
                c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
                c
            },
        ));
    }
    rows.push(("root successor nonce not advanced", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_new = Some(c.root_prev.clone());
        c
    }));
    rows.push(("selector out of range (7)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.op = VaultOp::Control(7);
        c
    }));
    rows.push(("negative selector", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.op = VaultOp::Control(-1);
        c
    }));
    rows.push(("selector / successor mismatch (pause selector, agentRoot change)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.vault_new = VaultState { agent_root: [0x99; 32], policy_nonce: 1, ..c.vault_prev.clone() };
        c
    }));
    rows.push(("setAgentRoot without a nonce increment", {
        let mut c = VaultCase::honest(VaultOp::Control(0));
        c.vault_new = VaultState { agent_root: [0x99; 32], ..c.vault_prev.clone() };
        c
    }));
    rows.push(("successor value != declared total", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.vault_succ_value = Some(c.vault_prev.protected + c.vault_prev.reserve - 1);
        c
    }));
    rows.push(("EMERGENCY pause on an already paused vault", {
        let mut c = VaultCase::honest(VaultOp::Control(6));
        c.vault_prev = VaultState { paused: 1, ..c.vault_prev.clone() };
        c.vault_new = VaultState { paused: 1, ..c.vault_prev.clone() };
        c
    }));
    rows.push(("EMERGENCY pause silently changing the agent root", {
        let mut c = VaultCase::honest(VaultOp::Control(6));
        c.vault_new = VaultState { paused: 1, agent_root: [0x99; 32], ..c.vault_prev.clone() };
        c
    }));
    rows.push(("setApprovers with a duplicate active key", {
        let mut c = VaultCase::honest(VaultOp::Control(1));
        let k = kp(0x2a);
        let mut approvers = [ZERO32; N_APPROVERS];
        approvers[0] = xonly32(&k);
        approvers[1] = xonly32(&k);
        c.vault_new = VaultState { approvers, approval_m: 1, policy_nonce: c.vault_prev.policy_nonce + 1, ..c.vault_prev.clone() };
        c
    }));
    rows.push(("setApprovers with M above the active count", {
        let mut c = VaultCase::honest(VaultOp::Control(1));
        let approver_keys: Vec<Keypair> = vec![kp(0x2b), kp(0x2c)];
        let refs: Vec<&Keypair> = approver_keys.iter().collect();
        let approvers = approver_set(&refs);
        c.vault_new = VaultState { approvers, approval_m: 4, policy_nonce: c.vault_prev.policy_nonce + 1, ..c.vault_prev.clone() };
        c
    }));
    rows.push(("recovery redirected to an attacker key", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.recover_dest = Some(xonly32(&kp(OUTSIDER_SEED)));
        c
    }));
    rows.push(("recovery without the root's authorization", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.no_root = true;
        c
    }));
    rows.push(("recovery under a FREEZE root successor (the emergency quorum must not terminate a vault)", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.root_action = 2;
        c.root_signers = vec![0];
        c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
        c
    }));

    /* ---- byte-level pin rows ---- */
    rows.push(("[pin] successor TAIL with the frozen byte flipped 0x00 -> 0x01", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_action = 0;
        c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("[pin] successor TAIL with the frozen byte flipped 0x01 -> 0x00 (selector 6)", {
        let mut c = VaultCase::honest(VaultOp::Control(6));
        c.root_action = 2;
        c.root_new = Some(c.root_prev.advanced()); // frozen 0
        c
    }));
    rows.push(("[pin] successor TAIL nonce advanced by two", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_new = Some(RootState { nonce: c.root_prev.nonce + 2, ..c.root_prev.clone() });
        c
    }));
    rows.push(("[pin] successor TAIL nonce unchanged", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_new = Some(RootState { nonce: c.root_prev.nonce, ..c.root_prev.clone() });
        c
    }));
    rows.push(("[pin] successor HEAD with one owner key changed (rotation disguised as AUTHORIZE)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        let mut n = c.root_prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.root_new = Some(n);
        c
    }));
    rows.push(("[pin] successor HEAD with the threshold lowered", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_new = Some(RootState { owner_m: 1, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("[pin] successor HEAD with the organization id rewritten", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_new = Some(RootState { org_id: ORG_ID_B, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("[pin] root OUTPUT carrying a different template with a matching head", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_tmpl_output = Some(RootTemplate { recovery_delay: RECOVERY_DELAY + 1, ..RootTemplate::default() });
        c
    }));
    rows.push(("[pin] root INPUT revealing a redeem that does not match its own P2SH", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_decoy_state = Some(RootState { nonce: 77, ..c.root_prev.clone() });
        c
    }));

    rows
}

#[test]
fn v7kas_hostile_matrix_all_refused() {
    let rows = vault_hostile_rows();
    println!("ROOTED KAS VAULT HOSTILE MATRIX ON PRODUCTION BYTES ({} rows)", rows.len());
    for (label, case) in rows.iter() {
        let err = refuse_vault(label, case);
        println!("  REFUSED  {label}\n           -> {err}");
    }
    assert!(rows.len() >= 40, "the full root-authority + KAS-specific hostile matrix must be present (got {})", rows.len());
    assert!(rows.iter().any(|(l, _)| l.contains("selector 0 pinned to a FREEZE")), "selectors 0-5 under FREEZE must all be rejected");
    assert!(rows.iter().filter(|(l, _)| l.starts_with("[pin]")).count() >= 9, "the 9 byte-level pin rows must all run");
}

#[test]
fn v7kas_under_quorum_is_refused_by_the_root_input() {
    let mut c = VaultCase::honest(VaultOp::Control(4));
    c.root_signers = vec![0]; // 1 of the required 2
    let o = run_vault_owner_op(&c);
    assert!(o.results[1].is_err(), "the root input must refuse an under-quorum owner operation");
    println!(
        "VAULT under-quorum: root input REFUSED -> {:?} | vault input result: {:?}",
        o.results[1].as_ref().unwrap_err(),
        o.results[0]
    );
}

/* ================================================================== */
/* D6 on the vault side                                                */
/* ================================================================== */

#[test]
fn v7kas_d6_frozen_recovery_cannot_authorize_a_general_owner_operation() {
    let mut c = VaultCase::honest(VaultOp::Control(4));
    c.root_prev = RootState::with(4, 4, 1, 2);
    c.root_action = 4;
    c.root_sequence = RECOVERY_DELAY as u64;
    c.root_signers = vec![0, 1];
    c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
    let err = refuse_vault("D6: frozen OWNER-RECOVER under a general vault owner operation", &c);
    println!("D6: recovery quorum can no longer authorize a general vault owner op -> REFUSED by the vault pin: {err}");

    let mut unfrozen = c.clone();
    unfrozen.root_new = Some(c.root_prev.advanced());
    let o = run_vault_owner_op(&unfrozen);
    assert!(o.results[1].is_err(), "the root must refuse an OWNER-RECOVER landing unfrozen (D6)");
    println!("D6: the same recovery landing UNFROZEN is refused by the ROOT input -> {:?}", o.results[1].as_ref().unwrap_err());
}

#[test]
fn v7kas_d6_frozen_recovery_can_still_ride_only_the_emergency_pause() {
    let mut c = VaultCase::honest(VaultOp::Control(6));
    c.root_prev = RootState::with(4, 4, 1, 2);
    c.root_action = 4;
    c.root_sequence = RECOVERY_DELAY as u64;
    c.root_signers = vec![0, 1];
    c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
    let o = run_vault_owner_op(&c);
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("D6 consequence: input {i} was expected to accept: {e:?}"));
    }
    println!("D6 CONSEQUENCE (measured): a frozen OWNER-RECOVER with an unchanged head can ride selector 6 (EMERGENCY pause) and nothing else.");
}

/* ================================================================== */
/* delegate (agent) spend — the path the root never touches            */
/* ================================================================== */

#[derive(Clone)]
struct Agent {
    pk: [u8; 32],
    max_per_spend: i64,
    period_budget: i64,
    period_length_daa: i64,
    period_start_daa: i64,
    period_spent: i64,
    approval_threshold: i64,
    max_fee_per_tx: i64,
    recipient_root: [u8; 32],
}
fn agent_leaf(a: &Agent) -> [u8; 32] {
    sha256(&[
        &AGENT_DOMAIN,
        &a.pk,
        &num8(a.max_per_spend),
        &num8(a.period_budget),
        &num8(a.period_length_daa),
        &num8(a.period_start_daa),
        &num8(a.period_spent),
        &num8(a.approval_threshold),
        &num8(a.max_fee_per_tx),
        &a.recipient_root,
    ])
}
fn agent(k: &Keypair, cap: i64, budget: i64, threshold: i64, fee_cap: i64) -> Agent {
    Agent {
        pk: xonly32(k),
        max_per_spend: cap,
        period_budget: budget,
        period_length_daa: 864_000,
        period_start_daa: 541_000_000,
        period_spent: 0,
        approval_threshold: threshold,
        max_fee_per_tx: fee_cap,
        recipient_root: ZERO32,
    }
}

#[allow(clippy::too_many_arguments)]
struct Spend<'a> {
    prev: VaultState,
    tree_agents: Vec<Agent>,
    target: usize,
    claim: Agent,
    pay: i64,
    reserve_consumed: i64,
    periods_elapsed: i64,
    recip_depth: u32,
    signer: &'a Keypair,
    signer_type: SigHashType,
    recipient: &'a Keypair,
    recipient_out_override: Option<[u8; 32]>,
    approver_sigs: [Option<(&'a Keypair, SigHashType)>; N_APPROVERS],
    override_new_root: Option<[u8; 32]>,
    override_succ_value: Option<i64>,
    ext_in: Option<i64>,
    ext_out: Option<i64>,
    budget: u16,
    seq_override: Option<u64>,
    lock_override: Option<u64>,
    succ_protected_override: Option<i64>,
    root_rider: bool,
    post_sign_bump_recipient: Option<i64>,
    forge_agent_sig_gate_byte: bool,
}
fn dflt<'a>(prev: VaultState, agents: Vec<Agent>, target: usize, claim: Agent, signer: &'a Keypair, recipient: &'a Keypair) -> Spend<'a> {
    Spend {
        prev,
        tree_agents: agents,
        target,
        claim,
        pay: 40 * KAS,
        reserve_consumed: 5_000_000,
        periods_elapsed: 0,
        recip_depth: 0,
        signer,
        signer_type: SIG_HASH_ALL,
        recipient,
        recipient_out_override: None,
        approver_sigs: Default::default(),
        override_new_root: None,
        override_succ_value: None,
        ext_in: None,
        ext_out: None,
        budget: 400,
        seq_override: None,
        lock_override: None,
        succ_protected_override: None,
        root_rider: false,
        post_sign_bump_recipient: None,
        forge_agent_sig_gate_byte: false,
    }
}

struct SpendOutcome {
    result: Result<(), TxScriptError>,
    units: u64,
    redeem_len: usize,
    state_region_len: usize,
    sigscript_len: usize,
    tx: Transaction,
    entries: Vec<UtxoEntry>,
}

fn run_full(c: Spend) -> SpendOutcome {
    let recovery_pk = default_recovery_pk();
    let rpin = default_root_pin();

    let (rroot, rsibs, rbits) = recip_tree(c.recip_depth, &xonly32(c.recipient));
    let mut real = c.tree_agents.clone();
    real[c.target].recipient_root = rroot;
    let real_leaves: Vec<[u8; 32]> = real.iter().map(agent_leaf).collect();
    let (root, policy_sibs, policy_bits) = merkle(&real_leaves, c.target);
    let prev = VaultState { agent_root: root, ..c.prev.clone() };

    let claim = Agent { recipient_root: rroot, ..c.claim.clone() };

    let mut new_start = claim.period_start_daa;
    let mut new_spent = claim.period_spent + c.pay;
    if c.periods_elapsed >= 1 {
        new_start = claim.period_start_daa + c.periods_elapsed * claim.period_length_daa;
        new_spent = c.pay;
    }
    let mut np = claim.clone();
    np.period_start_daa = new_start;
    np.period_spent = new_spent;
    let new_root = c.override_new_root.unwrap_or_else(|| fold(agent_leaf(&np), &policy_sibs, policy_bits));

    let new_protected = c.succ_protected_override.unwrap_or(prev.protected - c.pay);
    let new_reserve = prev.reserve - c.reserve_consumed;
    let succ = VaultState { protected: new_protected, reserve: new_reserve, agent_root: new_root, ..prev.clone() };
    let active = compile_vault(&rpin, &recovery_pk, &prev);
    let succ_c = compile_vault(&rpin, &recovery_pk, &succ);
    let succ_value = c.override_succ_value.unwrap_or(new_protected + new_reserve);

    let cov_val = prev.protected + prev.reserve;
    let mut input_ids: Vec<(u8, u64)> = vec![(0x42, c.seq_override.unwrap_or(0))];
    let mut entries = vec![cov_utxo(cov_val, &active, COV_VAULT)];

    let mut ext_pk: Option<[u8; 32]> = None;
    if let Some(ev) = c.ext_in {
        let ext_kp = kp(0x71);
        let epk = xonly32(&ext_kp);
        entries.push(UtxoEntry::new(ev as u64, p2pk_spk(&epk), 0, false, None));
        input_ids.push((0x71, 0));
        ext_pk = Some(epk);
    }

    let root_prev_c = compile_root(&RootState::with(3, 2, 1, 2), &RootTemplate::default());
    let root_succ_state = RootState::with(3, 2, 1, 2).advanced();
    let root_next_c = compile_root(&root_succ_state, &RootTemplate::default());
    if c.root_rider {
        entries.push(cov_utxo(ROOT_KAS, &root_prev_c, COV_ROOT));
        input_ids.push((0x99, 0));
    }

    let recip_out = c.recipient_out_override.unwrap_or(xonly32(c.recipient));
    let mut outputs = vec![p2pk_out(&recip_out, c.pay), cov_out(succ_value, &succ_c, 0, COV_VAULT)];
    if let Some(ov) = c.ext_out {
        let change_pk = ext_pk.unwrap_or(recip_out);
        outputs.push(p2pk_out(&change_pk, ov));
    }
    if c.root_rider {
        let root_input_idx = (input_ids.len() - 1) as u16;
        outputs.push(cov_out(ROOT_KAS - ROOT_FEE_PAID, &root_next_c, root_input_idx, COV_ROOT));
    }

    let lock = c.lock_override.unwrap_or(if c.periods_elapsed >= 1 { new_start as u64 } else { 0 });
    let unsigned = Transaction::new(
        1,
        input_ids.iter().map(|(id, seq)| tx_input(*id, vec![], *seq, c.budget)).collect(),
        outputs.clone(),
        lock,
        SubnetworkId::default(),
        0,
        vec![],
    );

    let mut agent_sig = sign_type(&unsigned, &entries, 0, c.signer, c.signer_type);
    if c.forge_agent_sig_gate_byte {
        // Sign with a genuine SIG_HASH_ALL (0x01) signature, then corrupt only
        // the trailing gate byte in the SUPPLIED call argument. requireAgentAuthorization
        // must read the actual trailing byte of the blob it is given, not merely
        // trust that a real signature was computed.
        assert_eq!(agent_sig.len(), 65, "sanity: agent_sig must be exactly 65 bytes before forging");
        assert_eq!(agent_sig[64], 0x01, "sanity: forging test must start from a real SIG_HASH_ALL signature");
        agent_sig[64] = 0x02;
    }
    let mut blob = Vec::with_capacity(650);
    for slot in c.approver_sigs.iter() {
        match slot {
            Some((k, ty)) => blob.extend_from_slice(&sign_type(&unsigned, &entries, 0, k, *ty)),
            None => blob.extend_from_slice(&placeholder_slot()),
        }
    }
    let args = vec![
        vault_state_arg(&succ),
        Expr::int(c.pay),
        Expr::bytes(claim.pk.to_vec()),
        Expr::int(claim.max_per_spend),
        Expr::int(claim.period_budget),
        Expr::int(claim.period_length_daa),
        Expr::int(claim.period_start_daa),
        Expr::int(claim.period_spent),
        Expr::int(claim.approval_threshold),
        Expr::int(claim.max_fee_per_tx),
        Expr::bytes(rroot.to_vec()),
        Expr::bytes(policy_sibs.clone()),
        Expr::int(policy_bits as i64),
        Expr::int(c.periods_elapsed),
        Expr::bytes(xonly32(c.recipient).to_vec()),
        Expr::bytes(rsibs),
        Expr::int(rbits as i64),
        Expr::bytes(agent_sig),
        Expr::bytes(blob),
    ];
    let ctrl_ss = cov_call(&active, "agentSpend", args);
    let sigscript_len = ctrl_ss.len();

    let mut sigscripts: Vec<Vec<u8>> = input_ids.iter().map(|_| vec![]).collect();
    sigscripts[0] = ctrl_ss;
    if let Some(i) = input_ids.iter().position(|(id, _)| *id == 0x71) {
        let ext_sig = sign_type(&unsigned, &entries, i, &kp(0x71), SIG_HASH_ALL);
        sigscripts[i] = p2pk_sigscript(ext_sig);
    }
    if c.root_rider {
        let i = input_ids.iter().position(|(id, _)| *id == 0x99).unwrap();
        let blob = root_owner_blob(&unsigned, &entries, i, &[0, 1]);
        sigscripts[i] = cov_call(&root_prev_c, "rootAction", vec![root_state_arg(&root_succ_state), Expr::int(0), Expr::bytes(blob)]);
    }

    let inputs: Vec<TransactionInput> =
        input_ids.iter().zip(sigscripts).map(|((id, seq), ss)| tx_input(*id, ss, *seq, c.budget)).collect();
    let mut tx = build_tx(inputs, outputs);
    tx.lock_time = lock;
    if let Some(delta) = c.post_sign_bump_recipient {
        tx.outputs[0].value = (tx.outputs[0].value as i64 + delta) as u64;
    }

    let (result, units) = execute_input_measured(tx.clone(), entries.clone(), 0);
    SpendOutcome { result, units, redeem_len: active.script.len(), state_region_len: active.state_layout.len, sigscript_len, tx, entries }
}

fn run(c: Spend) -> (Result<(), TxScriptError>, u64) {
    let o = run_full(c);
    (o.result, o.units)
}

/* ================================================================== */
/* honest delegate spend + positive matrix                             */
/* ================================================================== */

#[test]
fn v7kas_honest_delegate_spend() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let o = run_full(dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient));
    o.result.as_ref().unwrap_or_else(|e| panic!("rooted v0.7-kas delegate spend must accept: {e:?}"));
    println!("V7KAS delegate spend: units {} | redeem {} B | state {} B | sigscript {} B", o.units, o.redeem_len, o.state_region_len, o.sigscript_len);
}

#[test]
fn v7kas_honest_delegate_spend_with_period_rollover() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let mut pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    pa.period_spent = 480 * KAS;
    let r = run(Spend { pay: 40 * KAS, periods_elapsed: 1, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert!(r.is_ok(), "period rollover resets spent: {r:?}");
}

#[test]
fn v7kas_honest_delegate_spend_at_production_proof_depths() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let n = 1usize << 12;
    let mut agents = vec![pa.clone()];
    for i in 1..n {
        let mut g = agent(&kp(((i % 200) + 2) as u8), 1 * KAS, 1 * KAS, 1, 1);
        g.recipient_root = sha256(&[b"f", &(i as u64).to_le_bytes()]);
        agents.push(g);
    }
    let o = run_full(Spend { recip_depth: 16, budget: 800, ..dflt(base_vault_state(ZERO32), agents, 0, pa, &a, &recipient) });
    o.result.as_ref().unwrap_or_else(|e| panic!("deep proofs (agent 12 / recipient 16) must accept: {e:?}"));
    println!("V7KAS delegate spend at depths agent 12 / recipient 16: units {} | sigscript {} B", o.units, o.sigscript_len);
}

#[test]
fn v7kas_valid_matrix_agent_and_recipient_depths() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    for adepth in [0u32, 1, 4, 8, 12] {
        let pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
        let n = 1usize << adepth;
        let mut agents = vec![pa.clone()];
        for i in 1..n {
            let mut g = agent(&kp(((i % 200) + 2) as u8), 1 * KAS, 1 * KAS, 1, 1);
            g.recipient_root = sha256(&[b"f", &(i as u64).to_le_bytes()]);
            agents.push(g);
        }
        let r = run(dflt(base_vault_state(ZERO32), agents, 0, pa, &a, &recipient)).0;
        assert!(r.is_ok(), "agent depth {adepth} valid: {r:?}");
    }
    for rdepth in [0u32, 1, 4, 8, 12, 16] {
        let pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
        let r = run(Spend { recip_depth: rdepth, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
        assert!(r.is_ok(), "recipient depth {rdepth} valid: {r:?}");
    }
}

#[test]
fn v7kas_threshold_and_approvals_positive() {
    let a = kp(0x30);
    let (a1, a2, a3) = (kp(0x20), kp(0x21), kp(0x22));
    let recipient = kp(0x40);
    let slots = approver_set(&[&a1, &a2, &a3]);
    let mut st = base_vault_state(ZERO32);
    st.approvers = slots;
    st.approval_m = 2;
    let pa = agent(&a, 200 * KAS, 500 * KAS, 50 * KAS, 1 * KAS);
    assert!(run(Spend { pay: 50 * KAS, ..dflt(st.clone(), vec![pa.clone()], 0, pa.clone(), &a, &recipient) }).0.is_ok(), "at threshold: delegate-only");
    let ap = approvals_by_key(&slots, &[(&a1, SIG_HASH_ALL), (&a2, SIG_HASH_ALL)]);
    assert!(run(Spend { pay: 150 * KAS, approver_sigs: ap, ..dflt(st, vec![pa.clone()], 0, pa, &a, &recipient) }).0.is_ok(), "2-of-3 approvals above threshold");
}

#[test]
fn v7kas_worst_case_stack_and_execute() {
    let a = kp(0x1e);
    let recipient = kp(0x28);
    let approvers: Vec<Keypair> = (0..10).map(|i| kp(0x3c + i)).collect();
    let arefs: Vec<&Keypair> = approvers.iter().collect();
    let slots = approver_set(&arefs);
    let pa = agent(&a, 200 * KAS, 500 * KAS, 50 * KAS, 1 * KAS);
    let n = 1usize << 12;
    let mut agents = vec![pa.clone()];
    for i in 1..n {
        agents.push(agent(&kp(((i % 200) + 2) as u8), 1 * KAS, 1 * KAS, 1, 1));
    }
    for (i, g) in agents.iter_mut().enumerate().skip(1) {
        g.recipient_root = sha256(&[b"filler", &(i as u64).to_le_bytes()]);
    }
    let mut st = base_vault_state(ZERO32);
    st.approvers = slots;
    st.approval_m = 10;
    let signers: Vec<(&Keypair, SigHashType)> = approvers.iter().map(|k| (k, SIG_HASH_ALL)).collect();
    let ap = approvals_by_key(&slots, &signers);
    let o = run_full(Spend { pay: 150 * KAS, recip_depth: 16, approver_sigs: ap, budget: 800, ..dflt(st, agents, 0, pa, &a, &recipient) });
    o.result.as_ref().unwrap_or_else(|e| panic!("WORST CASE depth12+recip16+10of10 must execute under MAX_STACK_SIZE 244: {e:?}"));
    println!("V7KAS WORST depth12+recip16+10of10: compute_units={}", o.units);
}

/* ================================================================== */
/* delegate hostile matrix — named categories                          */
/* ================================================================== */

#[test]
fn v7kas_delegate_over_cap_rejected() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let r = run(Spend { pay: 101 * KAS, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "spend above per-spend cap must be refused");
}

#[test]
fn v7kas_delegate_over_budget_rejected() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let mut pa = agent(&a, 500 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    pa.period_spent = 480 * KAS;
    let r = run(Spend { pay: 30 * KAS, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "spend exceeding the period budget must be refused");
}

#[test]
fn v7kas_delegate_premature_rollover_rejected() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let mut pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    pa.period_spent = 480 * KAS;
    let new_start = pa.period_start_daa + pa.period_length_daa;
    let r = run(Spend {
        pay: 40 * KAS,
        periods_elapsed: 1,
        lock_override: Some((new_start - 1) as u64),
        ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient)
    })
    .0;
    assert_rejected(r, "rollover before the new period's DAA boundary must be refused");
}

#[test]
fn v7kas_delegate_recipient_substitution_rejected() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let other = kp(0x41);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let r = run(Spend { recipient_out_override: Some(xonly32(&other)), ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "payment to a non-member recipient must be refused");
}

#[test]
fn v7kas_delegate_forged_successor_root_rejected() {
    let a = kp(0x30);
    let b = kp(0x31);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let pb = agent(&b, 1000 * KAS, 10_000 * KAS, 100_000 * KAS, 5 * KAS);
    let leaves = vec![agent_leaf(&{ let mut g = pa.clone(); g.recipient_root = recip_tree(0, &xonly32(&recipient)).0; g }), agent_leaf(&pb)];
    let orig = merkle(&leaves, 0).0;
    let r = run(Spend { pay: 80 * KAS, override_new_root: Some(orig), ..dflt(base_vault_state(ZERO32), vec![pa.clone(), pb], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "forged (unchanged) successor root must be refused");
}

#[test]
fn v7kas_delegate_approval_shortfall_and_nonapprover_signature_rejected() {
    let a = kp(0x30);
    let (a1, a2, a3) = (kp(0x20), kp(0x21), kp(0x22));
    let recipient = kp(0x40);
    let slots = approver_set(&[&a1, &a2, &a3]);
    let mut st = base_vault_state(ZERO32);
    st.approvers = slots;
    st.approval_m = 2;
    let pa = agent(&a, 200 * KAS, 500 * KAS, 50 * KAS, 1 * KAS);

    let ap1 = approvals_by_key(&slots, &[(&a1, SIG_HASH_ALL)]);
    assert_rejected(run(Spend { pay: 150 * KAS, approver_sigs: ap1, ..dflt(st.clone(), vec![pa.clone()], 0, pa.clone(), &a, &recipient) }).0, "1-of-2 approvals (shortfall) must be refused");

    let ap_wrong = {
        let mut ap: [Option<(&Keypair, SigHashType)>; N_APPROVERS] = Default::default();
        ap[0] = Some((&a, SIG_HASH_ALL)); // a's OWN key does not hold slot 0 (a1 does)
        ap[1] = Some((&a2, SIG_HASH_ALL));
        ap
    };
    assert_rejected(run(Spend { pay: 150 * KAS, approver_sigs: ap_wrong, ..dflt(st, vec![pa.clone()], 0, pa, &a, &recipient) }).0, "a non-approver signature placed in an approver slot must not count");
}

#[test]
fn v7kas_delegate_malformed_genesis_duplicate_approver_rejected() {
    let a = kp(0x30);
    let k = kp(0x23);
    let a3 = kp(0x22);
    let recipient = kp(0x40);
    let pa = agent(&a, 200 * KAS, 500 * KAS, 50 * KAS, 1 * KAS);
    let mut approvers = [ZERO32; N_APPROVERS];
    approvers[0] = xonly32(&k);
    approvers[1] = xonly32(&k);
    approvers[2] = xonly32(&a3);
    let mut st = base_vault_state(ZERO32);
    st.approvers = approvers;
    st.approval_m = 2;
    let mut ap: [Option<(&Keypair, SigHashType)>; N_APPROVERS] = Default::default();
    ap[0] = Some((&k, SIG_HASH_ALL));
    ap[1] = Some((&k, SIG_HASH_ALL));
    let r = run(Spend { pay: 150 * KAS, approver_sigs: ap, ..dflt(st, vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "duplicate predecessor approver key must be refused (A2 malformed-genesis defense)");
}

#[test]
fn v7kas_delegate_nonall_approver_sighash_rejected() {
    let a = kp(0x30);
    let (a1, a2) = (kp(0x20), kp(0x21));
    let recipient = kp(0x40);
    let slots = approver_set(&[&a1, &a2]);
    let mut st = base_vault_state(ZERO32);
    st.approvers = slots;
    st.approval_m = 2;
    let pa = agent(&a, 200 * KAS, 500 * KAS, 50 * KAS, 1 * KAS);
    for (name, ty) in [
        ("NONE", SIG_HASH_NONE),
        ("SINGLE", SIG_HASH_SINGLE),
        ("ALL|ACP", SIG_HASH_ALL | SIG_HASH_ANY_ONE_CAN_PAY),
        ("NONE|ACP", SIG_HASH_NONE | SIG_HASH_ANY_ONE_CAN_PAY),
        ("SINGLE|ACP", SIG_HASH_SINGLE | SIG_HASH_ANY_ONE_CAN_PAY),
    ] {
        let ap = approvals_by_key(&slots, &[(&a1, ty), (&a2, SIG_HASH_ALL)]);
        let r = run(Spend { pay: 150 * KAS, approver_sigs: ap, ..dflt(st.clone(), vec![pa.clone()], 0, pa.clone(), &a, &recipient) }).0;
        assert_rejected(r, &format!("approver sighash {name} must be rejected by the A7 gate"));
    }
}

#[test]
fn v7kas_delegate_post_sign_output_mutation_rejected() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let r = run(Spend { post_sign_bump_recipient: Some(1), ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "mutating an output after the agent signature is captured must be refused (SIGHASH_ALL binding)");
}

#[test]
fn v7kas_delegate_fee_domain_and_value_leakage_matrix() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let other = kp(0x41);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let base = base_vault_state(ZERO32);
    let mk = |f: &dyn Fn(&mut Spend)| {
        let mut sp = dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa.clone(), &a, &recipient);
        f(&mut sp);
        run(sp).0
    };
    assert_rejected(mk(&|s| { s.reserve_consumed = 0; s.override_succ_value = Some(base.protected - s.pay + base.reserve - 5_000_000); }), "principal used as fee");
    assert_rejected(mk(&|s| { s.reserve_consumed = 1 * KAS; s.ext_out = Some(1 * KAS); }), "reserve redirected to an external output");
    assert_rejected(mk(&|s| { s.reserve_consumed = 1 * KAS; s.ext_in = Some(50_000_000); s.ext_out = Some(1 * KAS + 50_000_000); }), "external input masks reserve theft");
    assert_rejected(mk(&|s| { s.reserve_consumed = 0; s.ext_out = Some(3 * KAS); }), "external output exceeds external input");
    assert_rejected(mk(&|s| { s.reserve_consumed = 2 * KAS; s.ext_in = Some(3 * KAS); s.ext_out = Some(1 * KAS); }), "reserve consumption above the agent's fee cap");
    assert_rejected(mk(&|s| { s.pay = 0; }), "zero payment");
    assert_rejected(mk(&|s| { s.pay = 101 * KAS; }), "payment above cap");
    assert_rejected(mk(&|s| { s.reserve_consumed = -1 * KAS; }), "reserve consumption forged negative (value leakage)");
    assert_rejected(mk(&|s| { s.reserve_consumed = -s.pay; }), "principal-to-reserve swap (value leakage)");
    assert_rejected(mk(&|s| { s.recipient_out_override = Some(xonly32(&other)); }), "recipient substitution");
    assert!(mk(&|s| { s.reserve_consumed = 1 * KAS; s.ext_in = Some(2 * KAS); s.ext_out = Some(1 * KAS); }).is_ok(), "consuming exactly the fee cap with external change must accept");
}

/* --- D2 (v0.6 adversarial review, F1): zero-length period ------------ */

#[test]
fn v7kas_d2_zero_length_period_rejected() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let mut pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    pa.period_length_daa = 0;
    pa.period_spent = pa.period_budget;
    let r = run(Spend {
        pay: 40 * KAS,
        periods_elapsed: 1,
        lock_override: Some(pa.period_start_daa as u64),
        ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient)
    })
    .0;
    assert_rejected(r, "D2: zero-length period must be refused");
}

/* --- v0.7-kas candidate hardening E6(b): agentSpend now REFUSES any
 * covenant rider on the delegate path (requireOnlyPlainInputsOnDelegatePath).
 * UNLIKE frozen v0.4.1's agentSpend (which has no foreign-covenant-family
 * check at all — it predates multiple covenant families coexisting in one
 * PolicyVault transaction) this profile closes the surface unconditionally,
 * for parity with the payment profile's own family-isolation shape
 * (requireNoForeignCovenantInputs) even though a root rider was already
 * VERIFIED SAFE under the old (inherited) behavior — this is defense in
 * depth, not a bug fix. */

#[test]
fn v7kas_delegate_spend_refuses_a_root_covenant_rider() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let r = run(Spend { root_rider: true, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert_rejected(r, "E6(b): agentSpend must refuse a root-covenant rider on the delegate path");
}

#[test]
fn v7kas_delegate_spend_positive_control_no_rider_still_accepts() {
    // Positive control paired with the refusal above: the SAME honest spend,
    // with root_rider left false, must still accept — proving the new
    // requireOnlyPlainInputsOnDelegatePath() closure does not over-refuse the
    // ordinary (no-rider) delegate path.
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let r = run(Spend { root_rider: false, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert!(r.is_ok(), "positive control: an ordinary delegate spend with no rider must still accept: {r:?}");
}

/* --- v0.7-kas candidate hardening E6(a): agentSpend now requires the
 * agent's OWN signature to be SIG_HASH_ALL (requireAgentAuthorization),
 * exact parity with the ALREADY-PROVEN gate in
 * contracts/PolicyVault.v0.6.sil. UNLIKE frozen v0.4.1's agentSpend and the
 * frozen v0.7-payment profile's tokenAgentSpend (both carry an UNGATED `sig`
 * parameter — documented, verified-safe there because the outputs are bound
 * structurally regardless of what the signature covers), this profile closes
 * the surface unconditionally. */

#[test]
fn v7kas_delegate_spend_refuses_non_all_agent_sighash() {
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let anyone_can_pay_single =
        SigHashType::from_u8(SIG_HASH_SINGLE.to_u8() | SIG_HASH_ANY_ONE_CAN_PAY.to_u8()).expect("allowed sighash type");
    for (label, ty) in [("SIGHASH_NONE", SIG_HASH_NONE), ("SIGHASH_SINGLE|ANYONECANPAY", anyone_can_pay_single)] {
        let r = run(Spend {
            signer_type: ty,
            ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa.clone(), &a, &recipient)
        })
        .0;
        assert_rejected(r, &format!("E6(a): agentSpend must refuse a non-SIG_HASH_ALL agent signature ({label})"));
    }
}

#[test]
fn v7kas_delegate_spend_refuses_a_forged_gate_byte() {
    // The A7-style gate checks the LAST byte of the 65-byte agentSig blob
    // (SIG_HASH_ALL == 0x01). Sign with a real SIG_HASH_ALL signature (so the
    // 64-byte signature body itself is genuinely valid) and then forge only
    // the trailing byte in the call argument — the covenant must still
    // refuse, proving the gate reads the ACTUAL trailing byte of the
    // supplied blob and is not satisfied merely because the underlying
    // signature was computed over the ALL sighash.
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let o = run_full(Spend {
        forge_agent_sig_gate_byte: true,
        ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient)
    });
    assert_rejected(o.result, "E6(a): agentSpend must refuse a forged (non-0x01) trailing gate byte even over an ALL-computed signature");
}

#[test]
fn v7kas_delegate_spend_positive_control_all_sighash_still_accepts() {
    // Positive control paired with the two refusals above: an ordinary
    // SIG_HASH_ALL agent signature, unmutated, must still accept.
    let a = kp(0x30);
    let recipient = kp(0x40);
    let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
    let r = run(Spend { signer_type: SIG_HASH_ALL, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }).0;
    assert!(r.is_ok(), "positive control: an ordinary SIG_HASH_ALL agent signature must still accept: {r:?}");
}

/* ================================================================== */
/* measurement, standardness, MAX_STACK_SIZE headroom                  */
/* ================================================================== */

fn mass_of(tx: &Transaction, entries: &[UtxoEntry]) -> (u64, u64, u64, u64) {
    let mc = MassCalculator::new(1, 10, STORAGE_MASS_PARAMETER);
    let m = mc.calc_non_contextual_masses(tx);
    let populated = PopulatedTransaction::new(tx, entries.to_vec());
    let storage = mc.calc_contextual_masses(&populated).map(|c| c.storage_mass).unwrap_or(0);
    let size = transaction_estimated_serialized_size(tx) as u64;
    (size, m.compute_mass, m.transient_mass, storage)
}

fn priced_units_and_sigops(tx: &Transaction, entries: &[UtxoEntry]) -> Vec<(u64, u16, u64)> {
    (0..tx.inputs.len())
        .map(|i| {
            let (r, priced) = execute_input_measured_priced(tx.clone(), entries.to_vec(), i, 1000);
            r.unwrap_or_else(|e| panic!("priced input {i} must accept: {e:?}"));
            let budget = ComputeBudget::checked_covering_script_units(ScriptUnits(priced)).expect("budget").0;
            let sigops = post_toccata_p2sh_sig_scanner(&tx.inputs[i].signature_script, &entries[i].script_public_key);
            (priced, budget, sigops)
        })
        .collect()
}

const MAX_STACK_PROBE: usize = 244;

fn measure_peak_stack<F>(label: &str, mut run_with_pad: F) -> usize
where
    F: FnMut(usize) -> Result<(), TxScriptError>,
{
    run_with_pad(0).unwrap_or_else(|e| panic!("{label}: unpadded run must accept: {e:?}"));
    for pad in 1..=MAX_STACK_PROBE {
        if let Err(TxScriptError::StackSizeExceeded(size, max)) = run_with_pad(pad) {
            assert_eq!(max, 244, "{label}: unexpected MAX_STACK_SIZE");
            let peak = 245 - pad;
            println!("  {label}: peak combined stack {peak} (StackSizeExceeded at pad {pad}, reported {size}/{max}) -> headroom {}", 244 - peak);
            return peak;
        }
    }
    panic!("{label}: never hit MAX_STACK_SIZE within {MAX_STACK_PROBE} padding items");
}

fn check_standardness(label: &str, tx: &Transaction, entries: &[UtxoEntry], compute: u64, transient: u64) {
    for i in 0..tx.inputs.len() {
        let ops = post_toccata_p2sh_sig_scanner(&tx.inputs[i].signature_script, &entries[i].script_public_key);
        assert!(ops <= MAX_STANDARD_P2SH_SIG_OPS, "{label}: input {i} static sig-ops {ops} must be <= 15 (standard)");
    }
    for (i, o) in tx.outputs.iter().enumerate() {
        assert_ne!(ScriptClass::from_script(&o.script_public_key), ScriptClass::NonStandard, "{label}: output {i} must be a standard class");
    }
    assert!(compute <= 500_000, "{label}: compute mass {compute} exceeds the post-Toccata block-fit limit");
    assert!(transient <= 1_000_000, "{label}: transient mass {transient} exceeds the post-Toccata block-fit limit");
    if transient > 100_000 || compute > 100_000 {
        println!("    note: {label} exceeds the PRE-Toccata 100,000 standard cap — post-Toccata only");
    }
}

#[test]
fn v7kas_measurement_standardness_and_stack() {
    println!("\n===== v0.7-kas PRODUCTION MEASUREMENT (real TxScriptEngine, rusty-kaspa 2.0.1) =====");

    println!("\n[1] ROOTED VAULT OWNER OPERATIONS (root + vault, one transaction)");
    for (label, case) in [
        ("ownerControl(0 setAgentRoot) under AUTHORIZE", VaultCase::honest(VaultOp::Control(0))),
        ("ownerControl(1 setApprovers) under AUTHORIZE", VaultCase::honest(VaultOp::Control(1))),
        ("ownerControl(2 topUp) under AUTHORIZE", VaultCase::honest(VaultOp::Control(2))),
        ("ownerControl(3 topUpReserve) under AUTHORIZE", VaultCase::honest(VaultOp::Control(3))),
        ("ownerControl(4 pause) under AUTHORIZE", VaultCase::honest(VaultOp::Control(4))),
        ("ownerControl(5 unpause) under AUTHORIZE", VaultCase::honest(VaultOp::Control(5))),
        ("ownerControl(6 EMERGENCY pause) under FREEZE", VaultCase::honest(VaultOp::Control(6))),
        ("ownerRecover under AUTHORIZE", VaultCase::honest(VaultOp::Recover)),
    ] {
        let o = accept_vault(label, &case);
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let p = priced_units_and_sigops(&o.tx, &o.entries);
        println!("  {label}: tx {size} B | compute_mass {compute} | transient_mass {transient} | storage_mass {storage}");
        for (i, (pu, budget, sigops)) in p.iter().enumerate() {
            println!(
                "    input {i}: sigscript {} B | units {} | priced {pu} -> budget {budget} | static sig-ops {sigops}",
                o.tx.inputs[i].signature_script.len(),
                o.units[i]
            );
        }
        println!("    vault redeem {} B | root redeem {} B", o.vault_redeem_len, o.root_redeem_len);
        check_standardness(label, &o.tx, &o.entries, compute, transient);
    }

    println!("\n[2] DELEGATE SPEND (agentSpend, the path the root never touches)");
    {
        let a = kp(0x30);
        let recipient = kp(0x40);
        let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
        let o = run_full(dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient));
        o.result.as_ref().unwrap_or_else(|e| panic!("delegate spend must accept: {e:?}"));
        println!(
            "  redeem {} B | state {} B | sigscript {} B | units {}",
            o.redeem_len, o.state_region_len, o.sigscript_len, o.units
        );
        let real_sigops = {
            let recovery_pk = default_recovery_pk();
            let rpin = default_root_pin();
            let a2 = kp(0x30);
            let recipient2 = kp(0x40);
            let pa2 = agent(&a2, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
            let (rroot, rsibs, rbits) = recip_tree(0, &xonly32(&recipient2));
            let claim = Agent { recipient_root: rroot, ..pa2.clone() };
            let leaves = vec![agent_leaf(&claim)];
            let (root, psibs, pbits) = merkle(&leaves, 0);
            let prev = VaultState { agent_root: root, ..base_vault_state(ZERO32) };
            let pay = 40 * KAS;
            let mut np = claim.clone();
            np.period_spent += pay;
            let new_root = fold(agent_leaf(&np), &psibs, pbits);
            let succ = VaultState { protected: prev.protected - pay, reserve: prev.reserve - 5_000_000, agent_root: new_root, ..prev.clone() };
            let active = compile_vault(&rpin, &recovery_pk, &prev);
            let succ_c = compile_vault(&rpin, &recovery_pk, &succ);
            let outputs = vec![p2pk_out(&xonly32(&recipient2), pay), cov_out(succ.protected + succ.reserve, &succ_c, 0, COV_VAULT)];
            let tx = build_tx(vec![tx_input(0x42, vec![], 0, 400)], outputs);
            let utxo = cov_utxo(prev.protected + prev.reserve, &active, COV_VAULT);
            let agent_sig = sign(&tx, &[utxo.clone()], 0, &a2);
            let mut blob = Vec::new();
            for _ in 0..10 {
                blob.extend_from_slice(&placeholder_slot());
            }
            let args = vec![
                vault_state_arg(&succ),
                Expr::int(pay),
                Expr::bytes(claim.pk.to_vec()),
                Expr::int(claim.max_per_spend),
                Expr::int(claim.period_budget),
                Expr::int(claim.period_length_daa),
                Expr::int(claim.period_start_daa),
                Expr::int(claim.period_spent),
                Expr::int(claim.approval_threshold),
                Expr::int(claim.max_fee_per_tx),
                Expr::bytes(rroot.to_vec()),
                Expr::bytes(psibs),
                Expr::int(pbits as i64),
                Expr::int(0),
                Expr::bytes(xonly32(&recipient2).to_vec()),
                Expr::bytes(rsibs),
                Expr::int(rbits as i64),
                Expr::bytes(agent_sig),
                Expr::bytes(blob),
            ];
            let sig_script = cov_call(&active, "agentSpend", args);
            let spk = pay_to_script_hash_script(&active.script);
            post_toccata_p2sh_sig_scanner(&sig_script, &spk)
        };
        println!("  STANDARDNESS v0.7-kas: post_toccata_p2sh_sig_scanner = {real_sigops} (limit {MAX_STANDARD_P2SH_SIG_OPS}); v0.4.1 base was 13");
        assert_eq!(real_sigops, 11, "v0.7-kas production redeem must scan to exactly 11 static P2SH sig-ops (13 minus the two removed owner checkSigs)");
        assert!(real_sigops <= MAX_STANDARD_P2SH_SIG_OPS, "must be STANDARD");
    }

    println!("\n[3] DELEGATE SPEND AT PRODUCTION PROOF DEPTHS AND WITH ROLLOVER");
    {
        let a = kp(0x30);
        let recipient = kp(0x40);
        for (label, mut c) in [
            ("depths agent 12 / recipient 16", {
                let pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
                let n = 1usize << 12;
                let mut agents = vec![pa.clone()];
                for i in 1..n {
                    let mut g = agent(&kp(((i % 200) + 2) as u8), 1 * KAS, 1 * KAS, 1, 1);
                    g.recipient_root = sha256(&[b"f", &(i as u64).to_le_bytes()]);
                    agents.push(g);
                }
                Spend { recip_depth: 16, ..dflt(base_vault_state(ZERO32), agents, 0, pa, &a, &recipient) }
            }),
            ("rollover (2 periods)", {
                let mut pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
                pa.period_spent = pa.period_budget;
                Spend { periods_elapsed: 2, ..dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient) }
            }),
        ] {
            c.budget = 800;
            let o = run_full(c);
            o.result.as_ref().unwrap_or_else(|e| panic!("{label}: must accept: {e:?}"));
            println!("  {label}: sigscript {} B | units {}", o.sigscript_len, o.units);
        }
    }

    println!("\n[4] MAX_STACK_SIZE (244) HEADROOM");
    {
        let a = kp(0x30);
        let recipient = kp(0x40);
        measure_peak_stack("v0.7-kas delegate spend (agentSpend, basic shape)", |pad| {
            let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
            let mut c = dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient);
            c.recip_depth = 0;
            let padded_prev = c.prev.clone();
            let _ = padded_prev;
            run_stack_padded(c, pad)
        });
    }
    println!("========================================================================================\n");
}

/// Same as `run()` but pushes `pad` extra 1-byte data items onto the
/// signature script BEFORE the agentSpend call, to probe MAX_STACK_SIZE
/// headroom exactly like the payment-profile suite does.
fn run_stack_padded(c: Spend, pad: usize) -> Result<(), TxScriptError> {
    let recovery_pk = default_recovery_pk();
    let rpin = default_root_pin();

    let (rroot, rsibs, rbits) = recip_tree(c.recip_depth, &xonly32(c.recipient));
    let mut real = c.tree_agents.clone();
    real[c.target].recipient_root = rroot;
    let real_leaves: Vec<[u8; 32]> = real.iter().map(agent_leaf).collect();
    let (root, policy_sibs, policy_bits) = merkle(&real_leaves, c.target);
    let prev = VaultState { agent_root: root, ..c.prev.clone() };
    let claim = Agent { recipient_root: rroot, ..c.claim.clone() };
    let mut np = claim.clone();
    np.period_spent = claim.period_spent + c.pay;
    let new_root = fold(agent_leaf(&np), &policy_sibs, policy_bits);
    let new_protected = prev.protected - c.pay;
    let new_reserve = prev.reserve - c.reserve_consumed;
    let succ = VaultState { protected: new_protected, reserve: new_reserve, agent_root: new_root, ..prev.clone() };
    let active = compile_vault(&rpin, &recovery_pk, &prev);
    let succ_c = compile_vault(&rpin, &recovery_pk, &succ);

    let outputs = vec![p2pk_out(&xonly32(c.recipient), c.pay), cov_out(new_protected + new_reserve, &succ_c, 0, COV_VAULT)];
    let tx = build_tx(vec![tx_input(0x42, vec![], 0, c.budget)], outputs.clone());
    let utxo = cov_utxo(prev.protected + prev.reserve, &active, COV_VAULT);
    let entries = vec![utxo.clone()];

    let agent_sig = sign(&tx, &entries, 0, c.signer);
    let mut blob = Vec::with_capacity(650);
    for slot in c.approver_sigs.iter() {
        match slot {
            Some((k, ty)) => blob.extend_from_slice(&sign_type(&tx, &entries, 0, k, *ty)),
            None => blob.extend_from_slice(&placeholder_slot()),
        }
    }
    let args = vec![
        vault_state_arg(&succ),
        Expr::int(c.pay),
        Expr::bytes(claim.pk.to_vec()),
        Expr::int(claim.max_per_spend),
        Expr::int(claim.period_budget),
        Expr::int(claim.period_length_daa),
        Expr::int(claim.period_start_daa),
        Expr::int(claim.period_spent),
        Expr::int(claim.approval_threshold),
        Expr::int(claim.max_fee_per_tx),
        Expr::bytes(rroot.to_vec()),
        Expr::bytes(policy_sibs),
        Expr::int(policy_bits as i64),
        Expr::int(c.periods_elapsed),
        Expr::bytes(xonly32(c.recipient).to_vec()),
        Expr::bytes(rsibs),
        Expr::int(rbits as i64),
        Expr::bytes(agent_sig),
        Expr::bytes(blob),
    ];
    let mut ctrl_ss = cov_call(&active, "agentSpend", args);
    if pad > 0 {
        let mut p = ScriptBuilder::new();
        for _ in 0..pad {
            p.add_data(&[0x01u8]).unwrap();
        }
        let mut padded = p.drain();
        padded.extend_from_slice(&ctrl_ss);
        ctrl_ss = padded;
    }
    let mut t = tx;
    t.inputs[0].signature_script = ctrl_ss;
    execute_input_measured(t, entries, 0).0
}

#[test]
fn v7kas_measure_priced_worst_case_delegate_spend() {
    // PRICED measurement (Gram(1000) = 100,000 units/sig-op) of the worst-case
    // delegate spend shape (agent depth 12, recipient depth 16, 10-of-10
    // approvals) — the anchor compute-budget-v7-kas.js sizes its per-approval
    // sig-op allowance from.
    let a = kp(0x1e);
    let recipient = kp(0x28);
    let approvers: Vec<Keypair> = (0..10).map(|i| kp(0x3c + i)).collect();
    let arefs: Vec<&Keypair> = approvers.iter().collect();
    let slots = approver_set(&arefs);
    let pa = agent(&a, 200 * KAS, 500 * KAS, 50 * KAS, 1 * KAS);
    let n = 1usize << 12;
    let mut agents = vec![pa.clone()];
    for i in 1..n {
        agents.push(agent(&kp(((i % 200) + 2) as u8), 1 * KAS, 1 * KAS, 1, 1));
    }
    for (i, g) in agents.iter_mut().enumerate().skip(1) {
        g.recipient_root = sha256(&[b"filler", &(i as u64).to_le_bytes()]);
    }
    let mut st = base_vault_state(ZERO32);
    st.approvers = slots;
    st.approval_m = 10;
    let signers: Vec<(&Keypair, SigHashType)> = approvers.iter().map(|k| (k, SIG_HASH_ALL)).collect();
    let ap = approvals_by_key(&slots, &signers);

    // Rebuild the exact same transaction run_full builds, but execute it
    // under PRICED metering so the number reflects what a live node charges.
    let recovery_pk = default_recovery_pk();
    let rpin = default_root_pin();
    let (rroot, rsibs, rbits) = recip_tree(16, &xonly32(&recipient));
    let mut real = agents.clone();
    real[0].recipient_root = rroot;
    let real_leaves: Vec<[u8; 32]> = real.iter().map(agent_leaf).collect();
    let (root, policy_sibs, policy_bits) = merkle(&real_leaves, 0);
    let prev = VaultState { agent_root: root, ..st };
    let claim = Agent { recipient_root: rroot, ..pa.clone() };
    let pay = 150 * KAS;
    let mut np = claim.clone();
    np.period_spent = claim.period_spent + pay;
    let new_root = fold(agent_leaf(&np), &policy_sibs, policy_bits);
    let succ = VaultState { protected: prev.protected - pay, reserve: prev.reserve - 5_000_000, agent_root: new_root, ..prev.clone() };
    let active = compile_vault(&rpin, &recovery_pk, &prev);
    let succ_c = compile_vault(&rpin, &recovery_pk, &succ);
    let outputs = vec![p2pk_out(&xonly32(&recipient), pay), cov_out(succ.protected + succ.reserve, &succ_c, 0, COV_VAULT)];
    let tx = build_tx(vec![tx_input(0x42, vec![], 0, 800)], outputs);
    let utxo = cov_utxo(prev.protected + prev.reserve, &active, COV_VAULT);
    let entries = vec![utxo.clone()];
    let agent_sig = sign(&tx, &entries, 0, &a);
    let mut blob = Vec::with_capacity(650);
    for slot in ap.iter() {
        match slot {
            Some((k, ty)) => blob.extend_from_slice(&sign_type(&tx, &entries, 0, k, *ty)),
            None => blob.extend_from_slice(&placeholder_slot()),
        }
    }
    let args = vec![
        vault_state_arg(&succ),
        Expr::int(pay),
        Expr::bytes(claim.pk.to_vec()),
        Expr::int(claim.max_per_spend),
        Expr::int(claim.period_budget),
        Expr::int(claim.period_length_daa),
        Expr::int(claim.period_start_daa),
        Expr::int(claim.period_spent),
        Expr::int(claim.approval_threshold),
        Expr::int(claim.max_fee_per_tx),
        Expr::bytes(rroot.to_vec()),
        Expr::bytes(policy_sibs),
        Expr::int(policy_bits as i64),
        Expr::int(0),
        Expr::bytes(xonly32(&recipient).to_vec()),
        Expr::bytes(rsibs),
        Expr::int(rbits as i64),
        Expr::bytes(agent_sig),
        Expr::bytes(blob),
    ];
    let mut ss = cov_call(&active, "agentSpend", args);
    let sigscript_len = ss.len();
    let mut t = tx;
    t.inputs[0].signature_script = std::mem::take(&mut ss);
    let (r, priced) = execute_input_measured_priced(t, vec![utxo], 0, 1000);
    r.unwrap_or_else(|e| panic!("priced worst-case delegate spend must accept: {e:?}"));
    let budget = ComputeBudget::checked_covering_script_units(ScriptUnits(priced)).expect("budget").0;
    println!("PRICED worst-case delegate spend (depth12/16 + 10-of-10 approvals): sigscript {sigscript_len} B | priced units {priced} -> required budget {budget}");
}

/* ================================================================== */
/* I4 ECONOMIC VIABILITY — mass/fee at MINIMAL required budgets        */
/* ================================================================== */

/// Kaspa relay-floor fee arithmetic (mining/src/mempool/check_transaction_standard.rs,
/// consensus/core/src/mass/mod.rs): fee_mass = max(compute_mass,
/// ceil(transient_mass * 500_000 / 1_000_000)); relay fee = fee_mass * 100 sompi.
fn relay_floor_sompi(compute_mass: u64, transient_mass: u64) -> u64 {
    let storage_scaled = (transient_mass * 500_000 + 999_999) / 1_000_000;
    let fee_mass = compute_mass.max(storage_scaled);
    fee_mass * 100
}

#[test]
fn v7kas_economic_viability_minimal_budgets() {
    println!("\n===== v0.7-kas ECONOMIC VIABILITY (real engine, MINIMAL required compute budgets) =====");
    // Budgets below come from core/model/compute-budget-v7-kas.js's
    // selectComputeBudgetV7Kas / (reused) selectRootComputeBudgetV7, computed
    // once via `node -e` against the SAME measured constants this file
    // records, then hardcoded here so this test has no Node dependency.
    const VAULT_OWNER_CONTROL_BUDGET: u16 = 39; // ownerControl 0..6 (root pins: prefix 1, suffix 11077)
    const VAULT_OWNER_RECOVER_BUDGET: u16 = 30;
    const ROOT_AUTHORIZE_N3_BUDGET: u16 = 42;
    const AGENT_SPEND_BASE_BUDGET: u16 = 25;
    const AGENT_SPEND_DEPTH_BUDGET: u16 = 30;

    println!("\n[owner operations, root + vault, MINIMAL budgets]");
    for (label, sel, vault_budget) in [
        ("ownerControl(0 setAgentRoot)", 0i64, VAULT_OWNER_CONTROL_BUDGET),
        ("ownerControl(6 EMERGENCY pause)", 6i64, VAULT_OWNER_CONTROL_BUDGET),
    ] {
        let mut c = VaultCase::honest(VaultOp::Control(sel));
        c.budget = vault_budget.max(ROOT_AUTHORIZE_N3_BUDGET);
        let o = accept_vault(label, &c);
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let fee = relay_floor_sompi(compute, transient);
        println!(
            "  {label}: budget(vault={vault_budget},root={ROOT_AUTHORIZE_N3_BUDGET}) tx {size} B | compute_mass {compute} | transient_mass {transient} | storage_mass {storage} | relay-floor fee {fee} sompi ({:.8} KAS)",
            fee as f64 / KAS as f64
        );
    }
    {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.budget = VAULT_OWNER_RECOVER_BUDGET.max(ROOT_AUTHORIZE_N3_BUDGET);
        let o = accept_vault("ownerRecover", &c);
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let fee = relay_floor_sompi(compute, transient);
        println!(
            "  ownerRecover: budget(vault={VAULT_OWNER_RECOVER_BUDGET},root={ROOT_AUTHORIZE_N3_BUDGET}) tx {size} B | compute_mass {compute} | transient_mass {transient} | storage_mass {storage} | relay-floor fee {fee} sompi ({:.8} KAS)",
            fee as f64 / KAS as f64
        );
    }

    println!("\n[delegate spend, MINIMAL budgets]");
    {
        let a = kp(0x30);
        let recipient = kp(0x40);
        let pa = agent(&a, 100 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
        let mut sp = dflt(base_vault_state(ZERO32), vec![pa.clone()], 0, pa, &a, &recipient);
        sp.budget = AGENT_SPEND_BASE_BUDGET;
        let o = run_full(sp);
        o.result.as_ref().unwrap_or_else(|e| panic!("delegate spend at minimal budget must accept: {e:?}"));
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let fee = relay_floor_sompi(compute, transient);
        println!(
            "  delegate spend (basic, budget={AGENT_SPEND_BASE_BUDGET}): tx {size} B | compute_mass {compute} | transient_mass {transient} | storage_mass {storage} | relay-floor fee {fee} sompi ({:.8} KAS)",
            fee as f64 / KAS as f64
        );
    }
    {
        let a = kp(0x30);
        let recipient = kp(0x40);
        let pa = agent(&a, 200 * KAS, 500 * KAS, 100_000 * KAS, 1 * KAS);
        let n = 1usize << 12;
        let mut agents = vec![pa.clone()];
        for i in 1..n {
            let mut g = agent(&kp(((i % 200) + 2) as u8), 1 * KAS, 1 * KAS, 1, 1);
            g.recipient_root = sha256(&[b"f", &(i as u64).to_le_bytes()]);
            agents.push(g);
        }
        let mut sp = Spend { recip_depth: 16, budget: AGENT_SPEND_DEPTH_BUDGET, ..dflt(base_vault_state(ZERO32), agents, 0, pa, &a, &recipient) };
        sp.budget = AGENT_SPEND_DEPTH_BUDGET;
        let o = run_full(sp);
        o.result.as_ref().unwrap_or_else(|e| panic!("delegate spend depth12/16 at minimal budget must accept: {e:?}"));
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let fee = relay_floor_sompi(compute, transient);
        println!(
            "  delegate spend (depth12/16, budget={AGENT_SPEND_DEPTH_BUDGET}): tx {size} B | compute_mass {compute} | transient_mass {transient} | storage_mass {storage} | relay-floor fee {fee} sompi ({:.8} KAS)",
            fee as f64 / KAS as f64
        );
    }
    println!("=====================================================================================\n");
}
