//! VM layer — PRODUCTION CANDIDATE `contracts/PolicyVault.v0.7-payment.sil`
//! (contract `PolicyVaultRootedToken`, generated by `tools/gen_v7_payment.js`
//! as an exact-match delta over the FROZEN `contracts/PolicyVault.v0.5.sil`)
//! driven through the real TxScriptEngine (covenants enabled, real Schnorr),
//! together with the PRODUCTION root `contracts/PolicyVault.v0.7-root.sil`.
//!
//! Gate I1 of docs/postlaunch/v0.7-organizational-root-design.md section 11.1:
//! the honest rooted-vault lifecycle (ownerControl selectors 0-4 under the
//! right root path, ownerRecover to the genesis-pinned recoveryPk, the
//! delegate spend that never touches the root, period rollover, and the
//! production Merkle depths agent 12 / recipient 16), EVERY vault-side hostile
//! row of sections 7.8 and 10.8 ported onto the PRODUCTION bytes, the D2 row,
//! the authority-layering (under-quorum) row, the coordinator's D6 rows, the
//! production-byte encoder integration, and measurement + standardness +
//! MAX_STACK_SIZE headroom.
//!
//! `contracts/PolicyVault.v0.5.sil` is opened READ-ONLY as the delegate-cost
//! baseline and as the D2 inherited-behaviour record; it is never modified.

use std::sync::OnceLock;

use secp256k1::Keypair;
use sha2::{Digest, Sha256};
use silverscript_lang::ast::Expr;
use silverscript_lang::compiler::{compile_contract, struct_object, CompileOptions, CompiledContract, CovenantDeclCallOptions};

use kaspa_consensus_core::constants::STORAGE_MASS_PARAMETER;
use kaspa_consensus_core::hashing::sighash::{calc_schnorr_signature_hash, SigHashReusedValuesUnsync};
use kaspa_consensus_core::hashing::sighash_type::{SigHashType, SIG_HASH_ALL};
use kaspa_consensus_core::mass::units::{ComputeBudget, ScriptUnits};
use kaspa_consensus_core::mass::{transaction_estimated_serialized_size, MassCalculator};
use kaspa_consensus_core::subnets::SubnetworkId;
use kaspa_consensus_core::tx::{
    ComputeCommit, CovenantBinding, MutableTransaction, PopulatedTransaction, ScriptPublicKey, Transaction, TransactionId,
    TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
};
use kaspa_consensus_core::Hash;
use kaspa_txscript::opcodes::codes::OpCheckSig;
use kaspa_txscript::script_class::ScriptClass;
use kaspa_txscript::{pay_to_script_hash_script, post_toccata_p2sh_sig_scanner, script_builder::ScriptBuilder, EngineFlags};
use kaspa_txscript_errors::TxScriptError;
use policyvault_vm_tests::{execute_input_measured, execute_input_measured_priced};

/* ================================================================== */
/* constants                                                           */
/* ================================================================== */

const N_SLOTS: usize = 12;
const SIG_BLOB_LEN: usize = N_SLOTS * 65; // 780
const ROOT_TAIL_LEN: usize = 11;

const COV_ROOT: Hash = Hash::from_bytes(*b"ROOTROOTROOTROOTROOTROOTROOTROOT");
const COV_ROOT_B: Hash = Hash::from_bytes(*b"ROOTBROOTBROOTBROOTBROOTBROOTBRO");
const COV_VAULT: Hash = Hash::from_bytes(*b"VAULTVAULTVAULTVAULTVAULTVAULTVA");
const COV_TOKEN: Hash = Hash::from_bytes(*b"TOKENTOKENTOKENTOKENTOKENTOKENTO");
const COV_ALIEN: Hash = Hash::from_bytes(*b"ALIENALIENALIENALIENALIENALIENAL");

const ZERO32: [u8; 32] = [0u8; 32];
const ORG_ID: [u8; 32] = [0xa7u8; 32];
const ORG_ID_B: [u8; 32] = [0xb7u8; 32];
const VAULT_ID: [u8; 32] = [0x44u8; 32];
const DESCRIPTOR_HASH: [u8; 32] = [0xd5u8; 32];
const TOKEN_AGENT_DOMAIN: [u8; 4] = [0x50, 0x56, 0x35, 0x01];
const RECIP_DOMAIN: [u8; 4] = [0x50, 0x56, 0x33, 0x01];
const IDENTIFIER_PUBKEY: u8 = 0x00;
const IDENTIFIER_COVENANT_ID: u8 = 0x02;

const KAS: i64 = 100_000_000;
const ROOT_KAS: i64 = 3 * KAS;
const ROOT_MAX_FEE: i64 = 200_000;
const ROOT_FEE_PAID: i64 = 50_000;
const RECOVERY_DELAY: i64 = 1_000;
const SUCCESSION_DELAY: i64 = 2_000;

const RESERVE: i64 = 5 * KAS;
const TOKEN_CARRY: i64 = 2 * KAS;
const FUEL: i64 = KAS;
const RECIPIENT_CARRY: i64 = KAS / 5;
const FEE: i64 = 100_000;
const RESERVE_CONSUMED: i64 = 50_000;
const PREV_TOKEN_AMOUNT: i64 = 1_000;
const SPEND: i64 = 300;

/// The FROZEN v0.5 delegate-spend redeem, measured in sections 7.5 and 10.4.
const FROZEN_V5_DELEGATE_REDEEM_B: usize = 9_273;
/// Section 9.4's acceptance criterion for the rooted delegate spend.
const DELEGATE_REDEEM_TARGET_B: usize = 10_600;
/// rusty-kaspa mining/src/mempool/check_transaction_standard.rs.
const MAX_STANDARD_P2SH_SIG_OPS: u64 = 15;

const OWNER_SEEDS: [u8; N_SLOTS] = [0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c];
const SUCCESSOR_SEED: u8 = 0x7f;
const OUTSIDER_SEED: u8 = 0x6f;

/* ================================================================== */
/* helpers                                                             */
/* ================================================================== */

fn kp(seed: u8) -> Keypair {
    let secp = secp256k1::Secp256k1::new();
    let sk = secp256k1::SecretKey::from_slice(&[seed; 32]).expect("seed key");
    Keypair::from_secret_key(&secp, &sk)
}
fn xonly32(k: &Keypair) -> [u8; 32] {
    k.x_only_public_key().0.serialize()
}
fn hx(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}
fn sha256(parts: &[&[u8]]) -> [u8; 32] {
    let mut h = Sha256::new();
    for p in parts {
        h.update(p);
    }
    h.finalize().into()
}
fn num8(v: i64) -> [u8; 8] {
    (v as u64).to_le_bytes()
}
fn leak(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}
fn load(rel: &str) -> String {
    let path = format!("{}/{rel}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"))
}
/// THE PRODUCTION ROOT.
fn src_root() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../contracts/PolicyVault.v0.7-root.sil")))
}
/// THE PRODUCTION ROOTED PAYMENT PROFILE.
fn src_vault_raw() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../contracts/PolicyVault.v0.7-payment.sil")))
}
/// The FROZEN v0.5 controller — READ-ONLY comparison baseline.
fn src_v5_raw() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../contracts/PolicyVault.v0.5.sil")))
}
fn src_kcc20() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../../silverscript/silverscript-lang/tests/examples/kcc20.sil")))
}

#[derive(Clone)]
struct Template {
    prefix: Vec<u8>,
    state_len: usize,
    suffix: Vec<u8>,
    hash: [u8; 32],
}
fn template_of(c: &CompiledContract<'_>) -> Template {
    let l = c.state_layout;
    let prefix = c.script[..l.start].to_vec();
    let suffix = c.script[l.start + l.len..].to_vec();
    let h = blake2b_simd::Params::new().hash_length(32).to_state().update(&prefix).update(&suffix).finalize();
    let mut hash = [0u8; 32];
    hash.copy_from_slice(h.as_bytes());
    Template { prefix, state_len: l.len, suffix, hash }
}

fn push_redeem(script: &[u8]) -> Vec<u8> {
    ScriptBuilder::with_flags(EngineFlags { covenants_enabled: true, ..Default::default() }).add_data(script).unwrap().drain()
}
fn cov_call_opt(c: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>, is_leader: bool) -> Vec<u8> {
    let mut s = c.build_sig_script_for_covenant_decl(f, args, CovenantDeclCallOptions { is_leader }).unwrap_or_else(|e| panic!("call {f}: {e:?}"));
    s.extend_from_slice(&push_redeem(&c.script));
    s
}
fn cov_call(c: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>) -> Vec<u8> {
    cov_call_opt(c, f, args, false)
}
/// Build the call for `c`'s ABI but append a DIFFERENT contract's redeem — the
/// "revealed redeem does not match this input's own P2SH" substitution the
/// byte-level pin must refuse before it reads a single tail byte.
fn cov_call_with_decoy_redeem(c: &CompiledContract<'_>, decoy: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>) -> Vec<u8> {
    let mut s = c.build_sig_script_for_covenant_decl(f, args, CovenantDeclCallOptions { is_leader: false }).unwrap_or_else(|e| panic!("call {f}: {e:?}"));
    s.extend_from_slice(&push_redeem(&decoy.script));
    s
}
fn tx_input(id: u8, sigscript: Vec<u8>, sequence: u64, budget: u16) -> TransactionInput {
    TransactionInput::new_with_mass(
        TransactionOutpoint { transaction_id: TransactionId::from_bytes([id; 32]), index: 0 },
        sigscript,
        sequence,
        ComputeCommit::ComputeBudget(ComputeBudget(budget)),
    )
}
fn cov_out(value: i64, c: &CompiledContract<'_>, auth: u16, covid: Hash) -> TransactionOutput {
    TransactionOutput {
        value: value as u64,
        script_public_key: pay_to_script_hash_script(&c.script),
        covenant: Some(CovenantBinding { authorizing_input: auth, covenant_id: covid }),
    }
}
fn cov_utxo(value: i64, c: &CompiledContract<'_>, covid: Hash) -> UtxoEntry {
    UtxoEntry::new(value as u64, pay_to_script_hash_script(&c.script), 0, false, Some(covid))
}
fn p2pk_spk(pk: &[u8; 32]) -> ScriptPublicKey {
    ScriptPublicKey::new(0, ScriptBuilder::new().add_data(pk).unwrap().add_op(OpCheckSig).unwrap().drain().into())
}
fn p2pk_out(pk: &[u8; 32], value: i64) -> TransactionOutput {
    TransactionOutput { value: value as u64, script_public_key: p2pk_spk(pk), covenant: None }
}
fn p2pk_sigscript(sig: Vec<u8>) -> Vec<u8> {
    ScriptBuilder::new().add_data(&sig).unwrap().drain()
}
fn build_tx(inputs: Vec<TransactionInput>, outputs: Vec<TransactionOutput>) -> Transaction {
    Transaction::new(1, inputs, outputs, 0, SubnetworkId::default(), 0, vec![])
}
fn sign_type(tx: &Transaction, entries: &[UtxoEntry], idx: usize, k: &Keypair, ht: SigHashType) -> Vec<u8> {
    let m = MutableTransaction::with_entries(tx.clone(), entries.to_vec());
    let reused = SigHashReusedValuesUnsync::new();
    let h = calc_schnorr_signature_hash(&m.as_verifiable(), idx, ht, &reused);
    let msg = secp256k1::Message::from_digest_slice(h.as_bytes().as_slice()).unwrap();
    let mut out = k.sign_schnorr(msg).as_ref().to_vec();
    out.push(ht.to_u8());
    out
}
fn sign(tx: &Transaction, entries: &[UtxoEntry], idx: usize, k: &Keypair) -> Vec<u8> {
    sign_type(tx, entries, idx, k, SIG_HASH_ALL)
}
fn placeholder_slot() -> Vec<u8> {
    let mut v = vec![0u8; 64];
    v.push(0x01);
    v
}

/* ---------------- Merkle (identical construction to the v0.5 suite) ---- */

fn merkle(leaves: &[[u8; 32]], target: usize) -> ([u8; 32], Vec<u8>, u64) {
    let mut level = leaves.to_vec();
    while level.len().count_ones() != 1 {
        level.push(*level.last().unwrap());
    }
    let (mut idx, mut sibs, mut bits, mut lvl) = (target, Vec::new(), 0u64, 0);
    while level.len() > 1 {
        let s = if idx % 2 == 0 { idx + 1 } else { idx - 1 };
        sibs.extend_from_slice(&level[s]);
        if idx % 2 == 1 {
            bits |= 1 << lvl;
        }
        let mut next = Vec::with_capacity(level.len() / 2);
        for pair in level.chunks(2) {
            next.push(sha256(&[&pair[0], &pair[1]]));
        }
        idx /= 2;
        level = next;
        lvl += 1;
    }
    (level[0], sibs, bits)
}
fn recip_tree(depth: u32, target: &[u8; 32]) -> ([u8; 32], Vec<u8>, u64) {
    if depth == 0 {
        return (sha256(&[&RECIP_DOMAIN, target]), vec![], 0);
    }
    let n = 1usize << depth;
    let mut leaves: Vec<[u8; 32]> = (0..n).map(|i| sha256(&[&RECIP_DOMAIN, &(i as u64 + 900).to_le_bytes()])).collect();
    leaves[1] = sha256(&[&RECIP_DOMAIN, target]);
    merkle(&leaves, 1)
}

/* ================================================================== */
/* the PRODUCTION root covenant (the vault's owner authority)          */
/* ================================================================== */

#[derive(Clone, PartialEq, Debug)]
struct RootState {
    org_id: [u8; 32],
    owners: [[u8; 32]; N_SLOTS],
    owner_m: i64,
    emergency_k: i64,
    recovery_m: i64,
    frozen: i64,
    nonce: i64,
}
impl RootState {
    fn with(n: usize, m: i64, k: i64, r: i64) -> RootState {
        let mut owners = [ZERO32; N_SLOTS];
        for (i, o) in owners.iter_mut().enumerate().take(n) {
            *o = xonly32(&kp(OWNER_SEEDS[i]));
        }
        RootState { org_id: ORG_ID, owners, owner_m: m, emergency_k: k, recovery_m: r, frozen: 0, nonce: 0 }
    }
    fn advanced(&self) -> RootState {
        RootState { nonce: self.nonce + 1, ..self.clone() }
    }
}

#[derive(Clone)]
struct RootTemplate {
    recovery_delay: i64,
    successor_pk: [u8; 32],
    succession_delay: i64,
    max_fee: i64,
}
impl Default for RootTemplate {
    fn default() -> Self {
        RootTemplate {
            recovery_delay: RECOVERY_DELAY,
            successor_pk: xonly32(&kp(SUCCESSOR_SEED)),
            succession_delay: SUCCESSION_DELAY,
            max_fee: ROOT_MAX_FEE,
        }
    }
}

fn compile_root(s: &RootState, t: &RootTemplate) -> CompiledContract<'static> {
    let mut args: Vec<Expr<'static>> = vec![Expr::bytes(s.org_id.to_vec())];
    for o in s.owners.iter() {
        args.push(Expr::bytes(o.to_vec()));
    }
    for v in [s.owner_m, s.emergency_k, s.recovery_m] {
        args.push(Expr::int(v));
    }
    args.push(Expr::byte(s.frozen as u8));
    args.push(Expr::bytes(num8(s.nonce).to_vec()));
    args.push(Expr::int(t.recovery_delay));
    args.push(Expr::bytes(t.successor_pk.to_vec()));
    args.push(Expr::int(t.succession_delay));
    args.push(Expr::int(t.max_fee));
    compile_contract(src_root(), &args, CompileOptions::default()).unwrap_or_else(|e| panic!("compile production root: {e:?}"))
}

const ROOT_SLOT_NAMES: [&str; N_SLOTS] =
    ["owner1", "owner2", "owner3", "owner4", "owner5", "owner6", "owner7", "owner8", "owner9", "owner10", "owner11", "owner12"];

fn root_state_arg(s: &RootState) -> Expr<'static> {
    let mut f: Vec<(&'static str, Expr<'static>)> = vec![("boundOrgId", Expr::bytes(s.org_id.to_vec()))];
    for (i, n) in ROOT_SLOT_NAMES.iter().enumerate() {
        f.push((n, Expr::bytes(s.owners[i].to_vec())));
    }
    f.push(("ownerM", Expr::int(s.owner_m)));
    f.push(("emergencyK", Expr::int(s.emergency_k)));
    f.push(("recoveryM", Expr::int(s.recovery_m)));
    f.push(("frozen", Expr::byte(s.frozen as u8)));
    f.push(("rootNonce", Expr::bytes(num8(s.nonce).to_vec())));
    struct_object(f)
}

fn root_owner_blob(tx: &Transaction, entries: &[UtxoEntry], idx: usize, signers: &[usize]) -> Vec<u8> {
    let mut slots: Vec<Vec<u8>> = (0..N_SLOTS).map(|_| placeholder_slot()).collect();
    for i in signers.iter() {
        slots[*i] = sign(tx, entries, idx, &kp(OWNER_SEEDS[*i]));
    }
    let blob: Vec<u8> = slots.into_iter().flatten().collect();
    assert_eq!(blob.len(), SIG_BLOB_LEN);
    blob
}

/* ================================================================== */
/* the PRODUCTION rooted payment profile                               */
/* ================================================================== */

#[derive(Clone, PartialEq, Debug)]
struct VaultState {
    reserve: i64,
    paused: i64,
    agent_root: [u8; 32],
    policy_nonce: i64,
}

#[derive(Clone, Copy, PartialEq, Debug)]
enum Profile {
    /// contracts/PolicyVault.v0.7-payment.sil (the production candidate)
    RootedV7,
    /// contracts/PolicyVault.v0.5.sil (FROZEN — read-only comparison baseline)
    FrozenV5,
}

fn profile_src(p: Profile) -> &'static str {
    match p {
        Profile::RootedV7 => src_vault_raw(),
        Profile::FrozenV5 => src_v5_raw(),
    }
}

/// Exact-live-state templating — the same anchors the v0.5 production suite
/// uses, and the delta generator never touches them.
fn vault_templated(src: &str, s: &VaultState) -> String {
    let mut src = src.to_string();
    let mut r = |from: String, to: String| {
        assert!(src.contains(&from), "anchor missing: {from}");
        src = src.replacen(&from, &to, 1);
    };
    r("int feeReserve = initFeeReserve;".into(), format!("int feeReserve = {};", s.reserve));
    r("int paused = 0;".into(), format!("int paused = {};", s.paused));
    r("byte[32] agentRoot = initAgentRoot;".into(), format!("byte[32] agentRoot = 0x{};", hx(&s.agent_root)));
    r("int policyNonce = 0;".into(), format!("int policyNonce = {};", s.policy_nonce));
    src
}

#[derive(Clone)]
struct TokenPin {
    covid: Hash,
    hash: [u8; 32],
    prefix_len: i64,
    state_len: i64,
    suffix_len: i64,
}
#[derive(Clone)]
struct RootPin {
    covid: Hash,
    hash: [u8; 32],
    prefix_len: i64,
    state_len: i64,
    suffix_len: i64,
}

fn compile_vault(p: Profile, tok: &TokenPin, root: &RootPin, recovery_pk: &[u8; 32], s: &VaultState) -> CompiledContract<'static> {
    compile_vault_from(profile_src(p), p, tok, root, recovery_pk, s)
}
fn compile_vault_from(
    raw: &str,
    p: Profile,
    tok: &TokenPin,
    root: &RootPin,
    recovery_pk: &[u8; 32],
    s: &VaultState,
) -> CompiledContract<'static> {
    let src: &'static str = leak(vault_templated(raw, s));
    let mut args: Vec<Expr<'static>> = vec![];
    if p == Profile::FrozenV5 {
        args.push(Expr::bytes(recovery_pk.to_vec())); // the frozen v0.5 `pubkey owner`
    }
    args.push(Expr::bytes(VAULT_ID.to_vec()));
    args.push(Expr::bytes(DESCRIPTOR_HASH.to_vec()));
    args.push(Expr::bytes(tok.covid.as_bytes().to_vec()));
    args.push(Expr::bytes(tok.hash.to_vec()));
    args.push(Expr::int(tok.prefix_len));
    args.push(Expr::int(tok.state_len));
    args.push(Expr::int(tok.suffix_len));
    if p != Profile::FrozenV5 {
        args.push(Expr::bytes(root.covid.as_bytes().to_vec()));
        args.push(Expr::bytes(root.hash.to_vec()));
        args.push(Expr::int(root.prefix_len));
        args.push(Expr::int(root.state_len));
        args.push(Expr::int(root.suffix_len));
        args.push(Expr::bytes(recovery_pk.to_vec()));
    }
    args.push(Expr::bytes(s.agent_root.to_vec()));
    args.push(Expr::int(s.reserve));
    compile_contract(src, &args, CompileOptions::default()).unwrap_or_else(|e| panic!("compile {p:?}: {e:?}"))
}

fn vault_state_arg(s: &VaultState) -> Expr<'static> {
    struct_object(vec![
        ("boundVaultId", Expr::bytes(VAULT_ID.to_vec())),
        ("feeReserve", Expr::int(s.reserve)),
        ("paused", Expr::int(s.paused)),
        ("agentRoot", Expr::bytes(s.agent_root.to_vec())),
        ("policyNonce", Expr::int(s.policy_nonce)),
    ])
}

fn compile_kcc20(owner: [u8; 32], ty: u8, amount: i64, minter: bool, max_cov: i64) -> CompiledContract<'static> {
    compile_contract(
        src_kcc20(),
        &[Expr::bytes(owner.to_vec()), Expr::int(amount), Expr::byte(ty), Expr::bool(minter), Expr::int(max_cov), Expr::int(max_cov)],
        CompileOptions::default(),
    )
    .expect("compile kcc20")
}
fn kcc20_state<'i>(owner: [u8; 32], ty: u8, amount: i64, minter: bool) -> Expr<'i> {
    struct_object(vec![
        ("ownerIdentifier", Expr::bytes(owner.to_vec())),
        ("identifierType", Expr::byte(ty)),
        ("amount", Expr::int(amount)),
        ("isMinter", Expr::bool(minter)),
    ])
}

fn token_pin(covid: Hash) -> TokenPin {
    let sample = compile_kcc20(COV_VAULT.as_bytes().try_into().unwrap(), IDENTIFIER_COVENANT_ID, PREV_TOKEN_AMOUNT, false, 2);
    let t = template_of(&sample);
    TokenPin { covid, hash: t.hash, prefix_len: t.prefix.len() as i64, state_len: t.state_len as i64, suffix_len: t.suffix.len() as i64 }
}
fn root_pin(covid: Hash, tmpl: &RootTemplate) -> RootPin {
    let sample = compile_root(&RootState::with(1, 1, 1, 0), tmpl);
    let t = template_of(&sample);
    RootPin { covid, hash: t.hash, prefix_len: t.prefix.len() as i64, state_len: t.state_len as i64, suffix_len: t.suffix.len() as i64 }
}

/* ---------------- vault owner operations (root + vault) ---------------- */

#[derive(Clone, Copy, PartialEq, Debug)]
enum VaultOp {
    /// the merged entrypoint, selectors 0..4 (4 = EMERGENCY pause under FREEZE)
    Control(i64),
    Recover,
}

#[derive(Clone)]
struct VaultCase {
    op: VaultOp,
    root_prev: RootState,
    root_new: Option<RootState>,
    root_action: i64,
    root_signers: Vec<usize>,
    root_tmpl: RootTemplate,
    /// the root instance actually spent is compiled with THIS template
    root_tmpl_carried: Option<RootTemplate>,
    /// the root's continuation OUTPUT is compiled with THIS template
    root_tmpl_output: Option<RootTemplate>,
    /// the root input's sigscript carries THIS state's redeem instead of its own
    root_decoy_state: Option<RootState>,
    root_covid_carried: Hash,
    root_covid_pinned: Hash,
    root_succession: Option<u8>,
    root_sequence: u64,
    vault_prev: VaultState,
    vault_new: VaultState,
    no_root: bool,
    two_roots: bool,
    alien_rider: bool,
    tokens_ride: bool,
    vault_succ_value: Option<i64>,
    recover_dest: Option<[u8; 32]>,
    recover_amount_delta: i64,
    recover_with_tokens: bool,
    /// the vault pins a DIFFERENT root template hash than the root carries
    wrong_root_template: bool,
    budget: u16,
}
impl VaultCase {
    fn honest(op: VaultOp) -> VaultCase {
        let root_prev = RootState::with(3, 2, 1, 2);
        // selector 4 is the EMERGENCY pause: it must ride a root FREEZE
        let (action, signers) = match op {
            VaultOp::Control(4) => (2i64, vec![0usize]),
            _ => (0i64, vec![0usize, 1usize]),
        };
        let vault_prev = VaultState { reserve: RESERVE, paused: 0, agent_root: ZERO32, policy_nonce: 0 };
        let vault_new = match op {
            VaultOp::Control(0) => VaultState { agent_root: [0x99; 32], policy_nonce: 1, ..vault_prev.clone() },
            VaultOp::Control(1) => VaultState { reserve: RESERVE + KAS, ..vault_prev.clone() },
            VaultOp::Control(2) => VaultState { paused: 1, ..vault_prev.clone() },
            VaultOp::Control(3) => VaultState { paused: 0, ..vault_prev.clone() },
            VaultOp::Control(4) => VaultState { paused: 1, ..vault_prev.clone() },
            _ => vault_prev.clone(),
        };
        let vault_prev = if op == VaultOp::Control(3) { VaultState { paused: 1, ..vault_prev } } else { vault_prev };
        VaultCase {
            op,
            root_prev,
            root_new: None,
            root_action: action,
            root_signers: signers,
            root_tmpl: RootTemplate::default(),
            root_tmpl_carried: None,
            root_tmpl_output: None,
            root_decoy_state: None,
            root_covid_carried: COV_ROOT,
            root_covid_pinned: COV_ROOT,
            root_succession: None,
            root_sequence: 0,
            vault_prev,
            vault_new,
            no_root: false,
            two_roots: false,
            alien_rider: false,
            tokens_ride: false,
            vault_succ_value: None,
            recover_dest: None,
            recover_amount_delta: 0,
            recover_with_tokens: true,
            wrong_root_template: false,
            budget: 400,
        }
    }
}

struct VaultOutcome {
    results: Vec<Result<(), TxScriptError>>,
    units: Vec<u64>,
    tx: Transaction,
    entries: Vec<UtxoEntry>,
    vault_redeem_len: usize,
    root_redeem_len: usize,
}

fn run_vault_owner_op(c: &VaultCase) -> VaultOutcome {
    let recovery_pk = xonly32(&kp(0x51));
    let tok = token_pin(COV_TOKEN);
    let rpin_tmpl =
        if c.wrong_root_template { RootTemplate { recovery_delay: RECOVERY_DELAY + 7, ..RootTemplate::default() } } else { c.root_tmpl.clone() };
    let rpin = root_pin(c.root_covid_pinned, &rpin_tmpl);

    let vault_prev_c = compile_vault(Profile::RootedV7, &tok, &rpin, &recovery_pk, &c.vault_prev);
    let vault_next_c = compile_vault(Profile::RootedV7, &tok, &rpin, &recovery_pk, &c.vault_new);

    let carried_tmpl = c.root_tmpl_carried.clone().unwrap_or_else(|| c.root_tmpl.clone());
    let output_tmpl = c.root_tmpl_output.clone().unwrap_or_else(|| carried_tmpl.clone());
    let root_prev_c = compile_root(&c.root_prev, &carried_tmpl);
    let expect_frozen = if c.op == VaultOp::Control(4) { 1 } else { 0 };
    let root_new = c.root_new.clone().unwrap_or(RootState { frozen: expect_frozen, ..c.root_prev.advanced() });
    let root_next_c = compile_root(&root_new, &output_tmpl);

    /* ---- inputs / outputs ---- */
    let mut entries: Vec<UtxoEntry> = vec![cov_utxo(c.vault_prev.reserve, &vault_prev_c, COV_VAULT)];
    let mut input_ids: Vec<(u8, u64)> = vec![(1, 0)];
    let mut outputs: Vec<TransactionOutput> = vec![];

    let root_input_idx: u16 = 1;
    if !c.no_root {
        entries.push(cov_utxo(ROOT_KAS, &root_prev_c, c.root_covid_carried));
        input_ids.push((2, c.root_sequence));
    }
    let recover_dest = c.recover_dest.unwrap_or(recovery_pk);
    match c.op {
        VaultOp::Recover => outputs.push(p2pk_out(&recover_dest, c.vault_prev.reserve)),
        _ => outputs.push(cov_out(c.vault_succ_value.unwrap_or(c.vault_new.reserve), &vault_next_c, 0, COV_VAULT)),
    }
    if !c.no_root {
        outputs.push(cov_out(ROOT_KAS - ROOT_FEE_PAID, &root_next_c, root_input_idx, c.root_covid_carried));
    }

    /* token position (recovery, or riding a control op) */
    let tok_prev = compile_kcc20(COV_VAULT.as_bytes().try_into().unwrap(), IDENTIFIER_COVENANT_ID, PREV_TOKEN_AMOUNT, false, 2);
    let mut token_input_idx: Option<usize> = None;
    let mut token_sigscript: Option<Vec<u8>> = None;
    let wants_tokens = (c.op == VaultOp::Recover && c.recover_with_tokens) || c.tokens_ride;
    if wants_tokens {
        let amount = PREV_TOKEN_AMOUNT + c.recover_amount_delta;
        let (t_owner, t_type) = if c.op == VaultOp::Recover {
            (recover_dest, IDENTIFIER_PUBKEY)
        } else {
            (COV_VAULT.as_bytes().try_into().unwrap(), IDENTIFIER_COVENANT_ID)
        };
        let tok_out = compile_kcc20(t_owner, t_type, amount, false, 2);
        token_input_idx = Some(input_ids.len());
        entries.push(cov_utxo(TOKEN_CARRY, &tok_prev, COV_TOKEN));
        input_ids.push((3, 0));
        outputs.push(cov_out(TOKEN_CARRY, &tok_out, token_input_idx.unwrap() as u16, COV_TOKEN));
        token_sigscript = Some(cov_call_opt(
            &tok_prev,
            "transfer",
            vec![vec![kcc20_state(t_owner, t_type, amount, false)].into(), Vec::<Expr>::new().into(), Expr::bytes(vec![0u8])],
            true,
        ));
    }

    let mut second_root_idx: Option<usize> = None;
    if c.two_roots {
        second_root_idx = Some(input_ids.len());
        entries.push(cov_utxo(ROOT_KAS, &root_prev_c, c.root_covid_carried));
        input_ids.push((4, c.root_sequence));
        outputs.push(cov_out(ROOT_KAS - ROOT_FEE_PAID, &root_next_c, second_root_idx.unwrap() as u16, c.root_covid_carried));
    }
    let alien_prev = compile_kcc20(xonly32(&kp(0x66)), IDENTIFIER_PUBKEY, 5, false, 2);
    let mut alien_idx: Option<usize> = None;
    if c.alien_rider {
        alien_idx = Some(input_ids.len());
        entries.push(cov_utxo(KAS, &alien_prev, COV_ALIEN));
        input_ids.push((5, 0));
        outputs.push(cov_out(KAS, &alien_prev, alien_idx.unwrap() as u16, COV_ALIEN));
    }

    /* fuel input pays the network fee (owner ops never touch the reserve) */
    let fuel = kp(0x63);
    let fuel_pk = xonly32(&fuel);
    let fuel_idx = input_ids.len();
    entries.push(UtxoEntry::new(FUEL as u64, p2pk_spk(&fuel_pk), 0, false, None));
    input_ids.push((6, 0));
    let total_in: i64 = entries.iter().map(|e| e.amount as i64).sum();
    let total_out_so_far: i64 = outputs.iter().map(|o| o.value as i64).sum();
    outputs.push(p2pk_out(&fuel_pk, total_in - total_out_so_far - FEE));

    /* ---- sign (all outputs, sequences and budgets are fixed now) ---- */
    let unsigned = build_tx(input_ids.iter().map(|(id, seq)| tx_input(*id, vec![], *seq, c.budget)).collect(), outputs.clone());
    let fuel_sig = sign(&unsigned, &entries, fuel_idx, &fuel);

    let mut sigscripts: Vec<Vec<u8>> = input_ids.iter().map(|_| vec![]).collect();
    sigscripts[0] = match c.op {
        VaultOp::Control(sel) => cov_call(&vault_prev_c, "ownerControl", vec![vault_state_arg(&c.vault_new), Expr::int(sel)]),
        VaultOp::Recover => {
            let amount = PREV_TOKEN_AMOUNT + c.recover_amount_delta;
            cov_call(
                &vault_prev_c,
                "ownerRecover",
                vec![Vec::<Expr<'static>>::new().into(), kcc20_state(recover_dest, IDENTIFIER_PUBKEY, amount, false)],
            )
        }
    };
    if !c.no_root {
        let root_ss = match c.root_succession {
            Some(seed) => {
                let s = sign(&unsigned, &entries, 1, &kp(seed));
                cov_call(&root_prev_c, "rootSuccession", vec![root_state_arg(&root_new), Expr::bytes(s)])
            }
            None => {
                let blob = root_owner_blob(&unsigned, &entries, 1, &c.root_signers);
                let args = vec![root_state_arg(&root_new), Expr::int(c.root_action), Expr::bytes(blob)];
                match c.root_decoy_state.as_ref() {
                    Some(decoy) => {
                        let decoy_c = compile_root(decoy, &carried_tmpl);
                        cov_call_with_decoy_redeem(&root_prev_c, &decoy_c, "rootAction", args)
                    }
                    None => cov_call(&root_prev_c, "rootAction", args),
                }
            }
        };
        sigscripts[1] = root_ss;
    }
    if let (Some(i), Some(ss)) = (token_input_idx, token_sigscript.clone()) {
        sigscripts[i] = ss;
    }
    if let Some(i) = second_root_idx {
        let blob = root_owner_blob(&unsigned, &entries, i, &c.root_signers);
        sigscripts[i] = cov_call(&root_prev_c, "rootAction", vec![root_state_arg(&root_new), Expr::int(c.root_action), Expr::bytes(blob)]);
    }
    if let Some(i) = alien_idx {
        sigscripts[i] = cov_call_opt(
            &alien_prev,
            "transfer",
            vec![vec![kcc20_state(xonly32(&kp(0x66)), IDENTIFIER_PUBKEY, 5, false)].into(), Vec::<Expr>::new().into(), Expr::bytes(vec![0u8])],
            true,
        );
    }
    sigscripts[fuel_idx] = p2pk_sigscript(fuel_sig);

    let inputs: Vec<TransactionInput> = input_ids.iter().zip(sigscripts).map(|((id, seq), ss)| tx_input(*id, ss, *seq, c.budget)).collect();
    let tx = build_tx(inputs, outputs);

    let mut results = vec![];
    let mut units = vec![];
    for i in 0..tx.inputs.len() {
        let (r, u) = execute_input_measured(tx.clone(), entries.clone(), i);
        results.push(r);
        units.push(u);
    }
    VaultOutcome { results, units, tx, entries, vault_redeem_len: vault_prev_c.script.len(), root_redeem_len: root_prev_c.script.len() }
}

fn accept_vault(label: &str, c: &VaultCase) -> VaultOutcome {
    let o = run_vault_owner_op(c);
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("{label}: input {i} must ACCEPT the honest case: {e:?}"));
    }
    o
}
fn refuse_vault(label: &str, c: &VaultCase) -> String {
    let o = run_vault_owner_op(c);
    match &o.results[0] {
        Ok(()) => panic!("{label}: the VAULT input accepted a case that must be refused"),
        Err(e) => format!("{e:?}"),
    }
}

/* ================================================================== */
/* the root pin this vault is compiled against                         */
/* ================================================================== */

#[test]
fn v7pay_root_pin_geometry_matches_the_production_root() {
    // The vault slices the root input's revealed redeem by these pinned
    // lengths and rebuilds an 11-byte tail. They are not independent trust
    // inputs (rootTemplateVmHash already pins the exact root script), but a
    // mismatch would make every owner operation fail closed, so they are
    // asserted against the compiler's own layout here.
    let tmpl = RootTemplate::default();
    let pin = root_pin(COV_ROOT, &tmpl);
    for s in [
        RootState::with(1, 1, 1, 0),
        RootState::with(12, 12, 1, 6),
        RootState { frozen: 1, nonce: 1, ..RootState::with(7, 4, 2, 3) },
    ] {
        let c = compile_root(&s, &tmpl);
        let t = template_of(&c);
        assert_eq!(t.prefix.len() as i64, pin.prefix_len, "rootPrefixLen must not depend on the live state");
        assert_eq!(t.state_len as i64, pin.state_len, "rootStateLen must be CONSTANT");
        assert_eq!(t.suffix.len() as i64, pin.suffix_len, "rootSuffixLen must not depend on the live state");
        assert_eq!(t.hash, pin.hash, "rootTemplateVmHash must not depend on the live state");
        let state = &c.script[c.state_layout.start..c.state_layout.start + c.state_layout.len];
        let tail = &state[state.len() - ROOT_TAIL_LEN..];
        let mut expect = vec![0x01u8, s.frozen as u8, 0x08u8];
        expect.extend_from_slice(&num8(s.nonce));
        assert_eq!(tail, &expect[..], "the TAIL the vault rebuilds must be 0x01||frozen||0x08||nonce8");
    }
    println!(
        "[pin] rootPrefixLen {} | rootStateLen {} | rootSuffixLen {} | TAIL_LEN {} | rootTemplateVmHash {}",
        pin.prefix_len,
        pin.state_len,
        pin.suffix_len,
        ROOT_TAIL_LEN,
        hx(&pin.hash)
    );
}

/* ================================================================== */
/* honest rooted-vault owner operations                                */
/* ================================================================== */

#[test]
fn v7pay_honest_owner_control_selectors_0_to_4() {
    for sel in 0..=4i64 {
        let c = VaultCase::honest(VaultOp::Control(sel));
        let root_path = if sel == 4 { "FREEZE (emergency quorum K=1)" } else { "AUTHORIZE (full quorum)" };
        let o = accept_vault(&format!("ownerControl selector {sel} under root {root_path}"), &c);
        println!(
            "VAULT ownerControl({sel}) under root {root_path}: vault units {} | root units {} | vault redeem {} B | root redeem {} B",
            o.units[0], o.units[1], o.vault_redeem_len, o.root_redeem_len
        );
    }
}

#[test]
fn v7pay_honest_owner_recover_to_the_genesis_pinned_destination() {
    let o = accept_vault("ownerRecover under AUTHORIZE (reserve + tokens -> recoveryPk)", &VaultCase::honest(VaultOp::Recover));
    println!("VAULT ownerRecover under root AUTHORIZE: vault units {} | root units {} | token units {}", o.units[0], o.units[1], o.units[2]);
}

#[test]
fn v7pay_honest_owner_recover_without_a_token_position() {
    // The controller can terminate even when the position is not in the
    // transaction; the fee reserve still pays out to the pinned destination.
    let mut c = VaultCase::honest(VaultOp::Recover);
    c.recover_with_tokens = false;
    accept_vault("ownerRecover with no token position present", &c);
}

#[test]
fn v7pay_honest_accepts_root_nonce_carries() {
    // The byte-level pin rebuilds the successor tail with OpNum2Bin(prev+1, 8).
    for nonce in [255i64, 65_535, i64::from(u32::MAX)] {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_prev = RootState { nonce, ..c.root_prev.clone() };
        accept_vault(&format!("ownerControl(2) with root nonce {nonce} -> {}", nonce + 1), &c);
    }
}

#[test]
fn v7pay_honest_accepts_a_12_of_12_root() {
    let mut c = VaultCase::honest(VaultOp::Control(0));
    c.root_prev = RootState::with(12, 12, 1, 6);
    c.root_signers = (0..12).collect();
    accept_vault("ownerControl(0) under a 12-of-12 root AUTHORIZE", &c);
}

/* ================================================================== */
/* hostile matrix — every vault-side row of sections 7.8 and 10.8      */
/* ================================================================== */

fn vault_hostile_rows() -> Vec<(&'static str, VaultCase)> {
    let mut rows: Vec<(&'static str, VaultCase)> = vec![];

    /* ---- the 24 section-7.8 vault-side rows ---- */

    rows.push(("no root input at all (delegate/hosted admin acting as owner)", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.no_root = true;
        c
    }));
    rows.push(("root of a DIFFERENT organization (cross-organization confusion)", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_covid_carried = COV_ROOT_B; // pinned stays COV_ROOT
        c
    }));
    rows.push(("root input with a substituted root template", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.wrong_root_template = true;
        c
    }));
    rows.push(("two inputs of the root family", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.two_roots = true;
        c
    }));
    rows.push(("foreign covenant family riding an owner operation", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.alien_rider = true;
        c
    }));
    rows.push(("tokens riding an owner control operation", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.tokens_ride = true;
        c
    }));
    rows.push(("root running ROTATE in the same transaction", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_action = 1;
        let mut n = c.root_prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.root_new = Some(n);
        c
    }));
    rows.push(("root running UNFREEZE in the same transaction", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_prev = RootState { frozen: 1, ..c.root_prev.clone() };
        c.root_action = 3;
        c.root_new = Some(RootState { frozen: 0, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("root running OWNER-RECOVER in the same transaction (D6: it lands FROZEN)", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_prev = RootState::with(4, 4, 1, 2);
        c.root_action = 4;
        c.root_sequence = RECOVERY_DELAY as u64;
        c.root_signers = vec![0, 1];
        let mut n = c.root_prev.advanced();
        n.owners[2] = ZERO32;
        n.owners[3] = ZERO32;
        n.owner_m = 2;
        n.recovery_m = 2;
        n.frozen = 1; // decision D6
        c.root_new = Some(n);
        c
    }));
    rows.push(("root running SUCCESSION under a general owner operation", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_succession = Some(SUCCESSOR_SEED);
        c.root_sequence = SUCCESSION_DELAY as u64;
        let mut n = c.root_prev.advanced();
        n.owners[0] = xonly32(&kp(0x91));
        n.frozen = 1;
        c.root_new = Some(n);
        c
    }));
    rows.push(("root running SUCCESSION under the EMERGENCY pause (selector 4)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_succession = Some(SUCCESSOR_SEED);
        c.root_sequence = SUCCESSION_DELAY as u64;
        let mut n = c.root_prev.advanced();
        n.owners[0] = xonly32(&kp(0x91));
        n.frozen = 1;
        c.root_new = Some(n);
        c
    }));
    rows.push(("frozen root authorizing a general owner operation", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_prev = RootState { frozen: 1, ..c.root_prev.clone() };
        c.root_action = 1; // ROTATE is the only full-quorum action allowed while frozen
        let mut n = c.root_prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.root_new = Some(n);
        c
    }));
    rows.push(("EMERGENCY pause (selector 4) pinned to an AUTHORIZE root successor", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_action = 0;
        c.root_signers = vec![0, 1];
        c.root_new = Some(c.root_prev.advanced()); // frozen stays 0
        c
    }));
    for (label, sel) in [
        ("ownerControl selector 0 pinned to a FREEZE root successor", 0i64),
        ("ownerControl selector 1 pinned to a FREEZE root successor", 1),
        ("ownerControl selector 2 pinned to a FREEZE root successor", 2),
        ("ownerControl selector 3 pinned to a FREEZE root successor", 3),
    ] {
        rows.push((label, {
            let mut c = VaultCase::honest(VaultOp::Control(sel));
            c.root_action = 2;
            c.root_signers = vec![0];
            c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
            c
        }));
    }
    rows.push(("root successor nonce not advanced", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_new = Some(c.root_prev.clone());
        c
    }));
    rows.push(("selector out of range (5)", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.op = VaultOp::Control(5);
        c
    }));
    rows.push(("negative selector", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.op = VaultOp::Control(-1);
        c
    }));
    rows.push(("selector / successor mismatch (pause selector, agentRoot change)", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.vault_new = VaultState { agent_root: [0x99; 32], policy_nonce: 1, ..c.vault_prev.clone() };
        c
    }));
    rows.push(("setAgentRoot without a nonce increment", {
        let mut c = VaultCase::honest(VaultOp::Control(0));
        c.vault_new = VaultState { agent_root: [0x99; 32], ..c.vault_prev.clone() };
        c
    }));
    rows.push(("successor value != the declared fee reserve", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.vault_succ_value = Some(RESERVE - 1);
        c
    }));
    rows.push(("EMERGENCY pause on an already paused vault", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.vault_prev = VaultState { paused: 1, ..c.vault_prev.clone() };
        c.vault_new = VaultState { paused: 1, ..c.vault_prev.clone() };
        c
    }));
    rows.push(("EMERGENCY pause silently changing the agent root", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.vault_new = VaultState { paused: 1, agent_root: [0x99; 32], ..c.vault_prev.clone() };
        c
    }));
    rows.push(("recovery redirected to an attacker key", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.recover_dest = Some(xonly32(&kp(OUTSIDER_SEED)));
        c
    }));
    rows.push(("recovery paying out only part of the token position", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.recover_amount_delta = -1;
        c
    }));
    rows.push(("recovery without the root's authorization", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.no_root = true;
        c
    }));
    rows.push(("recovery under a FREEZE root successor (the emergency quorum must not terminate a vault)", {
        let mut c = VaultCase::honest(VaultOp::Recover);
        c.root_action = 2;
        c.root_signers = vec![0];
        c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
        c
    }));

    /* ---- the 9 section-9.4 rows that attack the byte-level pin itself ---- */

    rows.push(("[pin] successor TAIL with the frozen byte flipped 0x00 -> 0x01", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_action = 0;
        c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("[pin] successor TAIL with the frozen byte flipped 0x01 -> 0x00 (selector 4)", {
        let mut c = VaultCase::honest(VaultOp::Control(4));
        c.root_action = 2;
        c.root_new = Some(c.root_prev.advanced()); // frozen 0
        c
    }));
    rows.push(("[pin] successor TAIL nonce advanced by two", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_new = Some(RootState { nonce: c.root_prev.nonce + 2, ..c.root_prev.clone() });
        c
    }));
    rows.push(("[pin] successor TAIL nonce unchanged", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_new = Some(RootState { nonce: c.root_prev.nonce, ..c.root_prev.clone() });
        c
    }));
    rows.push(("[pin] successor HEAD with one owner key changed (rotation disguised as AUTHORIZE)", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        let mut n = c.root_prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.root_new = Some(n);
        c
    }));
    rows.push(("[pin] successor HEAD with the threshold lowered", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_new = Some(RootState { owner_m: 1, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("[pin] successor HEAD with the organization id rewritten", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_new = Some(RootState { org_id: ORG_ID_B, ..c.root_prev.advanced() });
        c
    }));
    rows.push(("[pin] root OUTPUT carrying a different template with a matching head", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        c.root_tmpl_output = Some(RootTemplate { recovery_delay: RECOVERY_DELAY + 1, ..RootTemplate::default() });
        c
    }));
    rows.push(("[pin] root INPUT revealing a redeem that does not match its own P2SH", {
        let mut c = VaultCase::honest(VaultOp::Control(2));
        // same template (so blake2b(prefix||suffix) still matches the pin),
        // different state -> P2SH(revealed redeem) != the input's scriptPubKey
        c.root_decoy_state = Some(RootState { nonce: 77, ..c.root_prev.clone() });
        c
    }));
    rows
}

#[test]
fn v7pay_hostile_matrix_all_refused() {
    let rows = vault_hostile_rows();
    println!("ROOTED VAULT HOSTILE MATRIX ON PRODUCTION BYTES ({} rows)", rows.len());
    for (label, case) in rows.iter() {
        let err = refuse_vault(label, case);
        println!("  REFUSED  {label}\n           -> {err}");
    }
    // 37 ported rows (sections 7.8 + 10.8) + 1 new row the production candidate
    // adds (recovery under a FREEZE root successor).
    assert!(rows.len() >= 38, "every vault-side row of 7.8/10.8 must be present (got {})", rows.len());
    assert!(rows.iter().any(|(l, _)| l.contains("selector 0 pinned to a FREEZE")), "section 9.4 requires selectors 0-3 under FREEZE");
    assert!(rows.iter().filter(|(l, _)| l.starts_with("[pin]")).count() >= 9, "the 9 byte-level pin rows must all run");
}

/// The vault delegates QUORUM authority to the root input: with an
/// under-quorum blob the ROOT input is what refuses, so the transaction is
/// invalid. Recorded explicitly rather than assumed — the vault's own rule is
/// "the pinned root transitioned into exactly these successor bytes".
#[test]
fn v7pay_under_quorum_is_refused_by_the_root_input() {
    let mut c = VaultCase::honest(VaultOp::Control(2));
    c.root_signers = vec![0]; // 1 of the required 2
    let o = run_vault_owner_op(&c);
    assert!(o.results[1].is_err(), "the root input must refuse an under-quorum owner operation");
    println!(
        "VAULT under-quorum: root input REFUSED -> {:?} | vault input result: {:?}",
        o.results[1].as_ref().unwrap_err(),
        o.results[0]
    );
}

/* ================================================================== */
/* D6 on the vault side (coordinator decision, section 11)             */
/* ================================================================== */

#[test]
fn v7pay_d6_frozen_recovery_cannot_authorize_a_general_owner_operation() {
    // Section 10.7 measured that an OWNER-RECOVER leaving the HEAD unchanged
    // produced a successor byte-identical to an AUTHORIZE one, so a recovery
    // quorum could authorize a GENERAL vault owner operation in ONE
    // transaction. D6 makes action 4 land FROZEN, so that is now impossible.
    let mut c = VaultCase::honest(VaultOp::Control(2)); // a general owner op
    c.root_prev = RootState::with(4, 4, 1, 2); // recoveryM 2 < ownerM 4
    c.root_action = 4;
    c.root_sequence = RECOVERY_DELAY as u64;
    c.root_signers = vec![0, 1]; // the RECOVERY quorum only
    c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() }); // head unchanged, D6 landing
    let err = refuse_vault("D6: frozen OWNER-RECOVER under a general vault owner operation", &c);
    println!("D6: recovery quorum can no longer authorize a general vault owner op -> REFUSED by the vault pin: {err}");

    // And landing it UNFROZEN — the shape that used to imitate an AUTHORIZE —
    // is refused by the ROOT itself, so neither input can be satisfied.
    let mut unfrozen = c.clone();
    unfrozen.root_new = Some(c.root_prev.advanced()); // frozen 0
    let o = run_vault_owner_op(&unfrozen);
    assert!(o.results[1].is_err(), "the root must refuse an OWNER-RECOVER landing unfrozen (D6)");
    println!("D6: the same recovery landing UNFROZEN is refused by the ROOT input -> {:?}", o.results[1].as_ref().unwrap_err());
}

/// MEASURED CONSEQUENCE of D6, recorded rather than assumed: a frozen recovery
/// with an UNCHANGED head is byte-identical to a FREEZE successor, so it can
/// still ride the EMERGENCY pause (selector 4). That is the accepted outcome
/// of section 11: the only vault effect reachable there is the
/// AUTHORITY-REDUCING pause, and the recovered set must UNFREEZE under its own
/// full quorum before any general owner operation.
#[test]
fn v7pay_d6_frozen_recovery_can_still_ride_only_the_emergency_pause() {
    let mut c = VaultCase::honest(VaultOp::Control(4)); // the EMERGENCY pause
    c.root_prev = RootState::with(4, 4, 1, 2);
    c.root_action = 4;
    c.root_sequence = RECOVERY_DELAY as u64;
    c.root_signers = vec![0, 1];
    c.root_new = Some(RootState { frozen: 1, ..c.root_prev.advanced() });
    let o = run_vault_owner_op(&c);
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("D6 consequence: input {i} was expected to accept: {e:?}"));
    }
    println!(
        "D6 CONSEQUENCE (measured): a frozen OWNER-RECOVER with an unchanged head is byte-identical to a FREEZE successor, so it can ride \
         selector 4 (EMERGENCY pause) and NOTHING else. That is section 11's accepted outcome: the effect is AUTHORITY-REDUCING and the \
         recovered set must UNFREEZE under its own full quorum before any general owner operation."
    );
}

/* ================================================================== */
/* delegate (agent) spend — the path the root never touches            */
/* ================================================================== */

#[derive(Clone)]
struct AgentLeaf {
    pk: [u8; 32],
    max_per_spend: i64,
    period_budget: i64,
    period_length_daa: i64,
    period_start_daa: i64,
    period_spent: i64,
    max_fee_per_tx: i64,
    max_carry_kas: i64,
    recipient_root: [u8; 32],
}
fn agent_leaf(a: &AgentLeaf) -> [u8; 32] {
    sha256(&[
        &TOKEN_AGENT_DOMAIN,
        &a.pk,
        &num8(a.max_per_spend),
        &num8(a.period_budget),
        &num8(a.period_length_daa),
        &num8(a.period_start_daa),
        &num8(a.period_spent),
        &num8(a.max_fee_per_tx),
        &num8(a.max_carry_kas),
        &a.recipient_root,
        &[0x00],
    ])
}

#[derive(Clone)]
struct AgentCase {
    profile: Profile,
    leaf: AgentLeaf,
    spend: i64,
    periods_elapsed: i64,
    lock_time: u64,
    budget: u16,
    /// number of OTHER agents in the policy tree; 4096 => proof depth 12
    agent_tree_size: usize,
    /// index of this agent's leaf inside that tree
    agent_index: usize,
    /// recipient tree depth; 16 is the production maximum
    recip_depth: u32,
    /// extra data pushes at the FRONT of the controller sigscript
    stack_pad: usize,
    /// drive the delegate spend with a root input present (must be REFUSED)
    root_rider: bool,
}
fn agent_honest(profile: Profile) -> AgentCase {
    let recipient_pk = xonly32(&kp(0x52));
    AgentCase {
        profile,
        leaf: AgentLeaf {
            pk: xonly32(&kp(0x62)),
            max_per_spend: 500,
            period_budget: 900,
            period_length_daa: 864_000,
            period_start_daa: 541_000_000,
            period_spent: 0,
            max_fee_per_tx: RESERVE_CONSUMED,
            max_carry_kas: RECIPIENT_CARRY,
            recipient_root: sha256(&[&RECIP_DOMAIN, &recipient_pk]),
        },
        spend: SPEND,
        periods_elapsed: 0,
        lock_time: 0,
        budget: 400,
        agent_tree_size: 1,
        agent_index: 0,
        recip_depth: 0,
        stack_pad: 0,
        root_rider: false,
    }
}

struct AgentOutcome {
    results: Vec<Result<(), TxScriptError>>,
    units: Vec<u64>,
    tx: Transaction,
    entries: Vec<UtxoEntry>,
    redeem_len: usize,
    state_region_len: usize,
    sigscript_len: usize,
}

fn run_agent(c: &AgentCase) -> AgentOutcome {
    let recovery_pk = xonly32(&kp(0x51));
    let recipient_pk = xonly32(&kp(0x52));
    let tok = token_pin(COV_TOKEN);
    let rpin = root_pin(COV_ROOT, &RootTemplate::default());

    /* recipient tree (depth 0 or the production maximum 16) */
    let (recip_root, recip_sibs, recip_bits) = recip_tree(c.recip_depth, &recipient_pk);
    let leaf = AgentLeaf { recipient_root: recip_root, ..c.leaf.clone() };

    let mut new_start = leaf.period_start_daa;
    let mut new_spent = leaf.period_spent + c.spend;
    if c.periods_elapsed >= 1 {
        new_start = leaf.period_start_daa + c.periods_elapsed * leaf.period_length_daa;
        new_spent = c.spend;
    }
    let new_leaf = AgentLeaf { period_start_daa: new_start, period_spent: new_spent, ..leaf.clone() };

    /* agent policy tree (size 1 or the production maximum 4096 = depth 12) */
    let (prev_root, policy_sibs, policy_bits, new_root) = if c.agent_tree_size <= 1 {
        (agent_leaf(&leaf), Vec::new(), 0u64, agent_leaf(&new_leaf))
    } else {
        let mut leaves: Vec<[u8; 32]> = (0..c.agent_tree_size)
            .map(|i| {
                let mut pk = [0u8; 32];
                pk[..4].copy_from_slice(&(i as u32).to_le_bytes());
                pk[31] = 0x77;
                agent_leaf(&AgentLeaf { pk, ..leaf.clone() })
            })
            .collect();
        leaves[c.agent_index] = agent_leaf(&leaf);
        let (pr, sibs, bits) = merkle(&leaves, c.agent_index);
        leaves[c.agent_index] = agent_leaf(&new_leaf);
        let (nr, _, _) = merkle(&leaves, c.agent_index);
        (pr, sibs, bits, nr)
    };

    let prev = VaultState { reserve: RESERVE, paused: 0, agent_root: prev_root, policy_nonce: 0 };
    let next = VaultState { reserve: RESERVE - RESERVE_CONSUMED, agent_root: new_root, ..prev.clone() };
    let ctrl_prev = compile_vault(c.profile, &tok, &rpin, &recovery_pk, &prev);
    let ctrl_next = compile_vault(c.profile, &tok, &rpin, &recovery_pk, &next);

    let self_id: [u8; 32] = COV_VAULT.as_bytes().try_into().unwrap();
    let tok_prev = compile_kcc20(self_id, IDENTIFIER_COVENANT_ID, PREV_TOKEN_AMOUNT, false, 2);
    let tok_self = compile_kcc20(self_id, IDENTIFIER_COVENANT_ID, PREV_TOKEN_AMOUNT - c.spend, false, 2);
    let tok_recipient = compile_kcc20(recipient_pk, IDENTIFIER_PUBKEY, c.spend, false, 2);

    /* an honest delegate spend never touches the root; `root_rider` adds one
     * to prove the delegate path still refuses EVERY foreign covenant input. */
    let root_prev_c = compile_root(&RootState::with(3, 2, 1, 2), &RootTemplate::default());
    let root_next_c = compile_root(&RootState::with(3, 2, 1, 2).advanced(), &RootTemplate::default());

    let fuel = kp(0x63);
    let fuel_pk = xonly32(&fuel);
    let mut entries = vec![
        cov_utxo(RESERVE, &ctrl_prev, COV_VAULT),
        cov_utxo(TOKEN_CARRY, &tok_prev, COV_TOKEN),
        UtxoEntry::new(FUEL as u64, p2pk_spk(&fuel_pk), 0, false, None),
    ];
    let mut outputs = vec![
        cov_out(RESERVE - RESERVE_CONSUMED, &ctrl_next, 0, COV_VAULT),
        cov_out(TOKEN_CARRY - RECIPIENT_CARRY, &tok_self, 1, COV_TOKEN),
        cov_out(RECIPIENT_CARRY, &tok_recipient, 1, COV_TOKEN),
        p2pk_out(&fuel_pk, FUEL - (FEE - RESERVE_CONSUMED)),
    ];
    let mut ids: Vec<u8> = vec![1, 2, 3];
    if c.root_rider {
        entries.push(cov_utxo(ROOT_KAS, &root_prev_c, COV_ROOT));
        ids.push(4);
        outputs.push(cov_out(ROOT_KAS - ROOT_FEE_PAID, &root_next_c, 3, COV_ROOT));
        // the rider's value has to come from somewhere: give the change back
        outputs[3].value += (ROOT_FEE_PAID) as u64;
    }

    let unsigned = Transaction::new(
        1,
        ids.iter().map(|id| tx_input(*id, vec![], 0, c.budget)).collect(),
        outputs.clone(),
        c.lock_time,
        SubnetworkId::default(),
        0,
        vec![],
    );
    let agent_sig = sign(&unsigned, &entries, 0, &kp(0x62));
    let fuel_sig = sign(&unsigned, &entries, 2, &fuel);

    let args: Vec<Expr<'static>> = vec![
        vault_state_arg(&next),
        kcc20_state(self_id, IDENTIFIER_COVENANT_ID, PREV_TOKEN_AMOUNT - c.spend, false),
        kcc20_state(recipient_pk, IDENTIFIER_PUBKEY, c.spend, false),
        Expr::bytes(leaf.pk.to_vec()),
        Expr::int(leaf.max_per_spend),
        Expr::int(leaf.period_budget),
        Expr::int(leaf.period_length_daa),
        Expr::int(leaf.period_start_daa),
        Expr::int(leaf.period_spent),
        Expr::int(leaf.max_fee_per_tx),
        Expr::int(leaf.max_carry_kas),
        Expr::bytes(leaf.recipient_root.to_vec()),
        Expr::bytes(policy_sibs.clone()),
        Expr::int(policy_bits as i64),
        Expr::int(c.periods_elapsed),
        Expr::bytes(recipient_pk.to_vec()),
        Expr::bytes(recip_sibs.clone()),
        Expr::int(recip_bits as i64),
        Expr::bytes(agent_sig),
    ];
    let mut ctrl_ss = cov_call(&ctrl_prev, "tokenAgentSpend", args);
    if c.stack_pad > 0 {
        let mut pad = ScriptBuilder::new();
        for _ in 0..c.stack_pad {
            pad.add_data(&[0x01u8]).unwrap();
        }
        let mut padded = pad.drain();
        padded.extend_from_slice(&ctrl_ss);
        ctrl_ss = padded;
    }
    let token_ss = cov_call_opt(
        &tok_prev,
        "transfer",
        vec![
            vec![
                kcc20_state(self_id, IDENTIFIER_COVENANT_ID, PREV_TOKEN_AMOUNT - c.spend, false),
                kcc20_state(recipient_pk, IDENTIFIER_PUBKEY, c.spend, false),
            ]
            .into(),
            Vec::<Expr>::new().into(),
            Expr::bytes(vec![0u8]),
        ],
        true,
    );
    let sigscript_len = ctrl_ss.len();
    let mut sigscripts = vec![ctrl_ss, token_ss, p2pk_sigscript(fuel_sig)];
    if c.root_rider {
        let blob = root_owner_blob(&unsigned, &entries, 3, &[0, 1]);
        sigscripts.push(cov_call(
            &root_prev_c,
            "rootAction",
            vec![root_state_arg(&RootState::with(3, 2, 1, 2).advanced()), Expr::int(0), Expr::bytes(blob)],
        ));
    }
    let tx = Transaction::new(
        1,
        ids.iter().zip(sigscripts).map(|(id, ss)| tx_input(*id, ss, 0, c.budget)).collect(),
        outputs,
        c.lock_time,
        SubnetworkId::default(),
        0,
        vec![],
    );
    let mut results = vec![];
    let mut units = vec![];
    for i in 0..tx.inputs.len() {
        let (r, u) = execute_input_measured(tx.clone(), entries.clone(), i);
        results.push(r);
        units.push(u);
    }
    AgentOutcome { results, units, tx, entries, redeem_len: ctrl_prev.script.len(), state_region_len: ctrl_prev.state_layout.len, sigscript_len }
}

#[test]
fn v7pay_honest_delegate_spend_needs_no_root_input() {
    let o = run_agent(&agent_honest(Profile::RootedV7));
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("rooted v0.7 delegate spend: input {i} must accept: {e:?}"));
    }
    println!(
        "V7 rooted delegate spend: units {} | redeem {} B | state {} B | sigscript {} B",
        o.units[0], o.redeem_len, o.state_region_len, o.sigscript_len
    );
    assert!(o.redeem_len <= DELEGATE_REDEEM_TARGET_B, "section 9.4 target: {} B > {DELEGATE_REDEEM_TARGET_B} B", o.redeem_len);
}

#[test]
fn v7pay_honest_delegate_spend_with_period_rollover() {
    let mut c = agent_honest(Profile::RootedV7);
    c.leaf.period_spent = c.leaf.period_budget; // the old period is exhausted
    c.periods_elapsed = 2;
    c.lock_time = (c.leaf.period_start_daa + 2 * c.leaf.period_length_daa) as u64;
    let o = run_agent(&c);
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("rollover spend: input {i} must accept: {e:?}"));
    }
    println!("V7 rooted delegate spend WITH ROLLOVER (2 periods): units {}", o.units[0]);
}

#[test]
fn v7pay_honest_delegate_spend_at_production_proof_depths() {
    // agent policy tree 4096 leaves (depth 12) and recipient tree depth 16 —
    // the maximum depths the covenant's unrolled folds accept.
    let mut c = agent_honest(Profile::RootedV7);
    c.agent_tree_size = 4096;
    c.agent_index = 1337;
    c.recip_depth = 16;
    let o = run_agent(&c);
    for (i, r) in o.results.iter().enumerate() {
        r.as_ref().unwrap_or_else(|e| panic!("deep proofs: input {i} must accept: {e:?}"));
    }
    println!("V7 rooted delegate spend at depths agent 12 / recipient 16: units {} | sigscript {} B", o.units[0], o.sigscript_len);
}

#[test]
fn v7pay_delegate_spend_refuses_a_root_covenant_rider() {
    // The delegate path is untouched by the v0.7 delta: it keeps the FROZEN
    // v0.5 `requireNoForeignCovenantInputs`, so even the ORGANIZATION'S OWN
    // root is a foreign covenant input on a delegate spend.
    let mut c = agent_honest(Profile::RootedV7);
    c.root_rider = true;
    let o = run_agent(&c);
    let err = o.results[0].as_ref().expect_err("a delegate spend carrying the root covenant must be REFUSED");
    println!("delegate spend with a root-family rider -> REFUSED: {err:?}");
}

/* --- D2 (v0.6 adversarial review, F1): zero-length period ------------ */

fn d2_case(profile: Profile) -> AgentCase {
    let mut c = agent_honest(profile);
    c.leaf.period_length_daa = 0;
    c.leaf.period_spent = c.leaf.period_budget; // the period is fully exhausted
    c.periods_elapsed = 1;
    c.lock_time = c.leaf.period_start_daa as u64; // newStart == periodStartDaa
    c
}

#[test]
fn v7pay_d2_zero_length_period_is_refused() {
    // periodLengthDaa == 0 makes the period budget vacuous: the rollover branch
    // recomputes newStart == periodStartDaa, so an agent could reset
    // periodSpent on every transaction and drain the position one cap-sized
    // spend at a time.
    let o = run_agent(&d2_case(Profile::RootedV7));
    let err = o.results[0].as_ref().expect_err("the v0.7 payment profile must REFUSE a zero-length period");
    println!("D2 zero-length period, v0.7-payment -> REFUSED: {err:?}");

    // The FROZEN v0.5 controller ACCEPTS it. Documented inherited behaviour,
    // recorded and never changed: contracts/PolicyVault.v0.5.sil is not edited.
    let f = run_agent(&d2_case(Profile::FrozenV5));
    assert!(f.results[0].is_ok(), "documented inherited behaviour: frozen v0.5 accepts a zero-length period ({:?})", f.results[0]);
    println!("D2 zero-length period, FROZEN v0.5 -> ACCEPTED (inherited behaviour, recorded not changed)");

    let h = run_agent(&agent_honest(Profile::RootedV7));
    h.results[0].as_ref().expect("an honest positive-length period must still be accepted");
}

/* ================================================================== */
/* PRODUCTION-BYTE integration: the real pv_call_encoder BINARY        */
/* ================================================================== */

mod encoder {
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn encoder_path() -> PathBuf {
        PathBuf::from(format!("{}/target/debug/pv_call_encoder", env!("CARGO_MANIFEST_DIR")))
    }
    fn tmp_dir() -> PathBuf {
        let unique = format!("{}-{}", std::process::id(), SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos());
        let dir = std::env::temp_dir().join(format!("pv-v7pay-{unique}"));
        std::fs::create_dir_all(&dir).expect("tmp dir");
        dir
    }
    fn bytes_arg(b: &[u8]) -> serde_json::Value {
        serde_json::json!({"kind": "array", "data": b.iter().map(|x| serde_json::json!({"kind": "byte", "data": x})).collect::<Vec<_>>()})
    }
    fn int_arg(v: i64) -> serde_json::Value {
        serde_json::json!({"kind": "int", "data": v})
    }

    fn ctor_args(tok: &TokenPin, root: &RootPin, recovery_pk: &[u8; 32], s: &VaultState) -> serde_json::Value {
        serde_json::Value::Array(vec![
            bytes_arg(&VAULT_ID),
            bytes_arg(&DESCRIPTOR_HASH),
            bytes_arg(tok.covid.as_bytes().as_slice()),
            bytes_arg(&tok.hash),
            int_arg(tok.prefix_len),
            int_arg(tok.state_len),
            int_arg(tok.suffix_len),
            bytes_arg(root.covid.as_bytes().as_slice()),
            bytes_arg(&root.hash),
            int_arg(root.prefix_len),
            int_arg(root.state_len),
            int_arg(root.suffix_len),
            bytes_arg(recovery_pk),
            bytes_arg(&s.agent_root),
            int_arg(s.reserve),
        ])
    }
    fn successor_json(s: &VaultState) -> serde_json::Value {
        serde_json::json!({
            "feeReserve": s.reserve,
            "paused": s.paused,
            "agentRoot": hx(&s.agent_root),
            "policyNonce": s.policy_nonce,
        })
    }
    fn kcc20_json(owner: &[u8; 32], ty: u8, amount: i64) -> serde_json::Value {
        serde_json::json!({"ownerIdentifier": hx(owner), "identifierType": ty, "amount": amount, "isMinter": false})
    }

    fn run(src: &str, ctor: serde_json::Value, call: serde_json::Value) -> Result<String, String> {
        let dir = tmp_dir();
        let s = dir.join("vault.sil");
        std::fs::write(&s, src).unwrap();
        let a = dir.join("ctor.json");
        std::fs::write(&a, serde_json::to_string(&ctor).unwrap()).unwrap();
        let cj = dir.join("call.json");
        std::fs::write(&cj, serde_json::to_string(&call).unwrap()).unwrap();
        let out = Command::new(encoder_path()).arg(&s).arg(&a).arg(&cj).output().expect("run pv_call_encoder");
        let _ = std::fs::remove_dir_all(&dir);
        if out.status.success() {
            Ok(String::from_utf8(out.stdout).unwrap().trim().to_string())
        } else {
            Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
        }
    }
    fn unhex(s: &str) -> Vec<u8> {
        (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
    }

    /// Rebuild an owner operation but take input 0's covenant-call bytes from
    /// the REAL binary instead of the in-process encoder.
    fn owner_op_with_encoder_bytes(c: &VaultCase, function: &str) -> Result<(), TxScriptError> {
        let recovery_pk = xonly32(&kp(0x51));
        let tok = token_pin(COV_TOKEN);
        let rpin = root_pin(COV_ROOT, &RootTemplate::default());
        let vault_prev_c = compile_vault(Profile::RootedV7, &tok, &rpin, &recovery_pk, &c.vault_prev);
        let src = vault_templated(src_vault_raw(), &c.vault_prev);
        let ctor = ctor_args(&tok, &rpin, &recovery_pk, &c.vault_prev);

        let call = match c.op {
            VaultOp::Control(sel) => serde_json::json!({
                "contractVersion": "policyvault-0.7-payment", "function": function,
                "opSelector": sel, "successor": successor_json(&c.vault_new)
            }),
            VaultOp::Recover => serde_json::json!({
                "contractVersion": "policyvault-0.7-payment", "function": function,
                "recipientNew": kcc20_json(&recovery_pk, IDENTIFIER_PUBKEY, PREV_TOKEN_AMOUNT)
            }),
        };
        let encoded = run(&src, ctor, call).expect("the encoder must succeed for an honest owner call");
        let mut ss = unhex(&encoded);
        ss.extend_from_slice(&push_redeem(&vault_prev_c.script));

        // Rebuild the transaction exactly as run_vault_owner_op does, then
        // swap input 0's signature script for the binary's bytes.
        let o = run_vault_owner_op(c);
        let mut inputs: Vec<TransactionInput> = o.tx.inputs.to_vec();
        assert_eq!(inputs[0].signature_script.len(), ss.len(), "the binary and the in-process encoder must agree on length");
        inputs[0].signature_script = ss;
        let tx = Transaction::new(1, inputs, o.tx.outputs.to_vec(), 0, SubnetworkId::default(), 0, vec![]);
        execute_input_measured(tx, o.entries.clone(), 0).0
    }

    #[test]
    fn v7pay_encoder_production_bytes_accepted_by_the_engine() {
        assert!(encoder_path().exists(), "build it first: cd tests/vm && cargo build --bin pv_call_encoder");
        for sel in 0..=4i64 {
            owner_op_with_encoder_bytes(&VaultCase::honest(VaultOp::Control(sel)), "ownerControl")
                .unwrap_or_else(|e| panic!("ownerControl({sel}) production encoder bytes must be accepted: {e:?}"));
            println!("  ENCODER -> ENGINE ACCEPTED  ownerControl({sel})");
        }
        owner_op_with_encoder_bytes(&VaultCase::honest(VaultOp::Recover), "ownerRecover").expect("ownerRecover production bytes");
        println!("  ENCODER -> ENGINE ACCEPTED  ownerRecover");
    }

    #[test]
    fn v7pay_encoder_fails_closed_on_out_of_domain_intent() {
        assert!(encoder_path().exists(), "build it first: cd tests/vm && cargo build --bin pv_call_encoder");
        let recovery_pk = xonly32(&kp(0x51));
        let tok = token_pin(COV_TOKEN);
        let rpin = root_pin(COV_ROOT, &RootTemplate::default());
        let vs = VaultState { reserve: RESERVE, paused: 0, agent_root: ZERO32, policy_nonce: 0 };
        let src = vault_templated(src_vault_raw(), &vs);
        let ctor = || ctor_args(&tok, &rpin, &recovery_pk, &vs);

        for (label, call) in [
            (
                "ownerControl selector out of range (5)",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "ownerControl", "opSelector": 5, "successor": successor_json(&vs)}),
            ),
            (
                "ownerControl negative selector",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "ownerControl", "opSelector": -1, "successor": successor_json(&vs)}),
            ),
            (
                "ownerControl carrying an owner signature (there is no owner key)",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "ownerControl", "opSelector": 2, "successor": successor_json(&vs), "signature": hx(&[0u8; 65])}),
            ),
            (
                "ownerRecover carrying an owner signature",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "ownerRecover", "recipientNew": kcc20_json(&recovery_pk, IDENTIFIER_PUBKEY, 10), "signature": hx(&[0u8; 65])}),
            ),
            (
                "ownerRecover carrying an opSelector",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "ownerRecover", "recipientNew": kcc20_json(&recovery_pk, IDENTIFIER_PUBKEY, 10), "opSelector": 0}),
            ),
            (
                "unknown entrypoint",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "emergencyPause", "successor": successor_json(&vs)}),
            ),
            (
                "tokenAgentSpend without the agent signature",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "tokenAgentSpend", "successor": successor_json(&vs)}),
            ),
            (
                "recipientNew with a negative amount",
                serde_json::json!({"contractVersion": "policyvault-0.7-payment", "function": "ownerRecover", "recipientNew": kcc20_json(&recovery_pk, IDENTIFIER_PUBKEY, -1)}),
            ),
        ] {
            let err = run(&src, ctor(), call).expect_err(&format!("{label}: the encoder must FAIL CLOSED"));
            println!("  ENCODER FAILED CLOSED  {label}\n           -> {err}");
        }
    }
}

/* ================================================================== */
/* measurement, standardness and stack headroom                        */
/* ================================================================== */

fn mass_of(tx: &Transaction, entries: &[UtxoEntry]) -> (u64, u64, u64, u64) {
    let mc = MassCalculator::new(1, 10, STORAGE_MASS_PARAMETER);
    let m = mc.calc_non_contextual_masses(tx);
    let populated = PopulatedTransaction::new(tx, entries.to_vec());
    let storage = mc.calc_contextual_masses(&populated).map(|c| c.storage_mass).unwrap_or(0);
    let size = transaction_estimated_serialized_size(tx) as u64;
    (size, m.compute_mass, m.transient_mass, storage)
}

fn priced_units_and_sigops(tx: &Transaction, entries: &[UtxoEntry]) -> Vec<(u64, u16, u64)> {
    (0..tx.inputs.len())
        .map(|i| {
            let (r, priced) = execute_input_measured_priced(tx.clone(), entries.to_vec(), i, 1000);
            r.unwrap_or_else(|e| panic!("priced input {i} must accept: {e:?}"));
            let budget = ComputeBudget::checked_covering_script_units(ScriptUnits(priced)).expect("budget").0;
            let sigops = post_toccata_p2sh_sig_scanner(&tx.inputs[i].signature_script, &entries[i].script_public_key);
            (priced, budget, sigops)
        })
        .collect()
}

const MAX_STACK_PROBE: usize = 244;

fn measure_peak_stack<F>(label: &str, mut run_with_pad: F) -> usize
where
    F: FnMut(usize) -> Result<(), TxScriptError>,
{
    run_with_pad(0).unwrap_or_else(|e| panic!("{label}: unpadded run must accept: {e:?}"));
    for pad in 1..=MAX_STACK_PROBE {
        if let Err(TxScriptError::StackSizeExceeded(size, max)) = run_with_pad(pad) {
            assert_eq!(max, 244, "{label}: unexpected MAX_STACK_SIZE");
            let peak = 245 - pad;
            println!("  {label}: peak combined stack {peak} (StackSizeExceeded at pad {pad}, reported {size}/{max}) -> headroom {}", 244 - peak);
            return peak;
        }
    }
    panic!("{label}: never hit MAX_STACK_SIZE within {MAX_STACK_PROBE} padding items");
}

fn check_standardness(label: &str, tx: &Transaction, entries: &[UtxoEntry], compute: u64, transient: u64) {
    for i in 0..tx.inputs.len() {
        let ops = post_toccata_p2sh_sig_scanner(&tx.inputs[i].signature_script, &entries[i].script_public_key);
        assert!(ops <= MAX_STANDARD_P2SH_SIG_OPS, "{label}: input {i} static sig-ops {ops} must be <= 15 (standard)");
    }
    for (i, o) in tx.outputs.iter().enumerate() {
        assert_ne!(ScriptClass::from_script(&o.script_public_key), ScriptClass::NonStandard, "{label}: output {i} must be a standard class");
    }
    assert!(compute <= 500_000, "{label}: compute mass {compute} exceeds the post-Toccata block-fit limit");
    assert!(transient <= 1_000_000, "{label}: transient mass {transient} exceeds the post-Toccata block-fit limit");
    if transient > 100_000 || compute > 100_000 {
        println!("    note: {label} exceeds the PRE-Toccata 100,000 standard cap — post-Toccata only");
    }
}

#[test]
fn v7pay_measurement_standardness_and_stack() {
    println!("\n===== v0.7-payment PRODUCTION MEASUREMENT (real TxScriptEngine, rusty-kaspa 2.0.1) =====");

    /* ---- 1. rooted vault owner operations (root + vault in ONE tx) ---- */
    println!("\n[1] ROOTED VAULT OWNER OPERATIONS (root + vault, one transaction)");
    for (label, case) in [
        ("ownerControl(0 setAgentRoot) under AUTHORIZE", VaultCase::honest(VaultOp::Control(0))),
        ("ownerControl(1 topUpReserve) under AUTHORIZE", VaultCase::honest(VaultOp::Control(1))),
        ("ownerControl(2 pause) under AUTHORIZE", VaultCase::honest(VaultOp::Control(2))),
        ("ownerControl(3 unpause) under AUTHORIZE", VaultCase::honest(VaultOp::Control(3))),
        ("ownerControl(4 EMERGENCY pause) under FREEZE", VaultCase::honest(VaultOp::Control(4))),
        ("ownerRecover under AUTHORIZE", VaultCase::honest(VaultOp::Recover)),
    ] {
        let o = accept_vault(label, &case);
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let p = priced_units_and_sigops(&o.tx, &o.entries);
        println!("  {label}: tx {size} B | compute_mass {compute} | transient_mass {transient} | storage_mass {storage}");
        for (i, (pu, budget, sigops)) in p.iter().enumerate() {
            println!(
                "    input {i}: sigscript {} B | units {} | priced {pu} -> budget {budget} | static sig-ops {sigops}",
                o.tx.inputs[i].signature_script.len(),
                o.units[i]
            );
        }
        println!("    vault redeem {} B | root redeem {} B", o.vault_redeem_len, o.root_redeem_len);
        assert_eq!(p[0].2, 1, "{label}: the rooted vault input must carry exactly ONE static sig-op (the agent)");
        check_standardness(label, &o.tx, &o.entries, compute, transient);
    }

    /* ---- 2. delegate spend: FROZEN v0.5 vs the v0.7 rooted profile ---- */
    println!("\n[2] DELEGATE SPEND (identical parameters; the path the root never touches)");
    println!("  {:>26} | {:>10} | {:>9} | {:>12} | {:>12} | {:>7} | {:>8}", "profile", "redeem B", "state B", "sigscript B", "script units", "tx B", "sig-ops");
    let mut redeems: Vec<(Profile, usize, u64)> = vec![];
    for profile in [Profile::FrozenV5, Profile::RootedV7] {
        let o = run_agent(&agent_honest(profile));
        for (i, r) in o.results.iter().enumerate() {
            r.as_ref().unwrap_or_else(|e| panic!("{profile:?} delegate spend input {i}: {e:?}"));
        }
        let (size, compute, transient, _s) = mass_of(&o.tx, &o.entries);
        let p = priced_units_and_sigops(&o.tx, &o.entries);
        println!(
            "  {:>26} | {:>10} | {:>9} | {:>12} | {:>12} | {:>7} | {:>8}",
            format!("{profile:?}"),
            o.redeem_len,
            o.state_region_len,
            o.sigscript_len,
            o.units[0],
            size,
            p[0].2
        );
        check_standardness(&format!("{profile:?} delegate spend"), &o.tx, &o.entries, compute, transient);
        redeems.push((profile, o.redeem_len, o.units[0]));
    }
    let v5 = redeems.iter().find(|r| r.0 == Profile::FrozenV5).unwrap();
    let v7 = redeems.iter().find(|r| r.0 == Profile::RootedV7).unwrap();
    assert_eq!(v5.1, FROZEN_V5_DELEGATE_REDEEM_B, "the frozen v0.5 baseline must not move");
    println!("  frozen v0.5 baseline : {} B", v5.1);
    println!(
        "  v0.7 rooted (production): {} B ({:+} B vs v0.5, script units {:+})",
        v7.1,
        v7.1 as i64 - v5.1 as i64,
        v7.2 as i64 - v5.2 as i64
    );
    println!(
        "  SECTION 9.4 TARGET <= {} B : {}  (measured {} B)",
        DELEGATE_REDEEM_TARGET_B,
        if v7.1 <= DELEGATE_REDEEM_TARGET_B { "MET" } else { "NOT MET" },
        v7.1
    );
    assert!(v7.1 <= DELEGATE_REDEEM_TARGET_B);

    /* ---- 3. production proof depths and rollover ---- */
    println!("\n[3] DELEGATE SPEND AT PRODUCTION PROOF DEPTHS AND WITH ROLLOVER");
    for (label, mut c) in [
        ("depths agent 12 / recipient 16", {
            let mut c = agent_honest(Profile::RootedV7);
            c.agent_tree_size = 4096;
            c.agent_index = 1337;
            c.recip_depth = 16;
            c
        }),
        ("rollover (2 periods)", {
            let mut c = agent_honest(Profile::RootedV7);
            c.leaf.period_spent = c.leaf.period_budget;
            c.periods_elapsed = 2;
            c.lock_time = (c.leaf.period_start_daa + 2 * c.leaf.period_length_daa) as u64;
            c
        }),
    ] {
        c.budget = 800;
        let o = run_agent(&c);
        for (i, r) in o.results.iter().enumerate() {
            r.as_ref().unwrap_or_else(|e| panic!("{label}: input {i} must accept: {e:?}"));
        }
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let p = priced_units_and_sigops(&o.tx, &o.entries);
        println!(
            "  {label}: tx {size} B | sigscript {} B | units {} | priced {} -> budget {} | compute_mass {compute} | transient_mass {transient} | storage_mass {storage} | sig-ops {}",
            o.sigscript_len, o.units[0], p[0].0, p[0].1, p[0].2
        );
        check_standardness(label, &o.tx, &o.entries, compute, transient);
    }

    /* ---- 4. MAX_STACK_SIZE headroom ---- */
    println!("\n[4] MAX_STACK_SIZE (244) HEADROOM");
    measure_peak_stack("rooted v0.7 delegate spend (tokenAgentSpend, deepest v0.5-derived frame)", |pad| {
        let mut c = agent_honest(Profile::RootedV7);
        c.stack_pad = pad;
        run_agent(&c).results.remove(0)
    });
    measure_peak_stack("rooted v0.7 delegate spend at depths 12/16", |pad| {
        let mut c = agent_honest(Profile::RootedV7);
        c.agent_tree_size = 4096;
        c.agent_index = 1337;
        c.recip_depth = 16;
        c.budget = 800;
        c.stack_pad = pad;
        run_agent(&c).results.remove(0)
    });
    println!("========================================================================================\n");
}
