//! VM layer — PRODUCTION CANDIDATE `contracts/PolicyVault.v0.7-root.sil`
//! (contract `PolicyVaultOrgRoot`, generated by `tools/gen_v7_root.js`)
//! driven through the real TxScriptEngine (covenants enabled, real Schnorr).
//!
//! Gate I1 of docs/postlaunch/v0.7-organizational-root-design.md section 11.1:
//! the honest organizational lifecycle, EVERY root-side hostile row of
//! sections 7.8 and 10.8 ported onto the PRODUCTION bytes, the coordinator's
//! D6 rows, the threshold sweep with its one-signature-short refusals, the
//! production-byte encoder integration, and measurement + standardness +
//! MAX_STACK_SIZE headroom.
//!
//! The frozen `PolicyVault.v0.5.sil` / `PolicyVault.v0.6.sil` and the phase-1
//! and phase-2 probe files are never read for anything but the record: this
//! suite compiles the PRODUCTION candidate only.
//!
//! Relative-age note: `this.age >= D` compiles to OpCheckSequenceVerify, which
//! this harness DOES execute (sequence-vs-D and the disabled bit). The
//! CONSENSUS-level UTXO-age rule `check_sequence_lock`
//! (utxo.block_daa_score + sequence - 1 < pov_daa_score) is NOT executed by a
//! script engine and is proven live on testnet-10 at gate I5, not here.

use std::sync::OnceLock;

use secp256k1::Keypair;
use silverscript_lang::ast::Expr;
use silverscript_lang::compiler::{compile_contract, struct_object, CompileOptions, CompiledContract, CovenantDeclCallOptions};

use kaspa_consensus_core::constants::STORAGE_MASS_PARAMETER;
use kaspa_consensus_core::hashing::sighash::{calc_schnorr_signature_hash, SigHashReusedValuesUnsync};
use kaspa_consensus_core::hashing::sighash_type::{SigHashType, SIG_HASH_ALL, SIG_HASH_ANY_ONE_CAN_PAY, SIG_HASH_NONE, SIG_HASH_SINGLE};
use kaspa_consensus_core::mass::units::{ComputeBudget, ScriptUnits};
use kaspa_consensus_core::mass::{transaction_estimated_serialized_size, MassCalculator};
use kaspa_consensus_core::subnets::SubnetworkId;
use kaspa_consensus_core::tx::{
    ComputeCommit, CovenantBinding, MutableTransaction, PopulatedTransaction, Transaction, TransactionId, TransactionInput,
    TransactionOutpoint, TransactionOutput, UtxoEntry,
};
use kaspa_consensus_core::Hash;
use kaspa_txscript::script_class::ScriptClass;
use kaspa_txscript::{pay_to_script_hash_script, post_toccata_p2sh_sig_scanner, script_builder::ScriptBuilder, EngineFlags};
use kaspa_txscript_errors::TxScriptError;
use policyvault_vm_tests::{execute_input_measured, execute_input_measured_priced};

/* ================================================================== */
/* constants                                                           */
/* ================================================================== */

const N_SLOTS: usize = 12;
const SIG_BLOB_LEN: usize = N_SLOTS * 65; // 780

/// The fixed-width state TAIL of the production root: `byte frozen` (2 B) +
/// `byte[8] rootNonce` (9 B). Asserted against the compiler's own layout.
const ROOT_TAIL_LEN: usize = 11;
/// 33 (byte[32] boundOrgId) + 12*33 (pubkey) + 3*9 (int) + 2 + 9.
const ROOT_STATE_LEN: usize = 33 + N_SLOTS * 33 + 3 * 9 + 2 + 9; // 467
/// 12 counting sig-ops at ONE call site + 1 succession = 13, budget 15.
const ROOT_STATIC_SIG_OPS: u64 = 13;
/// rusty-kaspa mining/src/mempool/check_transaction_standard.rs.
const MAX_STANDARD_P2SH_SIG_OPS: u64 = 15;

const COV_ROOT: Hash = Hash::from_bytes(*b"ROOTROOTROOTROOTROOTROOTROOTROOT");

const ZERO32: [u8; 32] = [0u8; 32];
const ORG_ID: [u8; 32] = [0xa7u8; 32];
const ORG_ID_B: [u8; 32] = [0xb7u8; 32];

const KAS: i64 = 100_000_000;
const ROOT_KAS: i64 = 3 * KAS;
const ROOT_MAX_FEE: i64 = 200_000;
const ROOT_FEE_PAID: i64 = 50_000;
const RECOVERY_DELAY: i64 = 1_000;
const SUCCESSION_DELAY: i64 = 2_000;

/* owner key seeds (deterministic, TEST-ONLY) */
const OWNER_SEEDS: [u8; N_SLOTS] = [0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c];
const SUCCESSOR_SEED: u8 = 0x7f;
const OUTSIDER_SEED: u8 = 0x6f;

/* ================================================================== */
/* helpers                                                             */
/* ================================================================== */

fn kp(seed: u8) -> Keypair {
    let secp = secp256k1::Secp256k1::new();
    let sk = secp256k1::SecretKey::from_slice(&[seed; 32]).expect("seed key");
    Keypair::from_secret_key(&secp, &sk)
}
fn xonly32(k: &Keypair) -> [u8; 32] {
    k.x_only_public_key().0.serialize()
}
fn hx(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}
fn num8(v: i64) -> [u8; 8] {
    (v as u64).to_le_bytes()
}
fn leak(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}
fn load(rel: &str) -> String {
    let path = format!("{}/{rel}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"))
}
/// THE PRODUCTION CANDIDATE — nothing else is compiled by this suite.
fn src_root() -> &'static str {
    static S: OnceLock<&'static str> = OnceLock::new();
    S.get_or_init(|| leak(load("../../contracts/PolicyVault.v0.7-root.sil")))
}

#[derive(Clone)]
struct Template {
    prefix: Vec<u8>,
    state_len: usize,
    suffix: Vec<u8>,
    hash: [u8; 32],
}
fn template_of(c: &CompiledContract<'_>) -> Template {
    let l = c.state_layout;
    let prefix = c.script[..l.start].to_vec();
    let suffix = c.script[l.start + l.len..].to_vec();
    let h = blake2b_simd::Params::new().hash_length(32).to_state().update(&prefix).update(&suffix).finalize();
    let mut hash = [0u8; 32];
    hash.copy_from_slice(h.as_bytes());
    Template { prefix, state_len: l.len, suffix, hash }
}

fn push_redeem(script: &[u8]) -> Vec<u8> {
    ScriptBuilder::with_flags(EngineFlags { covenants_enabled: true, ..Default::default() }).add_data(script).unwrap().drain()
}
fn cov_call(c: &CompiledContract<'_>, f: &str, args: Vec<Expr<'_>>) -> Vec<u8> {
    let mut s = c
        .build_sig_script_for_covenant_decl(f, args, CovenantDeclCallOptions { is_leader: false })
        .unwrap_or_else(|e| panic!("call {f}: {e:?}"));
    s.extend_from_slice(&push_redeem(&c.script));
    s
}
fn tx_input(id: u8, sigscript: Vec<u8>, sequence: u64, budget: u16) -> TransactionInput {
    TransactionInput::new_with_mass(
        TransactionOutpoint { transaction_id: TransactionId::from_bytes([id; 32]), index: 0 },
        sigscript,
        sequence,
        ComputeCommit::ComputeBudget(ComputeBudget(budget)),
    )
}
fn cov_out(value: i64, c: &CompiledContract<'_>, auth: u16, covid: Hash) -> TransactionOutput {
    TransactionOutput {
        value: value as u64,
        script_public_key: pay_to_script_hash_script(&c.script),
        covenant: Some(CovenantBinding { authorizing_input: auth, covenant_id: covid }),
    }
}
fn cov_utxo(value: i64, c: &CompiledContract<'_>, covid: Hash) -> UtxoEntry {
    UtxoEntry::new(value as u64, pay_to_script_hash_script(&c.script), 0, false, Some(covid))
}
fn build_tx(inputs: Vec<TransactionInput>, outputs: Vec<TransactionOutput>) -> Transaction {
    Transaction::new(1, inputs, outputs, 0, SubnetworkId::default(), 0, vec![])
}
fn sign_type(tx: &Transaction, entries: &[UtxoEntry], idx: usize, k: &Keypair, ht: SigHashType) -> Vec<u8> {
    let m = MutableTransaction::with_entries(tx.clone(), entries.to_vec());
    let reused = SigHashReusedValuesUnsync::new();
    let h = calc_schnorr_signature_hash(&m.as_verifiable(), idx, ht, &reused);
    let msg = secp256k1::Message::from_digest_slice(h.as_bytes().as_slice()).unwrap();
    let mut out = k.sign_schnorr(msg).as_ref().to_vec();
    out.push(ht.to_u8());
    out
}
/// The canonical abstaining slot: 64 zero bytes + the SIGHASH_ALL gate byte.
/// It passes the 0x01 gate and FAILS verification, so it counts 0.
fn placeholder_slot() -> Vec<u8> {
    let mut v = vec![0u8; 64];
    v.push(0x01);
    v
}

/* ================================================================== */
/* the production root covenant                                        */
/* ================================================================== */

#[derive(Clone, PartialEq, Debug)]
struct RootState {
    org_id: [u8; 32],
    owners: [[u8; 32]; N_SLOTS],
    owner_m: i64,
    emergency_k: i64,
    recovery_m: i64,
    frozen: i64,
    nonce: i64,
}
impl RootState {
    /// Active slots 0..n filled from OWNER_SEEDS, the rest sentinel-zero.
    fn with(n: usize, m: i64, k: i64, r: i64) -> RootState {
        let mut owners = [ZERO32; N_SLOTS];
        for (i, o) in owners.iter_mut().enumerate().take(n) {
            *o = xonly32(&kp(OWNER_SEEDS[i]));
        }
        RootState { org_id: ORG_ID, owners, owner_m: m, emergency_k: k, recovery_m: r, frozen: 0, nonce: 0 }
    }
    fn advanced(&self) -> RootState {
        RootState { nonce: self.nonce + 1, ..self.clone() }
    }
}

#[derive(Clone)]
struct RootTemplate {
    recovery_delay: i64,
    successor_pk: [u8; 32],
    succession_delay: i64,
    max_fee: i64,
}
impl Default for RootTemplate {
    fn default() -> Self {
        RootTemplate {
            recovery_delay: RECOVERY_DELAY,
            successor_pk: xonly32(&kp(SUCCESSOR_SEED)),
            succession_delay: SUCCESSION_DELAY,
            max_fee: ROOT_MAX_FEE,
        }
    }
}

/// Exact-live-state compilation: the state values ARE constructor arguments in
/// this covenant, so no source templating is needed.
fn compile_root(s: &RootState, t: &RootTemplate) -> CompiledContract<'static> {
    let mut args: Vec<Expr<'static>> = vec![Expr::bytes(s.org_id.to_vec())];
    for o in s.owners.iter() {
        args.push(Expr::bytes(o.to_vec()));
    }
    for v in [s.owner_m, s.emergency_k, s.recovery_m] {
        args.push(Expr::int(v));
    }
    args.push(Expr::byte(s.frozen as u8));
    args.push(Expr::bytes(num8(s.nonce).to_vec()));
    args.push(Expr::int(t.recovery_delay));
    args.push(Expr::bytes(t.successor_pk.to_vec()));
    args.push(Expr::int(t.succession_delay));
    args.push(Expr::int(t.max_fee));
    compile_contract(src_root(), &args, CompileOptions::default()).unwrap_or_else(|e| panic!("compile production root: {e:?}"))
}

const ROOT_SLOT_NAMES: [&str; N_SLOTS] =
    ["owner1", "owner2", "owner3", "owner4", "owner5", "owner6", "owner7", "owner8", "owner9", "owner10", "owner11", "owner12"];

fn root_state_arg(s: &RootState) -> Expr<'static> {
    let mut f: Vec<(&'static str, Expr<'static>)> = vec![("boundOrgId", Expr::bytes(s.org_id.to_vec()))];
    for (i, n) in ROOT_SLOT_NAMES.iter().enumerate() {
        f.push((n, Expr::bytes(s.owners[i].to_vec())));
    }
    f.push(("ownerM", Expr::int(s.owner_m)));
    f.push(("emergencyK", Expr::int(s.emergency_k)));
    f.push(("recoveryM", Expr::int(s.recovery_m)));
    f.push(("frozen", Expr::byte(s.frozen as u8)));
    f.push(("rootNonce", Expr::bytes(num8(s.nonce).to_vec())));
    struct_object(f)
}

/* ---------------- root-only transactions ---------------- */

#[derive(Clone)]
struct RootCase {
    prev: RootState,
    new: RootState,
    tmpl: RootTemplate,
    /// successor compiled against a DIFFERENT template (covenant substitution)
    next_tmpl: Option<RootTemplate>,
    action: i64,
    /// slot indices that sign with their OWN key
    signers: Vec<usize>,
    /// slot index -> foreign key seed used to sign that slot
    forged: Vec<(usize, u8)>,
    /// copy the signature produced for slot .0 into slot .1 as well
    dup_slot: Option<(usize, usize)>,
    /// override the trailing sighash-type byte of one slot
    slot_type_byte: Option<(usize, u8)>,
    /// override the whole blob length
    blob_len: Option<usize>,
    sequence: u64,
    hash_type: SigHashType,
    succ_value: Option<i64>,
    /// use rootSuccession instead of rootAction; value = signing key seed
    succession: Option<u8>,
    post_sign_mutate: bool,
    budget: u16,
    /// extra data pushes at the FRONT of the sigscript (stack-headroom probe)
    stack_pad: usize,
}
impl RootCase {
    fn authorize(prev: RootState, signers: &[usize]) -> RootCase {
        let new = prev.advanced();
        RootCase {
            prev,
            new,
            tmpl: RootTemplate::default(),
            next_tmpl: None,
            action: 0,
            signers: signers.to_vec(),
            forged: vec![],
            dup_slot: None,
            slot_type_byte: None,
            blob_len: None,
            sequence: 0,
            hash_type: SIG_HASH_ALL,
            succ_value: None,
            succession: None,
            post_sign_mutate: false,
            budget: 400,
            stack_pad: 0,
        }
    }
    /// A well-formed OWNER-RECOVER: the recovery quorum installs a smaller set
    /// past the idle delay, and (decision D6) it LANDS FROZEN.
    fn recover(prev: RootState, signers: &[usize]) -> RootCase {
        let mut c = RootCase::authorize(prev.clone(), signers);
        c.action = 4;
        c.sequence = RECOVERY_DELAY as u64;
        let mut n = prev.advanced();
        n.owners[2] = ZERO32;
        n.owners[3] = ZERO32;
        n.owner_m = 2;
        n.recovery_m = 2;
        n.frozen = 1; // D6
        c.new = n;
        c
    }
    /// A well-formed SUCCESSION: the pinned key installs a new set past the
    /// idle delay, landing FROZEN and changing the primary key (D1).
    fn succeed(prev: RootState, seed: u8) -> RootCase {
        let mut c = RootCase::authorize(prev.clone(), &[]);
        c.succession = Some(seed);
        c.sequence = SUCCESSION_DELAY as u64;
        let mut n = prev.advanced();
        n.owners[0] = xonly32(&kp(0x91));
        n.frozen = 1;
        c.new = n;
        c
    }
}

struct RootOutcome {
    result: Result<(), TxScriptError>,
    units: u64,
    tx: Transaction,
    entries: Vec<UtxoEntry>,
    redeem_len: usize,
    sigscript_len: usize,
}

fn owner_blob(tx: &Transaction, entries: &[UtxoEntry], idx: usize, c: &RootCase) -> Vec<u8> {
    let mut slots: Vec<Vec<u8>> = (0..N_SLOTS).map(|_| placeholder_slot()).collect();
    for i in c.signers.iter() {
        slots[*i] = sign_type(tx, entries, idx, &kp(OWNER_SEEDS[*i]), c.hash_type);
    }
    for (slot, seed) in c.forged.iter() {
        slots[*slot] = sign_type(tx, entries, idx, &kp(*seed), c.hash_type);
    }
    if let Some((from, to)) = c.dup_slot {
        slots[to] = slots[from].clone();
    }
    if let Some((slot, byte)) = c.slot_type_byte {
        let last = slots[slot].len() - 1;
        slots[slot][last] = byte;
    }
    let mut blob: Vec<u8> = slots.into_iter().flatten().collect();
    assert_eq!(blob.len(), SIG_BLOB_LEN);
    if let Some(n) = c.blob_len {
        blob.resize(n, 0u8);
    }
    blob
}

fn run_root(c: &RootCase) -> RootOutcome {
    let prev_c = compile_root(&c.prev, &c.tmpl);
    let next_c = compile_root(&c.new, c.next_tmpl.as_ref().unwrap_or(&c.tmpl));
    let entries = vec![cov_utxo(ROOT_KAS, &prev_c, COV_ROOT)];
    let succ_value = c.succ_value.unwrap_or(ROOT_KAS - ROOT_FEE_PAID);
    let outputs = vec![cov_out(succ_value, &next_c, 0, COV_ROOT)];

    let unsigned = build_tx(vec![tx_input(1, vec![], c.sequence, c.budget)], outputs.clone());
    let sigscript = match c.succession {
        Some(seed) => {
            let mut s = sign_type(&unsigned, &entries, 0, &kp(seed), c.hash_type);
            if let Some((_, byte)) = c.slot_type_byte {
                let last = s.len() - 1;
                s[last] = byte;
            }
            cov_call(&prev_c, "rootSuccession", vec![root_state_arg(&c.new), Expr::bytes(s)])
        }
        None => {
            let blob = owner_blob(&unsigned, &entries, 0, c);
            cov_call(&prev_c, "rootAction", vec![root_state_arg(&c.new), Expr::int(c.action), Expr::bytes(blob)])
        }
    };
    let sigscript = if c.stack_pad > 0 {
        let mut pad = ScriptBuilder::new();
        for _ in 0..c.stack_pad {
            pad.add_data(&[0x01u8]).unwrap();
        }
        let mut padded = pad.drain();
        padded.extend_from_slice(&sigscript);
        padded
    } else {
        sigscript
    };
    let mut final_outputs = outputs;
    if c.post_sign_mutate {
        final_outputs[0].value -= 1;
    }
    let sigscript_len = sigscript.len();
    let tx = build_tx(vec![tx_input(1, sigscript, c.sequence, c.budget)], final_outputs);
    let (result, units) = execute_input_measured(tx.clone(), entries.clone(), 0);
    RootOutcome { result, units, tx, entries, redeem_len: prev_c.script.len(), sigscript_len }
}

fn accept_root(label: &str, c: &RootCase) -> RootOutcome {
    let o = run_root(c);
    o.result.as_ref().unwrap_or_else(|e| panic!("{label}: the root must ACCEPT this honest case: {e:?}"));
    o
}
fn refuse_root(label: &str, c: &RootCase) -> String {
    let o = run_root(c);
    match o.result {
        Ok(()) => panic!("{label}: the root ACCEPTED a case that must be refused"),
        Err(e) => format!("{e:?}"),
    }
}

/* ================================================================== */
/* state layout (section 9.1) on the PRODUCTION bytes                  */
/* ================================================================== */

#[test]
fn v7root_state_layout_is_fixed_width() {
    // The state region length must be identical for every reachable state,
    // otherwise a rooted vault cannot slice HEAD and TAIL by fixed offsets.
    let states = [
        RootState::with(1, 1, 1, 0),
        RootState::with(12, 12, 1, 6),
        RootState { frozen: 1, nonce: 1, ..RootState::with(7, 4, 2, 3) },
        RootState { nonce: i64::from(u32::MAX), ..RootState::with(3, 2, 1, 2) },
    ];
    let mut lens = vec![];
    for s in states.iter() {
        let c = compile_root(s, &RootTemplate::default());
        let t = template_of(&c);
        lens.push(t.state_len);
        let state = &c.script[c.state_layout.start..c.state_layout.start + c.state_layout.len];
        let tail = &state[state.len() - ROOT_TAIL_LEN..];
        let mut expect = vec![0x01u8, s.frozen as u8, 0x08u8];
        expect.extend_from_slice(&num8(s.nonce));
        assert_eq!(tail, &expect[..], "root TAIL bytes must be 0x01||frozen||0x08||nonce8 for {s:?}");
    }
    assert!(lens.windows(2).all(|w| w[0] == w[1]), "root state region length must be CONSTANT, got {lens:?}");
    assert_eq!(lens[0], ROOT_STATE_LEN, "measured rootStateLen");

    let c = compile_root(&RootState::with(12, 12, 1, 6), &RootTemplate::default());
    let t = template_of(&c);
    println!(
        "[layout] rootStateLen {} B (33 + 12x33 + 3x9 + 2 + 9) | TAIL_LEN {} B | head {} B | prefix {} B | suffix {} B | redeem {} B",
        t.state_len,
        ROOT_TAIL_LEN,
        t.state_len - ROOT_TAIL_LEN,
        t.prefix.len(),
        t.suffix.len(),
        c.script.len()
    );
    // The template identity a rooted vault pins at genesis. It must be
    // independent of the live state, so every state above must produce it.
    println!("[layout] rootTemplateVmHash blake2b-256(prefix || suffix) = {}", hx(&t.hash));
    for s in states.iter() {
        assert_eq!(template_of(&compile_root(s, &RootTemplate::default())).hash, t.hash, "the root template identity must not depend on the live state");
    }
}

/* ================================================================== */
/* honest organizational lifecycle                                     */
/* ================================================================== */

#[test]
fn v7root_honest_authorize_2_of_3() {
    let o = accept_root("AUTHORIZE 2-of-3", &RootCase::authorize(RootState::with(3, 2, 1, 2), &[0, 1]));
    println!("ROOT AUTHORIZE 2-of-3: units {} | redeem {} B | sigscript {} B", o.units, o.redeem_len, o.sigscript_len);
}

#[test]
fn v7root_honest_authorize_12_of_12() {
    let all: Vec<usize> = (0..12).collect();
    let o = accept_root("AUTHORIZE 12-of-12", &RootCase::authorize(RootState::with(12, 12, 1, 6), &all));
    println!("ROOT AUTHORIZE 12-of-12: units {} | redeem {} B | sigscript {} B", o.units, o.redeem_len, o.sigscript_len);
}

#[test]
fn v7root_honest_rotate_full_quorum() {
    let prev = RootState::with(3, 2, 1, 2);
    let mut c = RootCase::authorize(prev.clone(), &[0, 1]);
    c.action = 1;
    let mut new = prev.advanced();
    new.owners[2] = xonly32(&kp(0x81));
    new.owners[3] = xonly32(&kp(0x82));
    new.owner_m = 3;
    c.new = new;
    accept_root("ROTATE (full quorum)", &c);
}

#[test]
fn v7root_honest_rotate_is_allowed_while_frozen() {
    // Compromised keys must be rotatable BEFORE the organization unfreezes.
    let prev = RootState { frozen: 1, ..RootState::with(3, 2, 1, 2) };
    let mut c = RootCase::authorize(prev.clone(), &[0, 1]);
    c.action = 1;
    let mut new = prev.advanced();
    new.owners[2] = xonly32(&kp(0x81));
    c.new = new;
    accept_root("ROTATE while frozen (full quorum)", &c);
}

#[test]
fn v7root_honest_freeze_by_emergency_k_1() {
    let prev = RootState::with(3, 3, 1, 2);
    let mut c = RootCase::authorize(prev.clone(), &[1]); // ONE owner, K = 1
    c.action = 2;
    c.new = RootState { frozen: 1, ..prev.advanced() };
    accept_root("FREEZE by emergency quorum K=1", &c);
}

#[test]
fn v7root_honest_unfreeze_full_quorum() {
    let prev = RootState { frozen: 1, ..RootState::with(3, 2, 1, 2) };
    let mut c = RootCase::authorize(prev.clone(), &[0, 1]);
    c.action = 3;
    c.new = RootState { frozen: 0, ..prev.advanced() };
    accept_root("UNFREEZE (full quorum)", &c);
}

#[test]
fn v7root_honest_owner_recover_lands_frozen_after_idle_delay() {
    // DECISION D6: action 4 must land frozen = 1. The recovery quorum (2 of a
    // 4-owner set, ownerM = 4) installs a smaller set past the idle delay.
    let o = accept_root(
        "OWNER-RECOVER (recovery quorum + idle age, landing FROZEN)",
        &RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1]),
    );
    println!("ROOT OWNER-RECOVER (D6, lands frozen): units {}", o.units);
}

#[test]
fn v7root_honest_succession_after_idle_delay() {
    let prev = RootState::with(3, 2, 1, 0);
    let mut c = RootCase::succeed(prev.clone(), SUCCESSOR_SEED);
    let mut new = prev.advanced();
    new.owners[0] = xonly32(&kp(0x91));
    new.owners[1] = xonly32(&kp(0x92));
    new.owners[2] = ZERO32;
    new.owner_m = 2;
    new.emergency_k = 1;
    new.recovery_m = 0;
    new.frozen = 1; // the installed set lands FROZEN by rule
    c.new = new;
    accept_root("SUCCESSION (pinned key + idle age)", &c);
}

#[test]
fn v7root_honest_nonce_rolls_over_multi_byte_boundaries() {
    // The byte[8] nonce advances as OpNum2Bin(prev + 1, 8): exercise the
    // carries a rooted vault has to reproduce byte-exactly.
    for start in [0i64, 254, 255, 65_534, 65_535, 16_777_215, i64::from(u32::MAX), 1 << 40] {
        let prev = RootState { nonce: start, ..RootState::with(3, 2, 1, 2) };
        accept_root(&format!("AUTHORIZE with nonce {start} -> {}", start + 1), &RootCase::authorize(prev, &[0, 1]));
    }
}

#[test]
fn v7root_honest_full_lifecycle_in_sequence() {
    // genesis-like state -> AUTHORIZE -> FREEZE -> ROTATE (while frozen) ->
    // UNFREEZE -> AUTHORIZE, each transition starting from the previous
    // successor state, so the nonce and the freeze flag are carried honestly.
    let mut s = RootState::with(4, 3, 1, 2);
    accept_root("lifecycle: AUTHORIZE", &RootCase::authorize(s.clone(), &[0, 1, 2]));
    s = s.advanced();

    let mut freeze = RootCase::authorize(s.clone(), &[3]);
    freeze.action = 2;
    freeze.new = RootState { frozen: 1, ..s.advanced() };
    accept_root("lifecycle: FREEZE (K=1)", &freeze);
    s = RootState { frozen: 1, ..s.advanced() };

    let mut rotate = RootCase::authorize(s.clone(), &[0, 1, 2]);
    rotate.action = 1;
    let mut rotated = s.advanced();
    rotated.owners[3] = xonly32(&kp(0x81));
    rotate.new = rotated.clone();
    accept_root("lifecycle: ROTATE while frozen", &rotate);
    s = rotated;

    let mut unfreeze = RootCase::authorize(s.clone(), &[0, 1, 2]);
    unfreeze.action = 3;
    unfreeze.new = RootState { frozen: 0, ..s.advanced() };
    accept_root("lifecycle: UNFREEZE", &unfreeze);
    s = RootState { frozen: 0, ..s.advanced() };

    accept_root("lifecycle: AUTHORIZE after the unfreeze", &RootCase::authorize(s, &[0, 1, 2]));
}

#[test]
fn v7root_honest_threshold_sweep_1_of_1_through_12_of_12() {
    // Each M-of-M accepted; each M-1 of M separately REFUSED (11 rows).
    let mut short_refusals = 0;
    for n in 1..=N_SLOTS {
        let prev = RootState::with(n, n as i64, 1, 0);
        let signers: Vec<usize> = (0..n).collect();
        accept_root(&format!("AUTHORIZE {n}-of-{n}"), &RootCase::authorize(prev.clone(), &signers));
        if n > 1 {
            let short: Vec<usize> = (0..n - 1).collect();
            refuse_root(&format!("AUTHORIZE {}-of-{n} (one short)", n - 1), &RootCase::authorize(prev, &short));
            short_refusals += 1;
        }
    }
    assert_eq!(short_refusals, 11, "the threshold sweep must contribute 11 one-signature-short refusals");
}

/* ================================================================== */
/* D6 — OWNER-RECOVER MUST LAND FROZEN (coordinator decision, s. 11)   */
/* ================================================================== */

#[test]
fn v7root_d6_owner_recover_must_land_frozen() {
    // Honest: lands frozen -> ACCEPTED (also covered above; asserted here so
    // the D6 rule is proven in one place, both directions).
    accept_root("D6 honest: OWNER-RECOVER landing FROZEN", &RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1]));

    // Hostile: identical in every other respect, but landing UNFROZEN.
    let mut unfrozen = RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1]);
    unfrozen.new.frozen = 0;
    let err = refuse_root("D6: OWNER-RECOVER landing UNFROZEN", &unfrozen);
    println!("D6 OWNER-RECOVER landing unfrozen -> REFUSED: {err}");

    // Hostile: a recovery that leaves the HEAD unchanged (the section 10.7
    // observation) still lands frozen, so it can never be byte-identical to an
    // AUTHORIZE successor. Landing it unfrozen — which is what would make it
    // look like an AUTHORIZE — is refused.
    let prev = RootState::with(4, 4, 1, 2);
    let mut head_unchanged = RootCase::authorize(prev.clone(), &[0, 1]);
    head_unchanged.action = 4;
    head_unchanged.sequence = RECOVERY_DELAY as u64;
    head_unchanged.new = prev.advanced(); // head preserved, frozen = 0
    let err = refuse_root("D6: OWNER-RECOVER with an unchanged head, landing unfrozen", &head_unchanged);
    println!("D6 unchanged-head recovery can no longer imitate AUTHORIZE -> REFUSED: {err}");

    // The same transition WITH the frozen landing is well-formed and accepted:
    // it is now distinguishable only from a FREEZE, whose sole vault effect is
    // the AUTHORITY-REDUCING emergency pause.
    let mut head_unchanged_frozen = head_unchanged.clone();
    head_unchanged_frozen.new = RootState { frozen: 1, ..prev.advanced() };
    accept_root("D6: OWNER-RECOVER with an unchanged head, landing FROZEN", &head_unchanged_frozen);
}

/* ================================================================== */
/* hostile matrix — every root-side row of sections 7.8 and 10.8       */
/* ================================================================== */

fn root_hostile_rows() -> Vec<(&'static str, RootCase)> {
    let base = RootState::with(3, 2, 1, 2);
    let big = RootState::with(6, 4, 2, 3);
    let mut rows: Vec<(&'static str, RootCase)> = vec![];

    rows.push(("duplicate owner key in the rotated set", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        let mut n = base.advanced();
        n.owners[2] = n.owners[0];
        c.new = n;
        c
    }));
    rows.push(("duplicate owner key in the predecessor (malformed genesis)", {
        let mut prev = RootState::with(3, 2, 1, 2);
        prev.owners[2] = prev.owners[0];
        RootCase::authorize(prev, &[0, 1])
    }));
    rows.push(("one signature replayed into a second slot", {
        let mut c = RootCase::authorize(base.clone(), &[0]);
        c.dup_slot = Some((0, 1));
        c
    }));
    rows.push(("insufficient quorum (1 of 2 required)", RootCase::authorize(base.clone(), &[0])));
    rows.push(("outsider key in an owner slot", {
        let mut c = RootCase::authorize(base.clone(), &[0]);
        c.forged = vec![(1, OUTSIDER_SEED)];
        c
    }));
    rows.push(("removed owner signing a sentinel slot", {
        let mut prev = RootState::with(3, 2, 1, 2);
        prev.owners[2] = ZERO32;
        let mut c = RootCase::authorize(prev, &[0]);
        c.forged = vec![(2, OWNER_SEEDS[2])];
        c
    }));
    rows.push(("root nonce not advanced (replay)", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.new = base.clone();
        c
    }));
    rows.push(("root nonce advanced by two", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.new = RootState { nonce: base.nonce + 2, ..base.clone() };
        c
    }));
    rows.push(("root nonce moved BACKWARD", {
        let prev = RootState { nonce: 9, ..base.clone() };
        let mut c = RootCase::authorize(prev.clone(), &[0, 1]);
        c.new = RootState { nonce: 8, ..prev };
        c
    }));
    rows.push(("boundOrgId rewritten in the successor", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.new = RootState { org_id: ORG_ID_B, ..base.advanced() };
        c
    }));
    rows.push(("owner set changed under AUTHORIZE", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        let mut n = base.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        c.new = n;
        c
    }));
    rows.push(("threshold lowered under AUTHORIZE", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.new = RootState { owner_m: 1, ..base.advanced() };
        c
    }));
    rows.push(("rotation to ownerM above the active count", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        c.new = RootState { owner_m: 4, ..base.advanced() };
        c
    }));
    rows.push(("rotation to ownerM = 0", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        c.new = RootState { owner_m: 0, ..base.advanced() };
        c
    }));
    rows.push(("rotation to emergencyK above ownerM", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        c.new = RootState { emergency_k: 3, ..base.advanced() };
        c
    }));
    rows.push(("rotation to recoveryM above ownerM", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        c.new = RootState { recovery_m: 3, ..base.advanced() };
        c
    }));
    rows.push(("rotation leaving a hole in the active slots", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        let mut n = base.advanced();
        n.owners[1] = ZERO32; // slot 3 active, slot 2 inactive
        n.owner_m = 2;
        c.new = n;
        c
    }));
    rows.push(("rotation to an empty owner set", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        let mut n = base.advanced();
        n.owners = [ZERO32; N_SLOTS];
        n.owner_m = 1;
        c.new = n;
        c
    }));
    rows.push(("FREEZE quorum (K) used to ROTATE", {
        let mut c = RootCase::authorize(big.clone(), &[0, 1]); // K = 2, M = 4
        c.action = 1;
        let mut n = big.advanced();
        n.owners[5] = xonly32(&kp(0x81));
        c.new = n;
        c
    }));
    rows.push(("FREEZE quorum (K) used to UNFREEZE", {
        let frozen = RootState { frozen: 1, ..big.clone() };
        let mut c = RootCase::authorize(frozen.clone(), &[0, 1]);
        c.action = 3;
        c.new = RootState { frozen: 0, ..frozen.advanced() };
        c
    }));
    rows.push(("FREEZE quorum (K) used to OWNER-RECOVER", {
        // the lighter emergency quorum (K = 2) must not reach the recovery
        // path either: recoveryM = 3 and only 2 owners sign.
        RootCase::recover(RootState::with(4, 4, 2, 3), &[0, 1])
    }));
    rows.push(("FREEZE also changing the owner set", {
        let mut c = RootCase::authorize(base.clone(), &[0]);
        c.action = 2;
        let mut n = base.advanced();
        n.frozen = 1;
        n.owners[2] = xonly32(&kp(0x81));
        c.new = n;
        c
    }));
    rows.push(("FREEZE while already frozen", {
        let frozen = RootState { frozen: 1, ..base.clone() };
        let mut c = RootCase::authorize(frozen.clone(), &[0]);
        c.action = 2;
        c.new = RootState { frozen: 1, ..frozen.advanced() };
        c
    }));
    rows.push(("AUTHORIZE while frozen", {
        let frozen = RootState { frozen: 1, ..base.clone() };
        let mut c = RootCase::authorize(frozen.clone(), &[0, 1]);
        c.new = frozen.advanced();
        c
    }));
    rows.push(("unfreeze disguised as AUTHORIZE", {
        let frozen = RootState { frozen: 1, ..base.clone() };
        let mut c = RootCase::authorize(frozen.clone(), &[0, 1]);
        c.new = RootState { frozen: 0, ..frozen.advanced() };
        c
    }));
    rows.push(("OWNER-RECOVER before the idle delay", {
        let mut c = RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1]);
        c.sequence = (RECOVERY_DELAY - 1) as u64;
        c
    }));
    rows.push(("OWNER-RECOVER with the sequence disabled bit set", {
        let mut c = RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1]);
        c.sequence = (1u64 << 63) | RECOVERY_DELAY as u64;
        c
    }));
    rows.push(("OWNER-RECOVER when recovery is disabled (recoveryM = 0)", {
        let prev = RootState::with(4, 4, 1, 0);
        let mut c = RootCase::recover(prev.clone(), &[0, 1]);
        c.new = RootState { recovery_m: 0, ..c.new.clone() };
        c
    }));
    rows.push(("OWNER-RECOVER below the recovery quorum", {
        let mut c = RootCase::recover(RootState::with(4, 4, 1, 2), &[0]);
        c.new.owner_m = 1;
        c.new.recovery_m = 1;
        c
    }));
    rows.push(("OWNER-RECOVER landing UNFROZEN (decision D6)", {
        let mut c = RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1]);
        c.new.frozen = 0;
        c
    }));
    rows.push(("SUCCESSION before the idle delay", {
        let mut c = RootCase::succeed(base.clone(), SUCCESSOR_SEED);
        c.sequence = (SUCCESSION_DELAY - 1) as u64;
        c
    }));
    rows.push(("SUCCESSION signed by a non-successor key", RootCase::succeed(base.clone(), OUTSIDER_SEED)));
    rows.push(("SUCCESSION landing UNFROZEN", {
        let mut c = RootCase::succeed(base.clone(), SUCCESSOR_SEED);
        c.new.frozen = 0;
        c
    }));
    rows.push(("SUCCESSION re-installing the same primary key (deviation D1)", {
        let mut c = RootCase::succeed(base.clone(), SUCCESSOR_SEED);
        c.new.owners[0] = base.owners[0];
        c
    }));
    rows.push(("SUCCESSION when the successor key is disabled (zero)", {
        let mut c = RootCase::succeed(base.clone(), SUCCESSOR_SEED);
        c.tmpl = RootTemplate { successor_pk: ZERO32, ..RootTemplate::default() };
        c
    }));
    for (label, ht) in [
        ("owner slots signed with SIGHASH_NONE", SIG_HASH_NONE),
        ("owner slots signed with SIGHASH_SINGLE", SIG_HASH_SINGLE),
    ] {
        rows.push((label, {
            let mut c = RootCase::authorize(base.clone(), &[0, 1]);
            c.hash_type = ht;
            c
        }));
    }
    rows.push(("owner slots signed with SIGHASH_ALL|ANYONECANPAY", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.hash_type = SigHashType::from_u8(SIG_HASH_ALL.to_u8() | SIG_HASH_ANY_ONE_CAN_PAY.to_u8()).expect("allowed type");
        c
    }));
    rows.push(("owner slot with a forged 0x01 gate byte over a SIGHASH_NONE signature", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.hash_type = SIG_HASH_NONE;
        c.slot_type_byte = Some((0, 0x01));
        c
    }));
    rows.push(("succession signature with a forged 0x01 gate byte over SIGHASH_NONE", {
        let mut c = RootCase::succeed(base.clone(), SUCCESSOR_SEED);
        c.hash_type = SIG_HASH_NONE;
        c.slot_type_byte = Some((0, 0x01));
        c
    }));
    rows.push(("successor output mutated after the owners signed", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.post_sign_mutate = true;
        c
    }));
    rows.push(("owner signature blob too short", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.blob_len = Some(SIG_BLOB_LEN - 1);
        c
    }));
    rows.push(("owner signature blob too long", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.blob_len = Some(SIG_BLOB_LEN + 65);
        c
    }));
    rows.push(("action out of range (5)", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 5;
        c
    }));
    rows.push(("negative action", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = -1;
        c
    }));
    rows.push(("root value drained beyond rootMaxFeePerTx", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.succ_value = Some(ROOT_KAS - ROOT_MAX_FEE - 1);
        c
    }));
    rows.push(("successor compiled against a different root template", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.next_tmpl = Some(RootTemplate { recovery_delay: RECOVERY_DELAY + 1, ..RootTemplate::default() });
        c
    }));
    /* the retyped tail's own domain (deviation D8) */
    rows.push(("non-canonical frozen byte in the predecessor (0x02)", {
        let mut prev = RootState::with(3, 2, 1, 2);
        prev.frozen = 2;
        RootCase::authorize(prev, &[0, 1])
    }));
    rows.push(("non-canonical frozen byte in the successor (0x02, under ROTATE)", {
        let mut c = RootCase::authorize(base.clone(), &[0, 1]);
        c.action = 1;
        let mut n = base.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        n.frozen = 2;
        c.new = n;
        c
    }));
    rows.push(("negative-zero frozen byte (0x80) in the predecessor", {
        let mut prev = RootState::with(3, 2, 1, 2);
        prev.frozen = 0x80;
        RootCase::authorize(prev, &[0, 1])
    }));
    rows
}

#[test]
fn v7root_hostile_matrix_all_refused() {
    let rows = root_hostile_rows();
    println!("ROOT HOSTILE MATRIX ON PRODUCTION BYTES ({} rows)", rows.len());
    for (label, case) in rows.iter() {
        let err = refuse_root(label, case);
        println!("  REFUSED  {label}\n           -> {err}");
    }
    // 47 ported rows (sections 7.8 + 10.8) + the D6 row + two new rows the
    // production candidate adds (emergency quorum reaching OWNER-RECOVER, and
    // a forged gate byte on the succession signature).
    assert!(rows.len() >= 48, "every root-side row of 7.8/10.8 plus D6 must be present (got {})", rows.len());
}

/* ================================================================== */
/* PRODUCTION-BYTE integration: the real pv_call_encoder BINARY        */
/* ================================================================== */

/// Encode a root call with the REAL `pv_call_encoder` binary (the exact tool
/// the SDK shells out to) and drive its bytes through the engine. This is the
/// production-byte rule: never only the in-process encoder, which is the blind
/// spot that shipped the v0.2 boundVaultId defect.
mod encoder {
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn encoder_path() -> PathBuf {
        PathBuf::from(format!("{}/target/debug/pv_call_encoder", env!("CARGO_MANIFEST_DIR")))
    }

    fn tmp_dir() -> PathBuf {
        let unique = format!("{}-{}", std::process::id(), SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos());
        let dir = std::env::temp_dir().join(format!("pv-v7root-{unique}"));
        std::fs::create_dir_all(&dir).expect("tmp dir");
        dir
    }

    fn bytes_arg(b: &[u8]) -> serde_json::Value {
        serde_json::json!({"kind": "array", "data": b.iter().map(|x| serde_json::json!({"kind": "byte", "data": x})).collect::<Vec<_>>()})
    }
    fn int_arg(v: i64) -> serde_json::Value {
        serde_json::json!({"kind": "int", "data": v})
    }
    fn byte_arg(v: u8) -> serde_json::Value {
        serde_json::json!({"kind": "byte", "data": v})
    }

    fn ctor_args(s: &RootState, t: &RootTemplate) -> serde_json::Value {
        let mut a = vec![bytes_arg(&s.org_id)];
        for o in s.owners.iter() {
            a.push(bytes_arg(o));
        }
        a.push(int_arg(s.owner_m));
        a.push(int_arg(s.emergency_k));
        a.push(int_arg(s.recovery_m));
        a.push(byte_arg(s.frozen as u8));
        a.push(bytes_arg(&num8(s.nonce)));
        a.push(int_arg(t.recovery_delay));
        a.push(bytes_arg(&t.successor_pk));
        a.push(int_arg(t.succession_delay));
        a.push(int_arg(t.max_fee));
        serde_json::Value::Array(a)
    }

    fn successor_json(s: &RootState) -> serde_json::Value {
        let mut m = serde_json::Map::new();
        for (i, n) in ROOT_SLOT_NAMES.iter().enumerate() {
            m.insert((*n).to_string(), serde_json::Value::String(hx(&s.owners[i])));
        }
        m.insert("ownerM".into(), serde_json::json!(s.owner_m));
        m.insert("emergencyK".into(), serde_json::json!(s.emergency_k));
        m.insert("recoveryM".into(), serde_json::json!(s.recovery_m));
        m.insert("frozen".into(), serde_json::json!(s.frozen));
        m.insert("rootNonce".into(), serde_json::json!(s.nonce));
        serde_json::Value::Object(m)
    }

    /// Run the binary; `Ok(hex)` on success, `Err(stderr)` when it fails closed.
    fn run(prev: &RootState, tmpl: &RootTemplate, call: serde_json::Value) -> Result<String, String> {
        let dir = tmp_dir();
        let src = dir.join("root.sil");
        std::fs::write(&src, src_root()).unwrap();
        let args = dir.join("ctor.json");
        std::fs::write(&args, serde_json::to_string(&ctor_args(prev, tmpl)).unwrap()).unwrap();
        let cj = dir.join("call.json");
        std::fs::write(&cj, serde_json::to_string(&call).unwrap()).unwrap();
        let out = Command::new(encoder_path()).arg(&src).arg(&args).arg(&cj).output().expect("run pv_call_encoder");
        let _ = std::fs::remove_dir_all(&dir);
        if out.status.success() {
            Ok(String::from_utf8(out.stdout).unwrap().trim().to_string())
        } else {
            Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
        }
    }

    fn unhex(s: &str) -> Vec<u8> {
        (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
    }

    /// Build a root-only transaction whose sigscript is the BINARY's output.
    fn execute_with_encoder(c: &RootCase, mut call: serde_json::Value) -> Result<(), TxScriptError> {
        let prev_c = compile_root(&c.prev, &c.tmpl);
        let next_c = compile_root(&c.new, &c.tmpl);
        let entries = vec![cov_utxo(ROOT_KAS, &prev_c, COV_ROOT)];
        let outputs = vec![cov_out(ROOT_KAS - ROOT_FEE_PAID, &next_c, 0, COV_ROOT)];
        let unsigned = build_tx(vec![tx_input(1, vec![], c.sequence, c.budget)], outputs.clone());
        match c.succession {
            Some(seed) => {
                let s = sign_type(&unsigned, &entries, 0, &kp(seed), c.hash_type);
                call["successorSig"] = serde_json::Value::String(hx(&s));
            }
            None => {
                let blob = owner_blob(&unsigned, &entries, 0, c);
                call["ownerSigs"] = serde_json::Value::String(hx(&blob));
            }
        }
        let encoded = run(&c.prev, &c.tmpl, call).expect("the encoder must succeed for an honest call");
        let mut sigscript = unhex(&encoded);
        sigscript.extend_from_slice(&push_redeem(&prev_c.script));
        let tx = build_tx(vec![tx_input(1, sigscript, c.sequence, c.budget)], outputs);
        execute_input_measured(tx, entries, 0).0
    }

    #[test]
    fn v7root_encoder_production_bytes_accepted_by_the_engine() {
        assert!(encoder_path().exists(), "build it first: cd tests/vm && cargo build --bin pv_call_encoder");

        for (label, case) in [
            ("rootAction AUTHORIZE 2-of-3", RootCase::authorize(RootState::with(3, 2, 1, 2), &[0, 1])),
            ("rootAction AUTHORIZE 12-of-12", RootCase::authorize(RootState::with(12, 12, 1, 6), &(0..12).collect::<Vec<_>>())),
            ("rootAction OWNER-RECOVER (D6, lands frozen)", RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1])),
        ] {
            let call = serde_json::json!({
                "contractVersion": "policyvault-0.7-root",
                "function": "rootAction",
                "action": case.action,
                "successor": successor_json(&case.new),
            });
            execute_with_encoder(&case, call).unwrap_or_else(|e| panic!("{label}: production encoder bytes must be accepted: {e:?}"));
            println!("  ENCODER -> ENGINE ACCEPTED  {label}");
        }

        // ROTATE and FREEZE through the same binary
        let prev = RootState::with(3, 2, 1, 2);
        let mut rotate = RootCase::authorize(prev.clone(), &[0, 1]);
        rotate.action = 1;
        let mut n = prev.advanced();
        n.owners[2] = xonly32(&kp(0x81));
        rotate.new = n;
        execute_with_encoder(
            &rotate,
            serde_json::json!({
                "contractVersion": "policyvault-0.7-root", "function": "rootAction",
                "action": 1, "successor": successor_json(&rotate.new)
            }),
        )
        .expect("rootAction ROTATE production bytes");
        println!("  ENCODER -> ENGINE ACCEPTED  rootAction ROTATE");

        let succ = RootCase::succeed(RootState::with(3, 2, 1, 0), SUCCESSOR_SEED);
        execute_with_encoder(
            &succ,
            serde_json::json!({
                "contractVersion": "policyvault-0.7-root", "function": "rootSuccession",
                "successor": successor_json(&succ.new)
            }),
        )
        .expect("rootSuccession production bytes");
        println!("  ENCODER -> ENGINE ACCEPTED  rootSuccession");
    }

    #[test]
    fn v7root_encoder_fails_closed_on_out_of_domain_intent() {
        assert!(encoder_path().exists(), "build it first: cd tests/vm && cargo build --bin pv_call_encoder");
        let prev = RootState::with(3, 2, 1, 2);
        let tmpl = RootTemplate::default();
        let ok_blob = hx(&[0u8; SIG_BLOB_LEN]);

        let base = |extra: serde_json::Value| -> serde_json::Value {
            let mut v = serde_json::json!({
                "contractVersion": "policyvault-0.7-root",
                "function": "rootAction",
                "action": 0,
                "ownerSigs": ok_blob.clone(),
                "successor": successor_json(&prev.advanced()),
            });
            for (k, val) in extra.as_object().unwrap() {
                v[k] = val.clone();
            }
            v
        };
        let successor_with = |field: &str, value: serde_json::Value| -> serde_json::Value {
            let mut s = successor_json(&prev.advanced());
            s[field] = value;
            serde_json::json!({ "successor": s })
        };

        for (label, call) in [
            ("action out of range (5)", base(serde_json::json!({"action": 5}))),
            ("negative action", base(serde_json::json!({"action": -1}))),
            ("owner blob one byte short", base(serde_json::json!({"ownerSigs": hx(&[0u8; SIG_BLOB_LEN - 1])}))),
            ("a 65-byte `signature` field instead of the blob", base(serde_json::json!({"signature": hx(&[0u8; 65])}))),
            ("unknown entrypoint", base(serde_json::json!({"function": "rootDissolve"}))),
            ("successor frozen byte out of domain", base(successor_with("frozen", serde_json::json!(2)))),
            ("successor emergencyK above ownerM", base(successor_with("emergencyK", serde_json::json!(3)))),
            ("successor recoveryM above ownerM", base(successor_with("recoveryM", serde_json::json!(9)))),
            ("successor rootNonce negative", base(successor_with("rootNonce", serde_json::json!(-1)))),
        ] {
            let err = run(&prev, &tmpl, call).expect_err(&format!("{label}: the encoder must FAIL CLOSED"));
            println!("  ENCODER FAILED CLOSED  {label}\n           -> {err}");
        }

        // An unknown contractVersion is never routed to a default. The row
        // carries a well-formed 65-byte `signature` so it reaches the version
        // dispatch rather than stopping at the shared signature field that
        // every pre-v0.7 generation requires.
        let mut unknown = base(serde_json::json!({"signature": hx(&[0u8; 65])}));
        unknown["contractVersion"] = serde_json::json!("policyvault-0.7-rooot");
        let err = run(&prev, &tmpl, unknown).expect_err("an unknown contractVersion must fail closed");
        assert!(err.contains("unknown contractVersion") && err.contains("failing closed"), "unknown version must fail closed, got: {err}");
        println!("  ENCODER FAILED CLOSED  unknown contractVersion\n           -> {err}");
    }
}

/* ================================================================== */
/* measurement, standardness and stack headroom                        */
/* ================================================================== */

fn mass_of(tx: &Transaction, entries: &[UtxoEntry]) -> (u64, u64, u64, u64) {
    let mc = MassCalculator::new(1, 10, STORAGE_MASS_PARAMETER);
    let m = mc.calc_non_contextual_masses(tx);
    let populated = PopulatedTransaction::new(tx, entries.to_vec());
    let storage = mc.calc_contextual_masses(&populated).map(|c| c.storage_mass).unwrap_or(0);
    let size = transaction_estimated_serialized_size(tx) as u64;
    (size, m.compute_mass, m.transient_mass, storage)
}

fn priced_units_and_sigops(tx: &Transaction, entries: &[UtxoEntry]) -> Vec<(u64, u16, u64)> {
    (0..tx.inputs.len())
        .map(|i| {
            let (r, priced) = execute_input_measured_priced(tx.clone(), entries.to_vec(), i, 1000);
            r.unwrap_or_else(|e| panic!("priced input {i} must accept: {e:?}"));
            let budget = ComputeBudget::checked_covering_script_units(ScriptUnits(priced)).expect("budget").0;
            let sigops = post_toccata_p2sh_sig_scanner(&tx.inputs[i].signature_script, &entries[i].script_public_key);
            (priced, budget, sigops)
        })
        .collect()
}

const MAX_STACK_PROBE: usize = 244;

/// Smallest front-padding that turns the failure into StackSizeExceeded;
/// peak combined stack = 245 - that count.
fn measure_peak_stack<F>(label: &str, mut run_with_pad: F) -> usize
where
    F: FnMut(usize) -> Result<(), TxScriptError>,
{
    run_with_pad(0).unwrap_or_else(|e| panic!("{label}: unpadded run must accept: {e:?}"));
    for pad in 1..=MAX_STACK_PROBE {
        if let Err(TxScriptError::StackSizeExceeded(size, max)) = run_with_pad(pad) {
            assert_eq!(max, 244, "{label}: unexpected MAX_STACK_SIZE");
            let peak = 245 - pad;
            println!("  {label}: peak combined stack {peak} (StackSizeExceeded at pad {pad}, reported {size}/{max}) -> headroom {}", 244 - peak);
            return peak;
        }
    }
    panic!("{label}: never hit MAX_STACK_SIZE within {MAX_STACK_PROBE} padding items");
}

#[test]
fn v7root_measurement_standardness_and_stack() {
    println!("\n===== v0.7-root PRODUCTION MEASUREMENT (real TxScriptEngine, rusty-kaspa 2.0.1) =====");

    let full = RootState::with(12, 12, 1, 6);
    let root_c = compile_root(&full, &RootTemplate::default());
    let t = template_of(&root_c);
    println!("\n[1] ROOT COVENANT GEOMETRY (production candidate)");
    println!(
        "  redeem {} B | state region {} B | head {} B | TAIL {} B | prefix {} B | suffix {} B",
        root_c.script.len(),
        t.state_len,
        t.state_len - ROOT_TAIL_LEN,
        ROOT_TAIL_LEN,
        t.prefix.len(),
        t.suffix.len()
    );
    assert_eq!(t.state_len, ROOT_STATE_LEN);

    let all: Vec<usize> = (0..12).collect();
    let auth12 = accept_root("AUTHORIZE 12-of-12", &RootCase::authorize(full.clone(), &all));
    println!("\n[2] ROOT-ONLY TRANSACTIONS");
    println!("  AUTHORIZE 12-of-12: sigscript {} B | script units {}", auth12.sigscript_len, auth12.units);

    for (label, case) in [
        ("ROTATE 12-of-12", {
            let mut c = RootCase::authorize(full.clone(), &all);
            c.action = 1;
            let mut n = full.advanced();
            n.owners[11] = xonly32(&kp(0x83));
            c.new = n;
            c
        }),
        ("AUTHORIZE 2-of-3", RootCase::authorize(RootState::with(3, 2, 1, 2), &[0, 1])),
        ("FREEZE K=1", {
            let prev = RootState::with(3, 3, 1, 2);
            let mut c = RootCase::authorize(prev.clone(), &[1]);
            c.action = 2;
            c.new = RootState { frozen: 1, ..prev.advanced() };
            c
        }),
        ("OWNER-RECOVER (D6)", RootCase::recover(RootState::with(4, 4, 1, 2), &[0, 1])),
        ("SUCCESSION", RootCase::succeed(RootState::with(3, 2, 1, 0), SUCCESSOR_SEED)),
    ] {
        let o = accept_root(label, &case);
        let (size, compute, transient, storage) = mass_of(&o.tx, &o.entries);
        let priced = priced_units_and_sigops(&o.tx, &o.entries);
        let normalized_transient = (transient * 500_000).div_ceil(1_000_000);
        println!(
            "  {label}: tx {size} B | sigscript {} B | units {} | priced {} -> budget {} | compute_mass {compute} | transient_mass {transient} | storage_mass {storage} | fee_mass {} | STATIC SIG-OPS {}",
            o.tx.inputs[0].signature_script.len(),
            o.units,
            priced[0].0,
            priced[0].1,
            compute.max(normalized_transient),
            priced[0].2
        );
        /* standardness (rusty-kaspa mining/src/mempool/check_transaction_standard.rs):
         *  - static P2SH sig-ops per input <= 15;
         *  - every output script class standard;
         *  - post-Toccata per-transaction block-fit limits: compute <= 500,000,
         *    transient <= 1,000,000. The PRE-Toccata 100,000 standard cap is
         *    reported, never asserted: covenant transactions cannot exist on a
         *    pre-Toccata network. */
        assert_eq!(priced[0].2, ROOT_STATIC_SIG_OPS, "{label}: root static sig-ops must be exactly 12 counting + 1 succession");
        assert!(priced[0].2 <= MAX_STANDARD_P2SH_SIG_OPS, "{label}: sig-ops must stay inside the standardness budget");
        for (i, out) in o.tx.outputs.iter().enumerate() {
            assert_ne!(ScriptClass::from_script(&out.script_public_key), ScriptClass::NonStandard, "{label}: output {i} must be standard");
        }
        assert!(compute <= 500_000, "{label}: compute mass {compute} exceeds the post-Toccata block-fit limit");
        assert!(transient <= 1_000_000, "{label}: transient mass {transient} exceeds the post-Toccata block-fit limit");
        if transient > 100_000 || compute > 100_000 {
            println!("    note: {label} exceeds the PRE-Toccata 100,000 standard cap — post-Toccata only");
        }
    }

    println!("\n[3] THRESHOLD SWEEP (root AUTHORIZE, M-of-M) — sigscript is CONSTANT, only compute varies");
    println!("  {:>7} | {:>13} | {:>12} | {:>13}", "M-of-N", "sigscript B", "script units", "priced units");
    let mut sig_lens = vec![];
    for n in 1..=N_SLOTS {
        let prev = RootState::with(n, n as i64, 1, 0);
        let signers: Vec<usize> = (0..n).collect();
        let o = accept_root(&format!("{n}-of-{n}"), &RootCase::authorize(prev, &signers));
        let p = priced_units_and_sigops(&o.tx, &o.entries);
        println!("  {:>7} | {:>13} | {:>12} | {:>13}", format!("{n}-of-{n}"), o.sigscript_len, o.units, p[0].0);
        sig_lens.push(o.sigscript_len);
    }
    assert!(sig_lens.windows(2).all(|w| w[0] == w[1]), "abstaining slots carry a placeholder, so the envelope must be constant");

    println!("\n[4] MAX_STACK_SIZE (244) HEADROOM");
    measure_peak_stack("root rootAction ROTATE 12-of-12 (WF(prev) + counting + WF(new))", |pad| {
        let mut c = RootCase::authorize(full.clone(), &all);
        c.action = 1;
        let mut n = full.advanced();
        n.owners[11] = xonly32(&kp(0x83));
        c.new = n;
        c.stack_pad = pad;
        run_root(&c).result
    });
    measure_peak_stack("root rootSuccession (WF(prev) + WF(new))", |pad| {
        let mut c = RootCase::succeed(RootState::with(12, 12, 1, 6), SUCCESSOR_SEED);
        c.stack_pad = pad;
        run_root(&c).result
    });
    println!("=====================================================================================\n");
}
