"use strict";
// Deterministic generator for contracts/PolicyVault.v0.6.sil — the v0.6
// ATOMIC-COMPOSABILITY TOKEN CONTROLLER covenant CANDIDATE
// (docs/postlaunch/v0.6-architecture-freeze.md; design record
// docs/postlaunch/v0.6-atomic-composability-design.md). A NEW lineage beside
// the frozen v0.5 controller (contracts/PolicyVault.v0.5.sil, generator
// tools/gen_v5.js) which this file never touches. NOT run at build/consensus
// time; a source-authoring tool. Byte-identical output (no timestamps).
// Covenant generation v0.6 is unrelated to application release v1.6.0.
// Usage: OUT=contracts/PolicyVault.v0.6.sil node tools/gen_v6.js
const AGENT_MAX_DEPTH = 12; // token-agent policy tree
const AGENT_MAX_SIB = AGENT_MAX_DEPTH * 32; // 384
const RECIP_MAX_DEPTH = 16; // recipient tree (v0.3 leaf format)
const RECIP_MAX_SIB = RECIP_MAX_DEPTH * 32; // 512
const MAX_TX_IO = 8;
const ZERO = "0x" + "00".repeat(32);
const out = [];
const P = (s = "") => out.push(s);

/* the 12 token-agent leaf fields (declaration order = leaf byte order) */
const AGENT_PARAMS = [
  "pubkey agentPk",
  "int tokenMaxPerSpend",
  "int tokenPeriodBudget",
  "int periodLengthDaa",
  "int periodStartDaa",
  "int tokenPeriodSpent",
  "int agentMaxFeePerTx",
  "int agentMaxCarryKas",
  "int kasMaxPerSwap",
  "int kasPeriodBudget",
  "int kasPeriodSpent",
  "byte[32] agentRecipientRoot"
];
const AGENT_ARGS = AGENT_PARAMS.map((p) => p.split(" ")[1]).join(", ");
/* the 14 swap-policy leaf fields (declaration order = leaf byte order) */
const SWAP_PARAMS = [
  "byte[32] profileHash",
  "byte[32] poolCovenantId",
  "byte[32] poolTemplateVmHash",
  "int poolPrefixLen",
  "int poolSuffixLen",
  "pubkey poolFeePk",
  "int maxProtocolFeeKas",
  "int sellFloorNum",
  "int sellFloorDen",
  "int buyCeilNum",
  "int buyCeilDen",
  "int directionMask",
  "byte destScheme",
  "pubkey destIdentity"
];
const SWAP_ARGS = SWAP_PARAMS.map((p) => p.split(" ")[1]).join(", ");
const params = (list, indent = "        ") => list.map((p) => `${indent}${p},`).join("\n");

P("pragma silverscript ^0.1.0;");
P("");
P("/*");
P(" * PolicyVault v0.6 — ATOMIC-COMPOSABILITY TOKEN CONTROLLER covenant (CANDIDATE;");
P(" * docs/postlaunch/v0.6-architecture-freeze.md). Covenant generation v0.6 is");
P(" * unrelated to application release v1.6.0.");
P(" *");
P(" * A NEW opt-in lineage beside the frozen v0.5 token controller. It keeps");
P(" * EVERY v0.5 protection (dual binding A/B, transaction-derived verified");
P(" * template carriage, token-denominated per-agent policy, exact conservation,");
P(" * KAS fee reserve as a separate domain, owner control, break-glass recovery)");
P(" * and adds ONE narrow composition capability: an atomic S2 swap against ONE");
P(" * owner-approved external constant-product pool covenant, in EITHER direction:");
P(" *   tokenAtomicSell — tokens leave the controller's position, KAS proceeds");
P(" *                     arrive (type A: accrue to the protected swapPrincipal;");
P(" *                     type B: an owner-allowlisted P2PK output);");
P(" *   tokenAtomicBuy  — KAS consideration leaves the protected swapPrincipal");
P(" *                     ONLY, tokens accrue to the controller's own position.");
P(" * The v0.5-shaped tokenAgentSpend / ownerControl / ownerRecover entrypoints");
P(" * still forbid EVERY foreign covenant input (no blanket relaxation).");
P(" *");
P(" * THREE KAS DOMAINS in one UTXO (value = feeReserve + swapPrincipal):");
P(" *   feeReserve    — may only ever become network fee (per-agent agentMaxFeePerTx,");
P(" *                   bounded by the exact fee);");
P(" *   swapPrincipal — the ONLY source of BUY consideration and the type-A SELL");
P(" *                   proceeds sink; funded by the owner (ownerControl 5); never");
P(" *                   fee, never token-note backing; accounted per agent");
P(" *                   (kasMaxPerSwap / kasPeriodBudget);");
P(" *   token-note carry — the token UTXOs' own KAS, never consideration, never fee.");
P(" *");
P(" * Owner-approved SWAP POLICY leaf (229-byte preimage; distinct length):");
P(" *   sha256(0x50563602 || profileHash || poolCovenantId || poolTemplateVmHash ||");
P(" *          num8(poolPrefixLen) || num8(poolSuffixLen) || poolFeePk ||");
P(" *          num8(maxProtocolFeeKas) || num8(sellFloorNum) || num8(sellFloorDen) ||");
P(" *          num8(buyCeilNum) || num8(buyCeilDen) || num8(directionMask) ||");
P(" *          destScheme || destIdentity)");
P(" *   profileHash = application identity of the policyvault-swap-venue-profile/1");
P(" *   (not evaluated in-VM); the VM-relevant protocol facts are explicit fields.");
P(" *   directionMask: 1 = SELL only, 2 = BUY only, 3 = both. destScheme 0x02 =");
P(" *   PolicyVault-controlled successor (type A; destIdentity = zero), 0x00 =");
P(" *   allowlisted P2PK (type B, SELL only; destIdentity = the x-only key).");
P(" *   Membership under state.swapRoot (owner-set, ownerControl 4); depth <= 12.");
P(" *");
P(" * Token-agent policy leaf (149-byte preimage; distinct from 125/124/36/64):");
P(" *   sha256(0x50563601 || agentPk || num8(tokenMaxPerSpend) ||");
P(" *          num8(tokenPeriodBudget) || num8(periodLengthDaa) ||");
P(" *          num8(periodStartDaa) || num8(tokenPeriodSpent) ||");
P(" *          num8(agentMaxFeePerTx) || num8(agentMaxCarryKas) ||");
P(" *          num8(kasMaxPerSwap) || num8(kasPeriodBudget) || num8(kasPeriodSpent) ||");
P(" *          recipientRoot || 0x00)");
P(" *   token caps bound tokenAgentSpend + SELL; KAS caps bound BUY consideration;");
P(" *   one period clock resets BOTH spent counters at rollover.");
P(" * Recipient leaf = sha256(0x50563301 || recipientPk) (v0.3, 36 bytes).");
P(` * Agent proof depth <= ${AGENT_MAX_DEPTH}; recipient proof depth <= ${RECIP_MAX_DEPTH}.`);
P(" *");
P(" * SIGHASH GATE: every agent authorization (spend, sell, buy) must commit to");
P(" * the WHOLE transaction (hash type byte 0x01 = SIGHASH_ALL), refused");
P(" * in-covenant independently of wallet policy.");
P(" *");
P(" * Security boundary: Kaspa consensus. A holder of a legitimate agent key");
P(" * bypassing the app and submitting directly to a node is bounded by every");
P(" * rule below.");
P(" */");
P("contract PolicyVaultV6(");
P("    pubkey owner,");
P("    byte[32] vaultId,");
P("    byte[32] descriptorHash,");
P("    byte[32] tokenCovenantId,");
P("    byte[32] templateVmHash,");
P("    int templatePrefixLen,");
P("    int templateStateLen,");
P("    int templateSuffixLen,");
P("    byte[32] initAgentRoot,");
P("    int initFeeReserve,");
P("    byte[32] initSwapRoot,");
P("    int initSwapPrincipal");
P(") {");
P("    byte[32] boundVaultId = vaultId;");
P("    int feeReserve = initFeeReserve;");
P("    int swapPrincipal = initSwapPrincipal;");
P("    int paused = 0;");
P("    byte[32] agentRoot = initAgentRoot;");
P("    byte[32] swapRoot = initSwapRoot;");
P("    int policyNonce = 0;");
P("");
P("    struct KCC20State {");
P("        byte[32] ownerIdentifier;");
P("        byte identifierType;");
P("        int amount;");
P("        bool isMinter;");
P("    }");
P("");
P("    /* the approved pool family's state layout (policyvault-swap-venue-profile/1");
P("     * constant-product pool: kasReserve, tokenReserve, feeBps, nonce) */");
P("    struct PoolState {");
P("        int kasReserve;");
P("        int tokenReserve;");
P("        int feeBps;");
P("        int nonce;");
P("    }");
P("");
P("    byte constant IDENTIFIER_PUBKEY = 0x00;");
P("    byte constant IDENTIFIER_COVENANT_ID = 0x02;");
P("");
P("    /* Exact single authorized successor value at the auth output. */");
P("    function requireExactSuccessorValue(int exactValue) {");
P("        int successorIndex = OpAuthOutputIdx(this.activeInputIndex, 0);");
P("        require(tx.outputs[successorIndex].value == exactValue);");
P("    }");
P("");
P("    /* Vault-global fields preserved across an agent transition (feeReserve,");
P("     * swapPrincipal and agentRoot move by rule). The descriptor pin is a");
P("     * template constant; referencing it keeps it in the revealed redeem. */");
P("    function requireVaultGlobalPreserved(State prevState, State newState) {");
P("        require(newState.boundVaultId == prevState.boundVaultId);");
P("        require(newState.paused == prevState.paused);");
P("        require(newState.policyNonce == prevState.policyNonce);");
P("        require(newState.swapRoot == prevState.swapRoot);");
P(`        require(bytes(descriptorHash) != bytes(${ZERO}));`);
P("    }");
P("");
P("    /* BINDING A (family isolation, v0.5 semantics): every input other than");
P("     * this covenant and the pinned token-family input must be a PLAIN input.");
P(`     * Bounded to <= ${MAX_TX_IO} inputs. */`);
P("    function requireNoForeignCovenantInputs(int tokIn) {");
P("        int inCount = tx.inputs.length;");
P("        require(inCount >= 1);");
P(`        require(inCount <= ${MAX_TX_IO});`);
P(`        for (i, 0, inCount, ${MAX_TX_IO}) {`);
P("            if (i != this.activeInputIndex) {");
P("                if (i != tokIn) {");
P(`                    require(bytes(OpInputCovenantId(i)) == bytes(${ZERO}));`);
P("                }");
P("            }");
P("        }");
P("    }");
P("");
P("    /* COMPOSITION BINDING (swap entrypoints only): every input other than");
P("     * this covenant is either the pinned token family, the ONE approved pool");
P("     * family, or a plain input — a third covenant family never rides. */");
P("    function requireOnlyApprovedCovenantInputs(byte[32] poolId) {");
P("        int inCount = tx.inputs.length;");
P("        require(inCount >= 1);");
P(`        require(inCount <= ${MAX_TX_IO});`);
P(`        for (i, 0, inCount, ${MAX_TX_IO}) {`);
P("            if (i != this.activeInputIndex) {");
P("                byte[32] cid = OpInputCovenantId(i);");
P("                if (cid != tokenCovenantId) {");
P("                    if (cid != poolId) {");
P(`                        require(bytes(cid) == bytes(${ZERO}));`);
P("                    }");
P("                }");
P("            }");
P("        }");
P("    }");
P("");
P("    /* Canonical token-agent policy leaf (149-byte preimage). */");
P("    function tokenAgentLeaf(");
P(params(AGENT_PARAMS).replace(/,$/, ""));
P("    ) : (byte[]) {");
P("        byte[] leaf = bytes(sha256(");
P("            bytes(0x50563601)");
P("            + bytes(agentPk)");
P("            + OpNum2Bin(tokenMaxPerSpend, 8)");
P("            + OpNum2Bin(tokenPeriodBudget, 8)");
P("            + OpNum2Bin(periodLengthDaa, 8)");
P("            + OpNum2Bin(periodStartDaa, 8)");
P("            + OpNum2Bin(tokenPeriodSpent, 8)");
P("            + OpNum2Bin(agentMaxFeePerTx, 8)");
P("            + OpNum2Bin(agentMaxCarryKas, 8)");
P("            + OpNum2Bin(kasMaxPerSwap, 8)");
P("            + OpNum2Bin(kasPeriodBudget, 8)");
P("            + OpNum2Bin(kasPeriodSpent, 8)");
P("            + bytes(agentRecipientRoot)");
P("            + bytes(0x00)");
P("        ));");
P("        return leaf;");
P("    }");
P("");
P("    /* Canonical owner-approved swap-policy leaf (229-byte preimage). */");
P("    function swapPolicyLeaf(");
P(params(SWAP_PARAMS).replace(/,$/, ""));
P("    ) : (byte[]) {");
P("        byte[] leaf = bytes(sha256(");
P("            bytes(0x50563602)");
P("            + bytes(profileHash)");
P("            + bytes(poolCovenantId)");
P("            + bytes(poolTemplateVmHash)");
P("            + OpNum2Bin(poolPrefixLen, 8)");
P("            + OpNum2Bin(poolSuffixLen, 8)");
P("            + bytes(poolFeePk)");
P("            + OpNum2Bin(maxProtocolFeeKas, 8)");
P("            + OpNum2Bin(sellFloorNum, 8)");
P("            + OpNum2Bin(sellFloorDen, 8)");
P("            + OpNum2Bin(buyCeilNum, 8)");
P("            + OpNum2Bin(buyCeilDen, 8)");
P("            + OpNum2Bin(directionMask, 8)");
P("            + bytes(destScheme)");
P("            + bytes(destIdentity)");
P("        ));");
P("        return leaf;");
P("    }");
P("");
P("    /* Single-leaf Merkle fold over a co-path (FUNDS-CRITICAL; v0.4 mechanism,");
P(`     * VM-proven). depth <= ${AGENT_MAX_DEPTH}. */`);
P("    function computeMerkleRoot(byte[] leaf, byte[] siblings, int pathBits) : (byte[]) {");
P("        require(siblings.length % 32 == 0);");
P(`        require(siblings.length <= ${AGENT_MAX_SIB});`);
P("        int depth = siblings.length / 32;");
P("        require(pathBits >= 0);");
P(`        require(pathBits < ${1 << AGENT_MAX_DEPTH});`);
P("        byte[] node = leaf;");
P("        byte[] rest = siblings;");
P("        int bits = pathBits;");
P(`        for (level, 0, depth, ${AGENT_MAX_DEPTH}) {`);
P("            (byte[] sib, byte[] tail) = rest.split(32);");
P("            rest = tail;");
P("            if (bits % 2 == 1) {");
P("                node = bytes(sha256(sib + node));");
P("            } else {");
P("                node = bytes(sha256(node + sib));");
P("            }");
P("            bits = bits / 2;");
P("        }");
P("        require(bits == 0);");
P("        return node;");
P("    }");
P("");
P("    function requireAgentMembership(byte[32] root, byte[] oldLeaf, byte[] siblings, int pathBits) {");
P("        (byte[] oldRoot) = computeMerkleRoot(oldLeaf, siblings, pathBits);");
P("        require(oldRoot == bytes(root));");
P("    }");
P("");
P("    /* The swap-policy leaf MUST be committed under the live swapRoot. */");
P("    function requireSwapPolicy(");
P("        byte[32] root,");
P(params(SWAP_PARAMS));
P("        byte[] swapSiblings,");
P("        int swapPathBits");
P("    ) {");
P(`        (byte[] leaf) = swapPolicyLeaf(${SWAP_ARGS});`);
P("        (byte[] computed) = computeMerkleRoot(leaf, swapSiblings, swapPathBits);");
P("        require(computed == bytes(root));");
P("    }");
P("");
P("    /* Authenticate the token-agent leaf, advance its accounting in BOTH");
P("     * domains (tokenSpend: tokens given up by spend/sell; kasSpend: KAS");
P("     * consideration given up by buy), and pin the successor agentRoot. */");
P("    function requireAgentTransition(");
P("        State prevState,");
P("        State newState,");
P("        int tokenSpend,");
P("        int kasSpend,");
P(params(AGENT_PARAMS));
P("        byte[] policySiblings,");
P("        int policyPathBits,");
P("        int periodsElapsed");
P("    ) {");
P("        require(tokenSpend >= 0);");
P("        require(kasSpend >= 0);");
P("        require(tokenSpend <= tokenMaxPerSpend);");
P("        require(kasSpend <= kasMaxPerSwap);");
P("        require(periodsElapsed >= 0);");
P("        require(periodsElapsed <= 1000);");
P("        int newStart = periodStartDaa;");
P("        int newTokenSpent = tokenPeriodSpent + tokenSpend;");
P("        int newKasSpent = kasPeriodSpent + kasSpend;");
P("        if (periodsElapsed >= 1) {");
P("            newStart = periodStartDaa + periodsElapsed * periodLengthDaa;");
P("            require(tx.time >= newStart);");
P("            newTokenSpent = tokenSpend;");
P("            newKasSpent = kasSpend;");
P("        }");
P("        require(newTokenSpent <= tokenPeriodBudget);");
P("        require(newKasSpent <= kasPeriodBudget);");
P("        (byte[] oldLeaf) = tokenAgentLeaf(agentPk, tokenMaxPerSpend, tokenPeriodBudget, periodLengthDaa, periodStartDaa, tokenPeriodSpent, agentMaxFeePerTx, agentMaxCarryKas, kasMaxPerSwap, kasPeriodBudget, kasPeriodSpent, agentRecipientRoot);");
P("        requireAgentMembership(prevState.agentRoot, oldLeaf, policySiblings, policyPathBits);");
P("        (byte[] newLeaf) = tokenAgentLeaf(agentPk, tokenMaxPerSpend, tokenPeriodBudget, periodLengthDaa, newStart, newTokenSpent, agentMaxFeePerTx, agentMaxCarryKas, kasMaxPerSwap, kasPeriodBudget, newKasSpent, agentRecipientRoot);");
P("        (byte[] newRoot) = computeMerkleRoot(newLeaf, policySiblings, policyPathBits);");
P("        require(bytes(newState.agentRoot) == newRoot);");
P("    }");
P("");
P("    /* Recipient membership under the LEAF's own recipient root (v0.3 leaf). */");
P("    function requireAgentRecipient(byte[32] root, pubkey recipientPk, byte[] siblings, int pathBits) {");
P("        require(siblings.length % 32 == 0);");
P(`        require(siblings.length <= ${RECIP_MAX_SIB});`);
P("        int depth = siblings.length / 32;");
P("        require(pathBits >= 0);");
P(`        require(pathBits < ${1 << RECIP_MAX_DEPTH});`);
P("        byte[] node = bytes(sha256(bytes(0x50563301) + bytes(recipientPk)));");
P("        byte[] rest = siblings;");
P("        int bits = pathBits;");
P(`        for (level, 0, depth, ${RECIP_MAX_DEPTH}) {`);
P("            (byte[] sib, byte[] tail) = rest.split(32);");
P("            rest = tail;");
P("            if (bits % 2 == 1) {");
P("                node = bytes(sha256(sib + node));");
P("            } else {");
P("                node = bytes(sha256(node + sib));");
P("            }");
P("            bits = bits / 2;");
P("        }");
P("        require(bits == 0);");
P("        require(node == bytes(root));");
P("    }");
P("");
P("    /* Exact network fee from full input/output value introspection. */");
P("    function txFee() : (int) {");
P("        int inCount = tx.inputs.length;");
P("        require(inCount >= 1);");
P(`        require(inCount <= ${MAX_TX_IO});`);
P("        int outCount = tx.outputs.length;");
P("        require(outCount >= 1);");
P(`        require(outCount <= ${MAX_TX_IO});`);
P("        int totalIn = 0;");
P(`        for (i, 0, inCount, ${MAX_TX_IO}) {`);
P("            totalIn = totalIn + tx.inputs[i].value;");
P("        }");
P("        int totalOut = 0;");
P(`        for (j, 0, outCount, ${MAX_TX_IO}) {`);
P("            totalOut = totalOut + tx.outputs[j].value;");
P("        }");
P("        require(totalOut <= totalIn);");
P("        int fee = totalIn - totalOut;");
P("        return fee;");
P("    }");
P("");
P("    /* FEE-RESERVE DOMAIN (FR-1) + successor pin: reserve consumed is >= 0,");
P("     * <= agentMaxFeePerTx, <= the exact fee; the principal never goes");
P("     * negative; the successor carries EXACTLY feeReserve + swapPrincipal. */");
P("    function requireFeeReserveDomain(State prevState, State newState, int agentMaxFeePerTx) {");
P("        require(newState.feeReserve >= 0);");
P("        require(newState.swapPrincipal >= 0);");
P("        int reserveConsumed = prevState.feeReserve - newState.feeReserve;");
P("        require(reserveConsumed >= 0);");
P("        require(reserveConsumed <= agentMaxFeePerTx);");
P("        (int fee) = txFee();");
P("        require(reserveConsumed <= fee);");
P("        requireExactSuccessorValue(newState.feeReserve + newState.swapPrincipal);");
P("    }");
P("");
P("    /* KAS DOMAINS of a v0.5-shaped token spend: the token family's own KAS");
P("     * never leaks (self + recipient carry >= token input KAS; recipient carry");
P("     * <= agentMaxCarryKas); the swap principal is untouched. */");
P("    function requireKasDomainsSpend(State prevState, State newState, int tokIn, int agentMaxFeePerTx, int agentMaxCarryKas) {");
P("        int selfOut = OpCovOutputIdx(tokenCovenantId, 0);");
P("        int recipientOut = OpCovOutputIdx(tokenCovenantId, 1);");
P("        require(tx.outputs[selfOut].value + tx.outputs[recipientOut].value >= tx.inputs[tokIn].value);");
P("        require(tx.outputs[recipientOut].value <= agentMaxCarryKas);");
P("        require(newState.swapPrincipal == prevState.swapPrincipal);");
P("        requireFeeReserveDomain(prevState, newState, agentMaxFeePerTx);");
P("    }");
P("");
P("    /* Exact COMPOSITION SHAPE + POOL BINDING: token family 2-in/2-out (our note");
P("     * + the pool's reserve note), pool family 1-in/1-out, nothing else; the");
P("     * ONE foreign input is the approved pool family (consensus lineage) AND its");
P("     * revealed redeem is the approved pool template (hash + geometry + P2SH). */");
P("    function requireSwapShape(byte[32] poolCovenantId, byte[32] poolTemplateVmHash, int poolPrefixLen, int poolSuffixLen) {");
P("        /* EXACTLY four inputs (controller, two token notes, pool): no external");
P("         * non-covenant KAS input can ride a swap — the network fee comes from");
P("         * the fee reserve only (architecture freeze OQ-V6-5, first candidate). */");
P("        require(tx.inputs.length == 4);");
P("        require(OpCovInputCount(tokenCovenantId) == 2);");
P("        require(OpCovOutputCount(tokenCovenantId) == 2);");
P("        require(OpCovInputCount(poolCovenantId) == 1);");
P("        require(OpCovOutputCount(poolCovenantId) == 1);");
P("        requireOnlyApprovedCovenantInputs(poolCovenantId);");
P("        int poolIn = OpCovInputIdx(poolCovenantId, 0);");
P("        PoolState poolPrev = readInputStateWithTemplate(poolIn, poolPrefixLen, poolSuffixLen, poolTemplateVmHash);");
P("        require(poolPrev.tokenReserve >= 0);");
P("        require(poolPrev.kasReserve >= 0);");
P("    }");
P("");
P("    /* TOKEN NOTES of a swap: both family inputs proven against the pinned");
P("     * token template; exactly one is OURS (owner = our covenant id), the other");
P("     * MUST be owned by the approved pool; continuation outputs (family output 0");
P("     * = ours, 1 = the pool's) reconstructed from OUR proven input's carried");
P("     * template; exact conservation with a signed delta (delta > 0: tokens to");
P("     * the pool [sell]; delta < 0: tokens from the pool [buy]); our note's KAS");
P("     * carry never leaks. */");
P("    function requireTokenNotes(KCC20State selfNew, KCC20State poolNoteNew, byte[32] poolCovenantId, int delta) {");
P("        byte[32] selfId = OpInputCovenantId(this.activeInputIndex);");
P("        int tokA = OpCovInputIdx(tokenCovenantId, 0);");
P("        int tokB = OpCovInputIdx(tokenCovenantId, 1);");
P("        KCC20State stA = readInputStateWithTemplate(tokA, templatePrefixLen, templateSuffixLen, templateVmHash);");
P("        KCC20State stB = readInputStateWithTemplate(tokB, templatePrefixLen, templateSuffixLen, templateVmHash);");
P("        require(stA.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(stB.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!stA.isMinter);");
P("        require(!stB.isMinter);");
P("        int ourIn = tokA;");
P("        int ourAmount = stA.amount;");
P("        int poolAmount = stB.amount;");
P("        if (stA.ownerIdentifier == selfId) {");
P("            require(stB.ownerIdentifier == poolCovenantId);");
P("        } else {");
P("            require(stB.ownerIdentifier == selfId);");
P("            require(stA.ownerIdentifier == poolCovenantId);");
P("            ourIn = tokB;");
P("            ourAmount = stB.amount;");
P("            poolAmount = stA.amount;");
P("        }");
P("        require(ourAmount >= 0);");
P("        require(poolAmount >= 0);");
P("        int sigLen = OpTxInputScriptSigLen(ourIn);");
P("        int redeemStart = sigLen - (templatePrefixLen + templateStateLen + templateSuffixLen);");
P("        byte[] templatePrefix = OpTxInputScriptSigSubstr(ourIn, redeemStart, redeemStart + templatePrefixLen);");
P("        byte[] templateSuffix = OpTxInputScriptSigSubstr(ourIn, sigLen - templateSuffixLen, sigLen);");
P("        require(selfNew.ownerIdentifier == selfId);");
P("        require(selfNew.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!selfNew.isMinter);");
P("        require(selfNew.amount >= 0);");
P("        require(selfNew.amount == ourAmount - delta);");
P("        require(poolNoteNew.ownerIdentifier == poolCovenantId);");
P("        require(poolNoteNew.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!poolNoteNew.isMinter);");
P("        require(poolNoteNew.amount >= 0);");
P("        require(poolNoteNew.amount == poolAmount + delta);");
P("        int selfOut = OpCovOutputIdx(tokenCovenantId, 0);");
P("        int poolNoteOut = OpCovOutputIdx(tokenCovenantId, 1);");
P("        validateOutputStateWithTemplate(selfOut, selfNew, templatePrefix, templateSuffix, templateVmHash);");
P("        validateOutputStateWithTemplate(poolNoteOut, poolNoteNew, templatePrefix, templateSuffix, templateVmHash);");
P("        require(tx.outputs[selfOut].value >= tx.inputs[ourIn].value);");
P("    }");
P("");
P("    /* PROTOCOL FEE output: plain P2PK to the profile's pinned fee key, bounded");
P("     * by the owner's maxProtocolFeeKas; returns its value. */");
P("    function protocolFeeValue(int feeOutIdx, pubkey poolFeePk, int maxProtocolFeeKas) : (int) {");
P(`        require(bytes(OpOutputCovenantId(feeOutIdx)) == bytes(${ZERO}));`);
P("        require(tx.outputs[feeOutIdx].scriptPubKey == new ScriptPubKeyP2PK(poolFeePk));");
P("        int protoFee = tx.outputs[feeOutIdx].value;");
P("        require(protoFee >= 0);");
P("        require(protoFee <= maxProtocolFeeKas);");
P("        return protoFee;");
P("    }");
P("");
P("    /* SIGHASH gate + the leaf's key is the sole authority. */");
P("    function requireAgentAuthorization(byte[] agentSig, pubkey agentPk) {");
P("        require(agentSig.length == 65);");
P("        (byte[] sigBody, byte[] hashByte) = agentSig.split(64);");
P("        require(hashByte == bytes(0x01));");
P("        require(checkSig(sig(agentSig), agentPk));");
P("    }");
P("");

// ---- tokenAgentSpend (v0.5 semantics + SIGHASH gate + v0.6 leaf) ----------
P("    #[covenant.singleton]");
P("    function tokenAgentSpend(");
P("        State prevState,");
P("        State newState,");
P("        KCC20State selfNew,");
P("        KCC20State recipientNew,");
P(params(AGENT_PARAMS));
P("        byte[] policySiblings,");
P("        int policyPathBits,");
P("        int periodsElapsed,");
P("        pubkey recipientPk,");
P("        byte[] recipientSiblings,");
P("        int recipientPathBits,");
P("        byte[] agentSig");
P("    ) {");
P("        require(prevState.paused == 0);");
P("        requireAgentAuthorization(agentSig, agentPk);");
P("");
P("        /* BINDING A — exact pinned token family, exact shape (1 in, 2 out:");
P("         * self continuation + single recipient), no foreign covenants. */");
P("        require(OpCovInputCount(tokenCovenantId) == 1);");
P("        require(OpCovOutputCount(tokenCovenantId) == 2);");
P("        int tokIn = OpCovInputIdx(tokenCovenantId, 0);");
P("        requireNoForeignCovenantInputs(tokIn);");
P("");
P("        /* BINDING B — the token input's revealed redeem is proven BEFORE its");
P("         * state is trusted; template carriage from that proven input. */");
P("        KCC20State prevTok = readInputStateWithTemplate(");
P("            tokIn,");
P("            templatePrefixLen,");
P("            templateSuffixLen,");
P("            templateVmHash");
P("        );");
P("        int sigLen = OpTxInputScriptSigLen(tokIn);");
P("        int redeemStart = sigLen - (templatePrefixLen + templateStateLen + templateSuffixLen);");
P("        byte[] templatePrefix = OpTxInputScriptSigSubstr(tokIn, redeemStart, redeemStart + templatePrefixLen);");
P("        byte[] templateSuffix = OpTxInputScriptSigSubstr(tokIn, sigLen - templateSuffixLen, sigLen);");
P("");
P("        byte[32] selfId = OpInputCovenantId(this.activeInputIndex);");
P("        require(prevTok.ownerIdentifier == selfId);");
P("        require(prevTok.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!prevTok.isMinter);");
P("        require(selfNew.ownerIdentifier == selfId);");
P("        require(selfNew.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!selfNew.isMinter);");
P("        require(bytes(selfNew.ownerIdentifier) != bytes(recipientPk));");
P("        require(bytes(recipientNew.ownerIdentifier) == bytes(recipientPk));");
P("        require(recipientNew.identifierType == IDENTIFIER_PUBKEY);");
P("        require(!recipientNew.isMinter);");
P("");
P("        /* TOKEN DOMAIN — exact conservation + token-denominated policy. */");
P("        int spendAmount = recipientNew.amount;");
P("        require(spendAmount > 0);");
P("        require(selfNew.amount >= 0);");
P("        require(selfNew.amount == prevTok.amount - spendAmount);");
P(`        requireAgentTransition(prevState, newState, spendAmount, 0, ${AGENT_ARGS}, policySiblings, policyPathBits, periodsElapsed);`);
P("        requireAgentRecipient(agentRecipientRoot, recipientPk, recipientSiblings, recipientPathBits);");
P("");
P("        validateOutputStateWithTemplate(");
P("            OpCovOutputIdx(tokenCovenantId, 0),");
P("            selfNew,");
P("            templatePrefix,");
P("            templateSuffix,");
P("            templateVmHash");
P("        );");
P("        validateOutputStateWithTemplate(");
P("            OpCovOutputIdx(tokenCovenantId, 1),");
P("            recipientNew,");
P("            templatePrefix,");
P("            templateSuffix,");
P("            templateVmHash");
P("        );");
P("");
P("        requireKasDomainsSpend(prevState, newState, tokIn, agentMaxFeePerTx, agentMaxCarryKas);");
P("        requireVaultGlobalPreserved(prevState, newState);");
P("    }");
P("");

// ---- tokenAtomicSell --------------------------------------------------------
P("    /* ATOMIC SELL: give up EXACTLY amountIn tokens to the approved pool's");
P("     * reserve note; receive net KAS proceeds (pool KAS decrease minus the");
P("     * bounded protocol fee) >= minKasOut and >= the owner's floor price, at");
P("     * the owner-approved destination (type A: accrue to swapPrincipal; type B:");
P("     * exact plain P2PK output). Outputs: successor, our note, pool note, pool");
P("     * successor, protocol fee (+ proceeds for type B) — nothing else. */");
P("    #[covenant.singleton]");
P("    function tokenAtomicSell(");
P("        State prevState,");
P("        State newState,");
P("        KCC20State selfNew,");
P("        KCC20State poolNoteNew,");
P(params(AGENT_PARAMS));
P("        byte[] policySiblings,");
P("        int policyPathBits,");
P("        int periodsElapsed,");
P(params(SWAP_PARAMS));
P("        byte[] swapSiblings,");
P("        int swapPathBits,");
P("        int amountIn,");
P("        int minKasOut,");
P("        int proceedsOutIdx,");
P("        int feeOutIdx,");
P("        byte[] agentSig");
P("    ) {");
P("        require(prevState.paused == 0);");
P("        requireAgentAuthorization(agentSig, agentPk);");
P(`        requireSwapPolicy(prevState.swapRoot, ${SWAP_ARGS}, swapSiblings, swapPathBits);`);
P("        require(directionMask >= 1);");
P("        require(directionMask <= 3);");
P("        require(directionMask % 2 == 1);");
P("        requireSwapShape(poolCovenantId, poolTemplateVmHash, poolPrefixLen, poolSuffixLen);");
P("        require(amountIn > 0);");
P("        requireTokenNotes(selfNew, poolNoteNew, poolCovenantId, amountIn);");
P("");
P("        /* KAS proceeds = the pool's exact KAS decrease minus the protocol fee */");
P("        int poolIn = OpCovInputIdx(poolCovenantId, 0);");
P("        int poolOut = OpCovOutputIdx(poolCovenantId, 0);");
P("        int kasOut = tx.inputs[poolIn].value - tx.outputs[poolOut].value;");
P("        require(kasOut > 0);");
P("        (int protoFee) = protocolFeeValue(feeOutIdx, poolFeePk, maxProtocolFeeKas);");
P("        require(protoFee < kasOut);");
P("        int netProceeds = kasOut - protoFee;");
P("        require(minKasOut > 0);");
P("        require(netProceeds >= minKasOut);");
P("        require(sellFloorDen > 0);");
P("        require(netProceeds * sellFloorDen >= amountIn * sellFloorNum);");
P("");
P("        if (destScheme == IDENTIFIER_COVENANT_ID) {");
P("            /* type A: proceeds accrue to the protected principal; the proceeds");
P("             * index MUST name our own successor; no proceeds output exists */");
P(`            require(bytes(destIdentity) == bytes(${ZERO}));`);
P("            require(proceedsOutIdx == OpAuthOutputIdx(this.activeInputIndex, 0));");
P("            require(newState.swapPrincipal == prevState.swapPrincipal + netProceeds);");
P("            require(tx.outputs.length == 5);");
P("        } else {");
P("            /* type B: exact plain P2PK proceeds output to the allowlisted key */");
P("            require(destScheme == IDENTIFIER_PUBKEY);");
P("            require(feeOutIdx != proceedsOutIdx);");
P(`            require(bytes(OpOutputCovenantId(proceedsOutIdx)) == bytes(${ZERO}));`);
P("            require(tx.outputs[proceedsOutIdx].scriptPubKey == new ScriptPubKeyP2PK(destIdentity));");
P("            require(tx.outputs[proceedsOutIdx].value == netProceeds);");
P("            require(newState.swapPrincipal == prevState.swapPrincipal);");
P("            require(tx.outputs.length == 6);");
P("        }");
P("");
P(`        requireAgentTransition(prevState, newState, amountIn, 0, ${AGENT_ARGS}, policySiblings, policyPathBits, periodsElapsed);`);
P("        requireFeeReserveDomain(prevState, newState, agentMaxFeePerTx);");
P("        requireVaultGlobalPreserved(prevState, newState);");
P("    }");
P("");

// ---- tokenAtomicBuy ---------------------------------------------------------
P("    /* ATOMIC BUY: pay KAS consideration (the pool's exact KAS increase + the");
P("     * bounded protocol fee) from the protected swapPrincipal ONLY, bounded by");
P("     * maxKasIn, the agent's kasMaxPerSwap / kasPeriodBudget and the owner's");
P("     * ceiling price; receive EXACTLY tokensOut into OUR position (type A only:");
P("     * tokens never leave to a third party on a buy). Outputs: successor, our");
P("     * note, pool note, pool successor, protocol fee — nothing else. */");
P("    #[covenant.singleton]");
P("    function tokenAtomicBuy(");
P("        State prevState,");
P("        State newState,");
P("        KCC20State selfNew,");
P("        KCC20State poolNoteNew,");
P(params(AGENT_PARAMS));
P("        byte[] policySiblings,");
P("        int policyPathBits,");
P("        int periodsElapsed,");
P(params(SWAP_PARAMS));
P("        byte[] swapSiblings,");
P("        int swapPathBits,");
P("        int tokensOut,");
P("        int maxKasIn,");
P("        int feeOutIdx,");
P("        byte[] agentSig");
P("    ) {");
P("        require(prevState.paused == 0);");
P("        requireAgentAuthorization(agentSig, agentPk);");
P(`        requireSwapPolicy(prevState.swapRoot, ${SWAP_ARGS}, swapSiblings, swapPathBits);`);
P("        require(directionMask >= 2);");
P("        require(directionMask <= 3);");
P("        require(destScheme == IDENTIFIER_COVENANT_ID);");
P(`        require(bytes(destIdentity) == bytes(${ZERO}));`);
P("        requireSwapShape(poolCovenantId, poolTemplateVmHash, poolPrefixLen, poolSuffixLen);");
P("        require(tokensOut > 0);");
P("        requireTokenNotes(selfNew, poolNoteNew, poolCovenantId, 0 - tokensOut);");
P("");
P("        /* KAS consideration = the pool's exact KAS increase + the protocol fee */");
P("        int poolIn = OpCovInputIdx(poolCovenantId, 0);");
P("        int poolOut = OpCovOutputIdx(poolCovenantId, 0);");
P("        int kasIn = tx.outputs[poolOut].value - tx.inputs[poolIn].value;");
P("        require(kasIn > 0);");
P("        (int protoFee) = protocolFeeValue(feeOutIdx, poolFeePk, maxProtocolFeeKas);");
P("        int kasSpend = kasIn + protoFee;");
P("        require(maxKasIn > 0);");
P("        require(kasSpend <= maxKasIn);");
P("        require(buyCeilDen > 0);");
P("        require(kasSpend * buyCeilDen <= tokensOut * buyCeilNum);");
P("        require(newState.swapPrincipal == prevState.swapPrincipal - kasSpend);");
P("        require(tx.outputs.length == 5);");
P("");
P(`        requireAgentTransition(prevState, newState, 0, kasSpend, ${AGENT_ARGS}, policySiblings, policyPathBits, periodsElapsed);`);
P("        requireFeeReserveDomain(prevState, newState, agentMaxFeePerTx);");
P("        requireVaultGlobalPreserved(prevState, newState);");
P("    }");
P("");

// ---- ownerControl (6 selectors, one checkSig) -----------------------------
P("    /* Owner operations behind ONE entrypoint + bounded opSelector (static");
P("     * sig-ops: spend + sell + buy + ownerControl + ownerRecover = 5 <= 15).");
P("     * Owner operations NEVER move tokens and NEVER admit a foreign covenant. */");
P("    #[covenant.singleton]");
P("    function ownerControl(State prevState, State newState, int opSelector, sig ownerSig) {");
P("        require(checkSig(ownerSig, owner));");
P("        require(opSelector >= 0);");
P("        require(opSelector <= 5);");
P("        requireNoForeignCovenantInputs(this.activeInputIndex);");
P("        require(newState.boundVaultId == prevState.boundVaultId);");
P(`        require(bytes(descriptorHash) != bytes(${ZERO}));`);
P("        if (opSelector == 0) {");
P("            /* setAgentRoot: replace agentRoot; nonce +1; all else preserved */");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.swapPrincipal == prevState.swapPrincipal);");
P("            require(newState.paused == prevState.paused);");
P("            require(newState.swapRoot == prevState.swapRoot);");
P("            require(newState.policyNonce == prevState.policyNonce + 1);");
P("        } else {");
P("        if (opSelector == 1) {");
P("            /* topUpReserve: increase fee reserve only */");
P("            require(newState.feeReserve > prevState.feeReserve);");
P("            require(newState.swapPrincipal == prevState.swapPrincipal);");
P("            require(newState.paused == prevState.paused);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.swapRoot == prevState.swapRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        } else {");
P("        if (opSelector == 2) {");
P("            /* pause: paused 0 -> 1 */");
P("            require(prevState.paused == 0);");
P("            require(newState.paused == 1);");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.swapPrincipal == prevState.swapPrincipal);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.swapRoot == prevState.swapRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        } else {");
P("        if (opSelector == 3) {");
P("            /* unpause: paused 1 -> 0 */");
P("            require(prevState.paused == 1);");
P("            require(newState.paused == 0);");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.swapPrincipal == prevState.swapPrincipal);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.swapRoot == prevState.swapRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        } else {");
P("        if (opSelector == 4) {");
P("            /* setSwapRoot: replace the swap-policy root; nonce +1; all else preserved */");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.swapPrincipal == prevState.swapPrincipal);");
P("            require(newState.paused == prevState.paused);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.policyNonce == prevState.policyNonce + 1);");
P("        } else {");
P("            /* opSelector == 5 (bounded to [0,5]): fundSwapPrincipal — increase the");
P("             * protected principal only */");
P("            require(newState.swapPrincipal > prevState.swapPrincipal);");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.paused == prevState.paused);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.swapRoot == prevState.swapRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        }");
P("        }");
P("        }");
P("        }");
P("        }");
P("        requireExactSuccessorValue(newState.feeReserve + newState.swapPrincipal);");
P("    }");
P("");

// ---- ownerRecover (terminal; everything returns to the owner key) ----------
P("    /* Break-glass recovery: the controller terminates, its fee reserve AND");
P("     * swap principal pay out to the owner (output 0), and — if the position");
P("     * exists in this transaction — the ENTIRE token amount moves to the");
P("     * owner's own key (p2pk scheme) through a template-verified continuation.");
P("     * No other covenant family may be present. */");
P("    #[covenant.singleton(");
P("        mode = transition,");
P("        termination = allowed");
P("    )]");
P("    function ownerRecover(State prevState, State[] nextStates, sig ownerSig, KCC20State recipientNew) : (State[]) {");
P("        require(checkSig(ownerSig, owner));");
P("        require(nextStates.length == 0);");
P("        require(tx.outputs[0].scriptPubKey == new ScriptPubKeyP2PK(owner));");
P("        require(tx.outputs[0].value == prevState.feeReserve + prevState.swapPrincipal);");
P(`        require(bytes(descriptorHash) != bytes(${ZERO}));`);
P("        int familyInputs = OpCovInputCount(tokenCovenantId);");
P("        require(familyInputs <= 1);");
P("        if (familyInputs == 1) {");
P("            require(OpCovOutputCount(tokenCovenantId) == 1);");
P("            int tokIn = OpCovInputIdx(tokenCovenantId, 0);");
P("            requireNoForeignCovenantInputs(tokIn);");
P("            KCC20State prevTok = readInputStateWithTemplate(");
P("                tokIn,");
P("                templatePrefixLen,");
P("                templateSuffixLen,");
P("                templateVmHash");
P("            );");
P("            int sigLen = OpTxInputScriptSigLen(tokIn);");
P("            int redeemStart = sigLen - (templatePrefixLen + templateStateLen + templateSuffixLen);");
P("            byte[] templatePrefix = OpTxInputScriptSigSubstr(tokIn, redeemStart, redeemStart + templatePrefixLen);");
P("            byte[] templateSuffix = OpTxInputScriptSigSubstr(tokIn, sigLen - templateSuffixLen, sigLen);");
P("            byte[32] selfId = OpInputCovenantId(this.activeInputIndex);");
P("            require(prevTok.ownerIdentifier == selfId);");
P("            require(prevTok.identifierType == IDENTIFIER_COVENANT_ID);");
P("            require(bytes(recipientNew.ownerIdentifier) == bytes(owner));");
P("            require(recipientNew.identifierType == IDENTIFIER_PUBKEY);");
P("            require(!recipientNew.isMinter);");
P("            require(recipientNew.amount == prevTok.amount);");
P("            validateOutputStateWithTemplate(");
P("                OpCovOutputIdx(tokenCovenantId, 0),");
P("                recipientNew,");
P("                templatePrefix,");
P("                templateSuffix,");
P("                templateVmHash");
P("            );");
P("        } else {");
P("            requireNoForeignCovenantInputs(this.activeInputIndex);");
P("        }");
P("        return(nextStates);");
P("    }");
P("}");

if (!process.env.OUT) {
  console.error("set OUT to the destination path");
  process.exit(1);
}
require("fs").writeFileSync(process.env.OUT, out.join("\n") + "\n");
console.log("wrote", out.length, "lines");
