"use strict";
// Deterministic generator for contracts/PolicyVault.v0.7-payment.sil — the
// v0.7 ROOTED PAYMENT PROFILE covenant CANDIDATE (contract
// `PolicyVaultRootedToken`), docs/postlaunch/v0.7-organizational-root-design.md
// sections 3, 9.2, 9.3 and 11.
//
// THIS GENERATOR IS A DELTA, NOT A REWRITE. It READS the FROZEN
// contracts/PolicyVault.v0.5.sil, refuses to run unless that file's sha256 is
// exactly the frozen value below, and applies an explicit, ordered list of
// EXACT-MATCH edits. Every edit must match EXACTLY ONCE or the generator fails
// closed and writes nothing, so the v0.5 rules that are not named here are
// carried into v0.7 byte-for-byte by construction and a reviewer only has to
// read the deltas. The frozen file is opened READ-ONLY and is never written.
//
// v0.7 is a NEW additive covenant lineage: the frozen v0.5 controller and the
// v0.6 candidate (c7c5f22c...) are never modified, and the phase-1/phase-2
// probe covenants stay on disk as the experimental record.
//
// Reference semantics: contracts/experiments/V7RootedTokenControllerProbe2.sil
// (VM-PROBED, section 10). The candidate differs from that probe ONLY by
// naming and comments — coordinator decision D6 changes the ROOT covenant
// (contracts/PolicyVault.v0.7-root.sil), not this profile.
//
// NOT run at build/consensus time; a source-authoring tool. Byte-identical
// output (no timestamps, no randomness, no environment except OUT).
// Usage: OUT=contracts/PolicyVault.v0.7-payment.sil node tools/gen_v7_payment.js

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

/* ---------------------------------------------------------------- *
 * 1. the frozen base, verified before a single byte is transformed
 * ---------------------------------------------------------------- */

/** contracts/PolicyVault.v0.5.sil — BYTE-FROZEN, owner-authorized 2026-09-02. */
const V5_SHA256 = "c693aeffb59286d21d44452bde0943d78840b66cf480b629624b7747b4197dd9";
const V5_PATH = path.join(__dirname, "..", "contracts", "PolicyVault.v0.5.sil");

const base = fs.readFileSync(V5_PATH); // read-only; never written by this tool
const baseSha = crypto.createHash("sha256").update(base).digest("hex");
if (baseSha !== V5_SHA256) {
  console.error(
    `FAIL CLOSED: ${V5_PATH} sha256 is ${baseSha}, expected the frozen ${V5_SHA256}.\n` +
      "The v0.7 payment profile is DERIVED from the frozen v0.5 bytes; if the base drifted, " +
      "the derivation is no longer reviewable and nothing is written."
  );
  process.exit(1);
}

const ZERO = "0x" + "00".repeat(32);

/* The pinned root version's fixed-width state TAIL (see
 * contracts/PolicyVault.v0.7-root.sil and design section 9.1):
 *     byte    frozen     -> 0x01 || <0x00|0x01>    2 B
 *     byte[8] rootNonce  -> 0x08 || <8 LE bytes>   9 B  */
const ROOT_TAIL_LEN = 11;
const ROOT_FROZEN_PUSH_LEN = 2;
const ROOT_NONCE_HEADER_LEN = 1;
/* the two successor tails this vault will accept, as raw pushes */
const PUSH_UNFROZEN = "0x0100"; // the root ran AUTHORIZE  (full quorum)
const PUSH_FROZEN = "0x0101"; // the root ran FREEZE     (emergency quorum)

/* ---------------------------------------------------------------- *
 * 2. the delta
 * ---------------------------------------------------------------- */

/**
 * Every edit is {name, from, to}. `from` must occur EXACTLY ONCE in the
 * current text or the generator aborts; the replacement is applied in order.
 * Insertions are expressed as replacements whose `to` re-emits `from` — that
 * way the anchor itself is verified too.
 */
const EDITS = [];
const edit = (name, from, to) => EDITS.push({ name, from, to });

/* --- E1. header, contract name, and the REMOVAL of `pubkey owner` ----- */

const V5_HEADER_AND_SIGNATURE = `/*
 * PolicyVault v0.5 — TOKEN CONTROLLER covenant (docs/postlaunch/v0.5-design-freeze.md).
 *
 * A NEW covenant lineage beside the frozen v0.4.1 KAS vault: one instance
 * per (vault, accepted asset descriptor, accepted template). The instance
 * OWNS a KCC20 token position through the KCC-0002 covenant-id/v1 owner
 * scheme and authorizes delegated token spends under TOKEN-denominated
 * per-agent policy, while its own KAS is exclusively a FEE RESERVE.
 *`;

const V7_HEADER = `/*
 * PolicyVault v0.7-payment — ROOTED PAYMENT PROFILE covenant CANDIDATE
 * (docs/postlaunch/v0.7-organizational-root-design.md sections 3, 9.2, 9.3).
 *
 * GENERATED by tools/gen_v7_payment.js as an EXACT-MATCH DELTA over the
 * FROZEN contracts/PolicyVault.v0.5.sil (sha256
 * ${V5_SHA256}),
 * which is never modified. Every v0.5 rule not named in the delta below is
 * carried here byte-for-byte: dual binding A/B, TRANSACTION-DERIVED VERIFIED
 * TEMPLATE CARRIAGE, token-denominated agent leaves, exact conservation, the
 * KAS fee-reserve domain (FR-1) and break-glass recovery.
 *
 * WHAT CHANGES, AND ONLY THIS:
 *   - the template constant \`pubkey owner\` is REMOVED. This vault has NO
 *     owner key and NO owner signature check anywhere. Its owner AUTHORITY is
 *     the ORGANIZATIONAL ROOT covenant (contracts/PolicyVault.v0.7-root.sil):
 *     an owner operation is valid only if the same transaction ALSO spends
 *     the pinned root, whose own script proved M-of-N (or the lighter
 *     emergency quorum for a FREEZE);
 *   - added template constants pin that root: \`orgRootCovenantId\`, its
 *     template identity \`rootTemplateVmHash\` = blake2b-256(prefix || suffix),
 *     its geometry \`rootPrefixLen\` / \`rootStateLen\` / \`rootSuffixLen\`, and
 *     \`recoveryPk\`, the cold recovery destination fixed at genesis so a
 *     hijacked quorum-signing session cannot redirect recovery;
 *   - \`requireRootAuthorization(expectFrozenPush)\` pins the root's EXACT
 *     SUCCESSOR BYTES, so this vault can tell WHICH root path ran;
 *   - \`ownerControl\` and the phase-1 \`emergencyPause\` are MERGED behind one
 *     bounded selector 0..4, so the root-authorization block is inlined ONCE
 *     on that path; \`ownerRecover\` stays a separate termination-mode
 *     entrypoint and is the second and last inline site;
 *   - \`require(periodLengthDaa > 0)\` (deviation D2) hardens the agent path.
 *
 * WHY BYTES AND NOT FIELDS. SilverScript inlines a function at every call
 * site and a P2SH spend reveals the WHOLE redeem, so anything the owner path
 * does is carried by every DELEGATE transaction forever. Decoding and
 * re-encoding the root's 18-field state cost +6,194 B on every delegate spend
 * (measured, section 7.5). Treating the root's head as an OPAQUE SLICE that
 * must be reproduced verbatim is strictly stronger (it pins the field
 * ENCODING as well as the values) and costs +363 B (section 10.4).
 *
 * Static sig-ops in this redeem: 1 (the agent). The v0.5 profile had 3.
 *`;

edit(
  "E1 header + contract name + REMOVE `pubkey owner`",
  `${V5_HEADER_AND_SIGNATURE}
 * DUAL BINDING`,
  `${V7_HEADER}
 * DUAL BINDING`
);

edit(
  "E1b contract declaration drops `pubkey owner`",
  `contract PolicyVaultToken(
    pubkey owner,
    byte[32] vaultId,`,
  `contract PolicyVaultRootedToken(
    byte[32] vaultId,`
);

edit(
  "E1c immutable-template doc line drops `owner`",
  ` * Immutable template: owner, vaultId, descriptorHash (the accepted`,
  ` * Immutable template: vaultId, descriptorHash (the accepted`
);

/* --- E2. the root pins join the immutable template constants --------- */

edit(
  "E2 root template constants",
  `    int templateSuffixLen,
    byte[32] initAgentRoot,`,
  `    int templateSuffixLen,
    byte[32] orgRootCovenantId,
    byte[32] rootTemplateVmHash,
    int rootPrefixLen,
    int rootStateLen,
    int rootSuffixLen,
    pubkey recoveryPk,
    byte[32] initAgentRoot,`
);

/* --- E3. the root-authorization block + the two generalised closures -- */

const ROOT_BLOCK = `    /* The pinned root version's fixed-width state TAIL:
     *     byte    frozen     -> 0x01 || <0x00|0x01>   2 B
     *     byte[8] rootNonce  -> 0x08 || <8 LE bytes>  9 B
     * The tail geometry is not an independent trust input: rootTemplateVmHash
     * already pins the EXACT root script (and therefore its exact field
     * layout), so this constant only names an offset inside bytes that are
     * already proven to belong to the pinned root template. */
    int constant ROOT_TAIL_LEN = ${ROOT_TAIL_LEN};
    int constant ROOT_FROZEN_PUSH_LEN = ${ROOT_FROZEN_PUSH_LEN};
    int constant ROOT_NONCE_HEADER_LEN = ${ROOT_NONCE_HEADER_LEN};

    /* THE ONLY OWNER AUTHORITY IN THIS VAULT (design section 9.2).
     *
     * There is no owner key and no owner signature: an owner operation is
     * valid only if the transaction ALSO spends the pinned organizational
     * root, whose own covenant proved M-of-N (or the lighter emergency
     * quorum for FREEZE). The root's EXACT successor BYTES are pinned here,
     * so this vault can tell WHICH root path ran:
     *   expectFrozenPush = ${PUSH_UNFROZEN} -> the root ran AUTHORIZE (full quorum)
     *   expectFrozenPush = ${PUSH_FROZEN} -> the root ran FREEZE (emergency quorum)
     * Any other root path (ROTATE, UNFREEZE, OWNER-RECOVER, SUCCESSION)
     * changes the HEAD or the frozen byte, so the rebuilt successor redeem no
     * longer hashes to the root output's scriptPubKey and the vault operation
     * is invalid. Rotation and vault operations are therefore separate
     * transactions by construction. (Root decision D6 makes OWNER-RECOVER
     * land FROZEN, so a recovery can never satisfy a GENERAL owner path.)
     *
     * Nothing is trusted before it is proven. Steps 1-2 are exactly the two
     * checks readInputStateWithTemplate performs (the P2SH commitment of the
     * revealed redeem to the input's own scriptPubKey, then the template
     * identity); only then are the sliced tail bytes read. */
    function requireRootAuthorization(byte[] expectFrozenPush) {
        require(OpCovInputCount(orgRootCovenantId) == 1);
        require(OpCovOutputCount(orgRootCovenantId) == 1);
        int rootIn = OpCovInputIdx(orgRootCovenantId, 0);

        /* 1. slice the claimed redeem out of the root input's signature
         *    script (TRANSACTION-DERIVED VERIFIED TEMPLATE CARRIAGE, the
         *    frozen v0.5 technique) and BIND it to that input's P2SH
         *    scriptPubKey, so the bytes below are the bytes consensus is
         *    actually executing on that input. */
        int rootSigLen = OpTxInputScriptSigLen(rootIn);
        int rootRedeemStart = rootSigLen - (rootPrefixLen + rootStateLen + rootSuffixLen);
        byte[] rootRedeem = OpTxInputScriptSigSubstr(rootIn, rootRedeemStart, rootSigLen);
        require(tx.inputs[rootIn].scriptPubKey == new ScriptPubKeyP2SHFromRedeemScript(rootRedeem));

        /* 2. split the proven redeem by the pinned geometry and require the
         *    template identity blake2b-256(prefix || suffix) to be the root
         *    template pinned at this vault's genesis. */
        (byte[] rootPrefix, byte[] rootAfterPrefix) = rootRedeem.split(rootPrefixLen);
        (byte[] rootHead, byte[] rootAfterHead) = rootAfterPrefix.split(rootStateLen - ROOT_TAIL_LEN);
        (byte[] rootTailPrev, byte[] rootSuffix) = rootAfterHead.split(ROOT_TAIL_LEN);
        require(blake2b(rootPrefix + rootSuffix) == rootTemplateVmHash);

        /* 3. the root must NOT be frozen, and its nonce is read from the
         *    proven tail. */
        (byte[] prevFrozenPush, byte[] prevNoncePush) = rootTailPrev.split(ROOT_FROZEN_PUSH_LEN);
        require(prevFrozenPush == bytes(${PUSH_UNFROZEN}));
        (byte[] prevNonceHeader, byte[] prevNonceBody) = prevNoncePush.split(ROOT_NONCE_HEADER_LEN);
        require(prevNonceHeader == bytes(0x08));

        /* 4. rebuild the ONE successor redeem this vault accepts: the same
         *    prefix, the same head (so no owner slot, threshold, emergency
         *    quorum, recovery quorum or organization id may move), the
         *    demanded frozen byte, the nonce advanced by exactly one, the
         *    same suffix — and require the root's continuation output to
         *    commit to precisely those bytes. */
        byte[] rootTailNew = expectFrozenPush + bytes(0x08) + OpNum2Bin(int(prevNonceBody) + 1, 8);
        byte[] rootExpectedRedeem = rootPrefix + rootHead + rootTailNew + rootSuffix;
        int rootOut = OpCovOutputIdx(orgRootCovenantId, 0);
        require(tx.outputs[rootOut].scriptPubKey == new ScriptPubKeyP2SHFromRedeemScript(rootExpectedRedeem));
    }

    /* BINDING A generalised for OWNER paths: every input other than this
     * covenant and the pinned ROOT family must be a PLAIN input.
     *
     * DEVIATION D9 (code size only): the two 32-byte comparands are bound to
     * locals BEFORE the loop. The compiler unrolls \`for (i, 0, inCount, 8)\`
     * to its compile-time bound, so an inline literal inside the body is
     * emitted as a 33-byte data push EIGHT times; hoisting makes each
     * reference a stack access instead. The compared values and the rule are
     * identical. */
    function requireOnlyRootCovenantInputs() {
        int inCount = tx.inputs.length;
        require(inCount >= 1);
        require(inCount <= 8);
        byte[32] rootCid = orgRootCovenantId;
        byte[32] plainCid = ${ZERO};
        for (i, 0, inCount, 8) {
            if (i != this.activeInputIndex) {
                byte[32] cid = OpInputCovenantId(i);
                if (cid != rootCid) {
                    require(bytes(cid) == bytes(plainCid));
                }
            }
        }
    }

    /* BINDING A generalised for RECOVERY: this covenant, the pinned ROOT
     * family and the pinned TOKEN family — nothing else. */
    function requireOnlyRootAndTokenCovenantInputs(int tokIn) {
        int inCount = tx.inputs.length;
        require(inCount >= 1);
        require(inCount <= 8);
        byte[32] rootCid = orgRootCovenantId;
        byte[32] plainCid = ${ZERO};
        for (i, 0, inCount, 8) {
            if (i != this.activeInputIndex) {
                if (i != tokIn) {
                    byte[32] cid = OpInputCovenantId(i);
                    if (cid != rootCid) {
                        require(bytes(cid) == bytes(plainCid));
                    }
                }
            }
        }
    }
`;

edit(
  "E3 ROOT_TAIL constants + requireRootAuthorization + the two generalised family closures",
  `    byte constant IDENTIFIER_COVENANT_ID = 0x02;

    /* Exact single authorized successor value at the auth output. */`,
  `    byte constant IDENTIFIER_COVENANT_ID = 0x02;

${ROOT_BLOCK}
    /* Exact single authorized successor value at the auth output. */`
);

/* --- E4. deviation D2 — the zero-length-period hardening ------------- */

edit(
  "E4 D2 require(periodLengthDaa > 0) at the top of requireTokenAgentTransition",
  `        int periodsElapsed
    ) {
        require(spendAmount <= tokenMaxPerSpend);`,
  `        int periodsElapsed
    ) {
        /* DEVIATION D2 (v0.6 adversarial review, finding F1): a zero-length
         * period makes the period budget VACUOUS. With periodLengthDaa == 0
         * and periodsElapsed >= 1 the rollover branch computes
         * newStart == periodStartDaa, so \`tx.time >= newStart\` holds inside
         * the SAME period and newSpent resets to spendAmount — the agent can
         * drain the position one cap-sized spend at a time without the period
         * ever ending. The frozen v0.3-v0.6 covenants lack this check (their
         * leaves are owner-committed, so it is an owner-misconfiguration
         * hazard, not a delegate escalation) and those frozen files are NEVER
         * modified; the new generation rejects the degenerate parameter at
         * consensus. */
        require(periodLengthDaa > 0);
        require(spendAmount <= tokenMaxPerSpend);`
);

/* --- E5. ownerControl: root authority + the merged selector 0..4 ------ */

edit(
  "E5 ownerControl header, signature and authority",
  `    /* Owner operations behind ONE entrypoint + bounded opSelector (v0.4.1
     * standardness pattern; static sig-ops: 1 tokenAgentSpend + 1 ownerControl
     * + 1 ownerRecover = 3 <= 15). Owner operations NEVER move tokens: no
     * covenant input other than this one may be present. The successor
     * state is pinned by the signed covenant output; mutually exclusive
     * per-selector rules make a substituted selector reject. */
    #[covenant.singleton]
    function ownerControl(State prevState, State newState, int opSelector, sig ownerSig) {
        require(checkSig(ownerSig, owner));
        require(opSelector >= 0);
        require(opSelector <= 3);
        requireNoForeignCovenantInputs(this.activeInputIndex);`,
  `    /* ALL non-terminal owner operations behind ONE entrypoint + a bounded
     * opSelector (design section 9.3; the v0.4.1 standardness pattern).
     * Merging what phase 1 split across ownerControl and emergencyPause
     * leaves exactly ONE inline site of the root-authorization block on this
     * path — the lever the phase-1 cost measurement identified.
     *
     * In v0.7 the AUTHORITY is the organizational root input, not an owner
     * key: static sig-ops here are ZERO. Owner operations NEVER move tokens:
     * no covenant input other than this one and the root may be present. The
     * successor state is pinned by the covenant output; mutually exclusive
     * per-selector rules make a substituted selector reject.
     *
     *   0 setAgentRoot   1 topUpReserve   2 pause   3 unpause   full quorum
     *   4 EMERGENCY pause                                  emergency quorum
     *
     * Selector 4 is the ONLY vault effect reachable from the root's LIGHTER
     * emergency quorum: AUTHORITY-REDUCING and monotone (paused 0 -> 1, every
     * other field preserved, policyNonce included, no value movement).
     * Unpausing is selector 3 and needs the FULL quorum. Selectors 0-3 pin an
     * AUTHORIZE root successor and selector 4 pins a FREEZE one, so an
     * emergency quorum can reach nothing but the pause. */
    #[covenant.singleton]
    function ownerControl(State prevState, State newState, int opSelector) {
        require(opSelector >= 0);
        require(opSelector <= 4);
        byte[] expectFrozenPush = bytes(${PUSH_UNFROZEN});
        if (opSelector == 4) {
            expectFrozenPush = bytes(${PUSH_FROZEN});
        }
        requireRootAuthorization(expectFrozenPush);
        requireOnlyRootCovenantInputs();`
);

edit(
  "E5b selector 2 is the FULL-quorum pause",
  `            /* pause: paused 0 -> 1 */`,
  `            /* pause (full quorum): paused 0 -> 1 */`
);

edit(
  "E5c selector 3 becomes an explicit branch and selector 4 is added",
  `        } else {
            /* opSelector == 3 (bounded to [0,3]): unpause 1 -> 0 */
            require(prevState.paused == 1);
            require(newState.paused == 0);
            require(newState.feeReserve == prevState.feeReserve);
            require(newState.agentRoot == prevState.agentRoot);
            require(newState.policyNonce == prevState.policyNonce);
        }
        }
        }
        requireExactSuccessorValue(newState.feeReserve);
    }`,
  `        } else {
        if (opSelector == 3) {
            /* unpause (full quorum): paused 1 -> 0 */
            require(prevState.paused == 1);
            require(newState.paused == 0);
            require(newState.feeReserve == prevState.feeReserve);
            require(newState.agentRoot == prevState.agentRoot);
            require(newState.policyNonce == prevState.policyNonce);
        } else {
            /* opSelector == 4 (bounded to [0,4]): EMERGENCY pause under a
             * FREEZE root successor. Identical state effect to selector 2,
             * different and strictly lighter root authority. */
            require(prevState.paused == 0);
            require(newState.paused == 1);
            require(newState.feeReserve == prevState.feeReserve);
            require(newState.agentRoot == prevState.agentRoot);
            require(newState.policyNonce == prevState.policyNonce);
        }
        }
        }
        }
        requireExactSuccessorValue(newState.feeReserve);
    }`
);

/* --- E6. ownerRecover: root authority + the genesis-pinned destination */

edit(
  "E6 ownerRecover header, signature, authority and pinned destination",
  `    /* Break-glass recovery: the controller terminates, its fee reserve pays
     * out to the owner (output 0), and — if the position exists in this
     * transaction — the ENTIRE token amount moves to the owner's own key
     * (p2pk scheme) through a template-verified continuation, so tokens can
     * never be stranded under a dissolved covenant id. No other covenant
     * family may be present. */
    #[covenant.singleton(
        mode = transition,
        termination = allowed
    )]
    function ownerRecover(State prevState, State[] nextStates, sig ownerSig, KCC20State recipientNew) : (State[]) {
        require(checkSig(ownerSig, owner));
        require(nextStates.length == 0);
        require(tx.outputs[0].scriptPubKey == new ScriptPubKeyP2PK(owner));`,
  `    /* Break-glass recovery: the controller terminates, its fee reserve pays
     * out to the GENESIS-PINNED cold destination recoveryPk (output 0), and
     * — if the position exists in this transaction — the ENTIRE token amount
     * moves to recoveryPk (p2pk scheme) through a template-verified
     * continuation, so tokens can never be stranded under a dissolved
     * covenant id. The destination is a template constant, so a hijacked
     * quorum-signing session cannot redirect recovery. Authority is the
     * root's FULL quorum (AUTHORIZE). No covenant family other than the root
     * and the pinned token family may be present. TERMINAL. */
    #[covenant.singleton(
        mode = transition,
        termination = allowed
    )]
    function ownerRecover(State prevState, State[] nextStates, KCC20State recipientNew) : (State[]) {
        requireRootAuthorization(bytes(${PUSH_UNFROZEN}));
        require(nextStates.length == 0);
        require(tx.outputs[0].scriptPubKey == new ScriptPubKeyP2PK(recoveryPk));`
);

edit(
  "E6b recovery family closure admits the root family",
  `            requireNoForeignCovenantInputs(tokIn);`,
  `            requireOnlyRootAndTokenCovenantInputs(tokIn);`
);

edit(
  "E6c the recovered token position is owned by recoveryPk",
  `            require(bytes(recipientNew.ownerIdentifier) == bytes(owner));`,
  `            require(bytes(recipientNew.ownerIdentifier) == bytes(recoveryPk));`
);

edit(
  "E6d the token-free recovery branch admits the root family",
  `        } else {
            requireNoForeignCovenantInputs(this.activeInputIndex);
        }
        return(nextStates);`,
  `        } else {
            requireOnlyRootCovenantInputs();
        }
        return(nextStates);`
);

/* ---------------------------------------------------------------- *
 * 3. apply — every edit must match exactly once, or nothing is written
 * ---------------------------------------------------------------- */

let text = base.toString("utf8");
for (const { name, from, to } of EDITS) {
  const count = text.split(from).length - 1;
  if (count !== 1) {
    console.error(
      `FAIL CLOSED: edit "${name}" matched ${count} times, expected exactly 1.\n` +
        "A v0.7 delta that does not apply exactly once is not a reviewable derivation; nothing is written."
    );
    process.exit(1);
  }
  text = text.replace(from, to);
}

/* Post-conditions the delta must have achieved (cheap, mechanical, and they
 * fail closed): no owner key, no owner signature anywhere, both root call
 * sites present, the D2 hardening present. */
const MUST_BE_ABSENT = [
  ["pubkey owner,", "the removed owner template constant"],
  ["sig ownerSig", "an owner signature argument"],
  ["checkSig(ownerSig", "an owner signature check"],
  ["ScriptPubKeyP2PK(owner)", "a recovery payout to the removed owner key"],
];
for (const [needle, what] of MUST_BE_ABSENT) {
  if (text.includes(needle)) {
    console.error(`FAIL CLOSED: ${what} survived the delta (${JSON.stringify(needle)}).`);
    process.exit(1);
  }
}
const MUST_APPEAR = [
  ["contract PolicyVaultRootedToken(", 1],
  ["function requireRootAuthorization(byte[] expectFrozenPush) {", 1],
  ["        requireRootAuthorization(expectFrozenPush);", 1],
  [`        requireRootAuthorization(bytes(${PUSH_UNFROZEN}));`, 1],
  ["        require(periodLengthDaa > 0);", 1],
  ["    function requireOnlyRootCovenantInputs() {", 1],
  ["    function requireOnlyRootAndTokenCovenantInputs(int tokIn) {", 1],
  /* the agent path keeps the FROZEN v0.5 family closure verbatim */
  ["        requireNoForeignCovenantInputs(tokIn);", 1],
];
for (const [needle, want] of MUST_APPEAR) {
  const got = text.split(needle).length - 1;
  if (got !== want) {
    console.error(`FAIL CLOSED: expected ${want} occurrence(s) of ${JSON.stringify(needle)}, found ${got}.`);
    process.exit(1);
  }
}

if (!process.env.OUT) {
  console.error("set OUT to the destination path");
  process.exit(1);
}
fs.writeFileSync(process.env.OUT, text);
console.log(
  "wrote",
  text.split("\n").length - 1,
  "lines from the frozen v0.5 base",
  `(${V5_SHA256.slice(0, 8)}...)`,
  "via",
  EDITS.length,
  "exact-match edits"
);
