"use strict";
// Deterministic generator for contracts/PolicyVault.v0.5.sil — the v0.5
// TOKEN CONTROLLER covenant (docs/postlaunch/v0.5-design-freeze.md). A NEW
// lineage beside the frozen v0.4/v0.4.1 KAS vault covenants, which this
// file never touches. NOT run at build/consensus time; a source-authoring
// tool. Byte-identical output (no timestamps/randomness).
// Usage: OUT=contracts/PolicyVault.v0.5.sil node tools/gen_v5.js
const AGENT_MAX_DEPTH = 12; // token-agent policy tree
const AGENT_MAX_SIB = AGENT_MAX_DEPTH * 32; // 384
const RECIP_MAX_DEPTH = 16; // recipient tree (v0.3 leaf format)
const RECIP_MAX_SIB = RECIP_MAX_DEPTH * 32; // 512
const MAX_TX_IO = 8;
const ZERO = "0x" + "00".repeat(32);
const out = [];
const P = (s = "") => out.push(s);

P("pragma silverscript ^0.1.0;");
P("");
P("/*");
P(" * PolicyVault v0.5 — TOKEN CONTROLLER covenant (docs/postlaunch/v0.5-design-freeze.md).");
P(" *");
P(" * A NEW covenant lineage beside the frozen v0.4.1 KAS vault: one instance");
P(" * per (vault, accepted asset descriptor, accepted template). The instance");
P(" * OWNS a KCC20 token position through the KCC-0002 covenant-id/v1 owner");
P(" * scheme and authorizes delegated token spends under TOKEN-denominated");
P(" * per-agent policy, while its own KAS is exclusively a FEE RESERVE.");
P(" *");
P(" * DUAL BINDING (non-negotiable; either failing fails closed):");
P(" *   A. controller/covenant-id authorization — the token family in the");
P(" *      transaction is exactly the PINNED tokenCovenantId, located by family");
P(" *      enumeration with exact family counts (hidden-extra-output defense),");
P(" *      and NO other covenant family may ride the controller's presence");
P(" *      (every other input must be a plain, non-covenant input);");
P(" *   B. hash-verified template/output identity — TRANSACTION-DERIVED");
P(" *      VERIFIED TEMPLATE CARRIAGE: the controller pins the accepted");
P(" *      template's in-VM identity blake2b-256(prefix || suffix) AND its");
P(" *      geometry (prefix/state/suffix lengths; the hash is unframed),");
P(" *      proves the token INPUT's revealed redeem against both (hash + P2SH,");
P(" *      readInputStateWithTemplate) BEFORE trusting its state, slices the");
P(" *      now-proven prefix/suffix out of that input's signature script, and");
P(" *      reconstructs every continuation output from them");
P(" *      (validateOutputStateWithTemplate re-verifies the hash at use).");
P(" *      Template bytes are NEVER baked into this redeem and NEVER supplied");
P(" *      by the caller.");
P(" *");
P(" * TWO ACCOUNTING DOMAINS: token value lives in the token UTXO and is");
P(" * conserved by exact state arithmetic (selfNew + recipient == prev); the");
P(" * controller UTXO holds ONLY the KAS fee reserve (FR-1: reserve can only");
P(" * ever become network fee, bounded per agent by agentMaxFeePerTx and by");
P(" * the exact fee); the token family's own KAS never leaks except to the");
P(" * recipient's bounded carry (agentMaxCarryKas).");
P(" *");
P(" * Immutable template: owner, vaultId, descriptorHash (the accepted");
P(" * descriptor's pinned hash — application identity readable from the");
P(" * revealed redeem; not evaluated in-VM), tokenCovenantId, templateVmHash,");
P(" * templatePrefixLen/StateLen/SuffixLen. Mutable state (5 fields):");
P(" * boundVaultId, feeReserve, paused, agentRoot, policyNonce.");
P(" *");
P(" * Token-agent policy leaf (125-byte preimage, distinct from every other");
P(" * PolicyVault leaf length 124/36/64):");
P(" *   sha256(0x50563501 || agentPk || num8(tokenMaxPerSpend) ||");
P(" *          num8(tokenPeriodBudget) || num8(periodLengthDaa) ||");
P(" *          num8(periodStartDaa) || num8(tokenPeriodSpent) ||");
P(" *          num8(agentMaxFeePerTx) || num8(agentMaxCarryKas) ||");
P(" *          recipientRoot || 0x00)   -- trailing byte = recipient scheme (0x00 p2pk only)");
P(" * Recipient leaf = sha256(0x50563301 || recipientPk) (v0.3, 36 bytes).");
P(` * Agent proof depth <= ${AGENT_MAX_DEPTH}; recipient proof depth <= ${RECIP_MAX_DEPTH}.`);
P(" *");
P(" * Security boundary: Kaspa consensus. A holder of a legitimate agent key");
P(" * bypassing the app and submitting directly to a node is bounded by every");
P(" * rule below.");
P(" */");
P("contract PolicyVaultToken(");
P("    pubkey owner,");
P("    byte[32] vaultId,");
P("    byte[32] descriptorHash,");
P("    byte[32] tokenCovenantId,");
P("    byte[32] templateVmHash,");
P("    int templatePrefixLen,");
P("    int templateStateLen,");
P("    int templateSuffixLen,");
P("    byte[32] initAgentRoot,");
P("    int initFeeReserve");
P(") {");
P("    byte[32] boundVaultId = vaultId;");
P("    int feeReserve = initFeeReserve;");
P("    int paused = 0;");
P("    byte[32] agentRoot = initAgentRoot;");
P("    int policyNonce = 0;");
P("");
P("    struct KCC20State {");
P("        byte[32] ownerIdentifier;");
P("        byte identifierType;");
P("        int amount;");
P("        bool isMinter;");
P("    }");
P("");
P("    byte constant IDENTIFIER_PUBKEY = 0x00;");
P("    byte constant IDENTIFIER_COVENANT_ID = 0x02;");
P("");
P("    /* Exact single authorized successor value at the auth output. */");
P("    function requireExactSuccessorValue(int exactValue) {");
P("        int successorIndex = OpAuthOutputIdx(this.activeInputIndex, 0);");
P("        require(tx.outputs[successorIndex].value == exactValue);");
P("    }");
P("");
P("    /* Vault-global fields preserved across a token spend (feeReserve and");
P("     * agentRoot move by rule). The descriptor pin is a template constant;");
P("     * referencing it keeps it in the revealed redeem for verifiers. */");
P("    function requireVaultGlobalPreserved(State prevState, State newState) {");
P("        require(newState.boundVaultId == prevState.boundVaultId);");
P("        require(newState.paused == prevState.paused);");
P("        require(newState.policyNonce == prevState.policyNonce);");
P(`        require(bytes(descriptorHash) != bytes(${ZERO}));`);
P("    }");
P("");
P("    /* BINDING A (family isolation): every input other than this covenant");
P("     * and the pinned token-family input must be a PLAIN input (zero");
P("     * covenant id), so no other covenant family — including a different");
P("     * asset deposited to this controller's id — can be authorized by the");
P(`     * controller's mere presence. Bounded to <= ${MAX_TX_IO} inputs. */`);
P("    function requireNoForeignCovenantInputs(int tokIn) {");
P("        int inCount = tx.inputs.length;");
P("        require(inCount >= 1);");
P(`        require(inCount <= ${MAX_TX_IO});`);
P(`        for (i, 0, inCount, ${MAX_TX_IO}) {`);
P("            if (i != this.activeInputIndex) {");
P("                if (i != tokIn) {");
P(`                    require(bytes(OpInputCovenantId(i)) == bytes(${ZERO}));`);
P("                }");
P("            }");
P("        }");
P("    }");
P("");
P("    /* Canonical token-agent policy leaf (125-byte preimage, frozen). */");
P("    function tokenAgentLeaf(");
P("        pubkey agentPk,");
P("        int tokenMaxPerSpend,");
P("        int tokenPeriodBudget,");
P("        int periodLengthDaa,");
P("        int periodStartDaa,");
P("        int tokenPeriodSpent,");
P("        int agentMaxFeePerTx,");
P("        int agentMaxCarryKas,");
P("        byte[32] recipientRoot");
P("    ) : (byte[]) {");
P("        byte[] leaf = bytes(sha256(");
P("            bytes(0x50563501)");
P("            + bytes(agentPk)");
P("            + OpNum2Bin(tokenMaxPerSpend, 8)");
P("            + OpNum2Bin(tokenPeriodBudget, 8)");
P("            + OpNum2Bin(periodLengthDaa, 8)");
P("            + OpNum2Bin(periodStartDaa, 8)");
P("            + OpNum2Bin(tokenPeriodSpent, 8)");
P("            + OpNum2Bin(agentMaxFeePerTx, 8)");
P("            + OpNum2Bin(agentMaxCarryKas, 8)");
P("            + bytes(recipientRoot)");
P("            + bytes(0x00)");
P("        ));");
P("        return leaf;");
P("    }");
P("");
P("    /* Single-leaf Merkle fold over a co-path (FUNDS-CRITICAL; v0.4 mechanism,");
P(`     * VM-proven). depth <= ${AGENT_MAX_DEPTH}. */`);
P("    function computeMerkleRoot(byte[] leaf, byte[] siblings, int pathBits) : (byte[]) {");
P("        require(siblings.length % 32 == 0);");
P(`        require(siblings.length <= ${AGENT_MAX_SIB});`);
P("        int depth = siblings.length / 32;");
P("        require(pathBits >= 0);");
P(`        require(pathBits < ${1 << AGENT_MAX_DEPTH});`);
P("        byte[] node = leaf;");
P("        byte[] rest = siblings;");
P("        int bits = pathBits;");
P(`        for (level, 0, depth, ${AGENT_MAX_DEPTH}) {`);
P("            (byte[] sib, byte[] tail) = rest.split(32);");
P("            rest = tail;");
P("            if (bits % 2 == 1) {");
P("                node = bytes(sha256(sib + node));");
P("            } else {");
P("                node = bytes(sha256(node + sib));");
P("            }");
P("            bits = bits / 2;");
P("        }");
P("        require(bits == 0);");
P("        return node;");
P("    }");
P("");
P("    function requireAgentMembership(byte[32] root, byte[] oldLeaf, byte[] siblings, int pathBits) {");
P("        (byte[] oldRoot) = computeMerkleRoot(oldLeaf, siblings, pathBits);");
P("        require(oldRoot == bytes(root));");
P("    }");
P("");
P("    /* Authenticate the token-agent leaf, advance its TOKEN accounting, and");
P("     * pin the successor agentRoot — one helper frame (stack discipline). */");
P("    function requireTokenAgentTransition(");
P("        State prevState,");
P("        State newState,");
P("        int spendAmount,");
P("        pubkey agentPk,");
P("        int tokenMaxPerSpend,");
P("        int tokenPeriodBudget,");
P("        int periodLengthDaa,");
P("        int periodStartDaa,");
P("        int tokenPeriodSpent,");
P("        int agentMaxFeePerTx,");
P("        int agentMaxCarryKas,");
P("        byte[32] agentRecipientRoot,");
P("        byte[] policySiblings,");
P("        int policyPathBits,");
P("        int periodsElapsed");
P("    ) {");
P("        require(spendAmount <= tokenMaxPerSpend);");
P("        require(periodsElapsed >= 0);");
P("        require(periodsElapsed <= 1000);");
P("        int newStart = periodStartDaa;");
P("        int newSpent = tokenPeriodSpent + spendAmount;");
P("        if (periodsElapsed >= 1) {");
P("            newStart = periodStartDaa + periodsElapsed * periodLengthDaa;");
P("            require(tx.time >= newStart);");
P("            newSpent = spendAmount;");
P("        }");
P("        require(newSpent <= tokenPeriodBudget);");
P("        (byte[] oldLeaf) = tokenAgentLeaf(agentPk, tokenMaxPerSpend, tokenPeriodBudget, periodLengthDaa, periodStartDaa, tokenPeriodSpent, agentMaxFeePerTx, agentMaxCarryKas, agentRecipientRoot);");
P("        requireAgentMembership(prevState.agentRoot, oldLeaf, policySiblings, policyPathBits);");
P("        (byte[] newLeaf) = tokenAgentLeaf(agentPk, tokenMaxPerSpend, tokenPeriodBudget, periodLengthDaa, newStart, newSpent, agentMaxFeePerTx, agentMaxCarryKas, agentRecipientRoot);");
P("        (byte[] newRoot) = computeMerkleRoot(newLeaf, policySiblings, policyPathBits);");
P("        require(bytes(newState.agentRoot) == newRoot);");
P("    }");
P("");
P("    /* Recipient membership under the LEAF's own recipient root (v0.3 leaf).");
P("     * The recipient is bound to the TOKEN output's owner identifier by the");
P(`     * caller, not to a KAS output. Depth <= ${RECIP_MAX_DEPTH}. */`);
P("    function requireAgentRecipient(byte[32] root, pubkey recipientPk, byte[] siblings, int pathBits) {");
P("        require(siblings.length % 32 == 0);");
P(`        require(siblings.length <= ${RECIP_MAX_SIB});`);
P("        int depth = siblings.length / 32;");
P("        require(pathBits >= 0);");
P(`        require(pathBits < ${1 << RECIP_MAX_DEPTH});`);
P("        byte[] node = bytes(sha256(bytes(0x50563301) + bytes(recipientPk)));");
P("        byte[] rest = siblings;");
P("        int bits = pathBits;");
P(`        for (level, 0, depth, ${RECIP_MAX_DEPTH}) {`);
P("            (byte[] sib, byte[] tail) = rest.split(32);");
P("            rest = tail;");
P("            if (bits % 2 == 1) {");
P("                node = bytes(sha256(sib + node));");
P("            } else {");
P("                node = bytes(sha256(node + sib));");
P("            }");
P("            bits = bits / 2;");
P("        }");
P("        require(bits == 0);");
P("        require(node == bytes(root));");
P("    }");
P("");
P("    /* Exact network fee from full input/output value introspection.");
P(`     * Bounded to <= ${MAX_TX_IO} inputs and <= ${MAX_TX_IO} outputs. */`);
P("    function txFee() : (int) {");
P("        int inCount = tx.inputs.length;");
P("        require(inCount >= 1);");
P(`        require(inCount <= ${MAX_TX_IO});`);
P("        int outCount = tx.outputs.length;");
P("        require(outCount >= 1);");
P(`        require(outCount <= ${MAX_TX_IO});`);
P("        int totalIn = 0;");
P(`        for (i, 0, inCount, ${MAX_TX_IO}) {`);
P("            totalIn = totalIn + tx.inputs[i].value;");
P("        }");
P("        int totalOut = 0;");
P(`        for (j, 0, outCount, ${MAX_TX_IO}) {`);
P("            totalOut = totalOut + tx.outputs[j].value;");
P("        }");
P("        require(totalOut <= totalIn);");
P("        int fee = totalIn - totalOut;");
P("        return fee;");
P("    }");
P("");
P("    /* KAS DOMAIN (separate from token value):");
P("     *  - the token family's own KAS never leaks: self + recipient carry >=");
P("     *    the token input's KAS, and the recipient's carry is capped by the");
P("     *    agent's agentMaxCarryKas;");
P("     *  - the controller's KAS is exclusively fee reserve (FR-1): reserve");
P("     *    consumed is >= 0, <= agentMaxFeePerTx, <= the exact fee; the");
P("     *    successor carries exactly newState.feeReserve. */");
P("    function requireKasDomains(State prevState, State newState, int tokIn, int agentMaxFeePerTx, int agentMaxCarryKas) {");
P("        int selfOut = OpCovOutputIdx(tokenCovenantId, 0);");
P("        int recipientOut = OpCovOutputIdx(tokenCovenantId, 1);");
P("        require(tx.outputs[selfOut].value + tx.outputs[recipientOut].value >= tx.inputs[tokIn].value);");
P("        require(tx.outputs[recipientOut].value <= agentMaxCarryKas);");
P("        require(newState.feeReserve >= 0);");
P("        int reserveConsumed = prevState.feeReserve - newState.feeReserve;");
P("        require(reserveConsumed >= 0);");
P("        require(reserveConsumed <= agentMaxFeePerTx);");
P("        (int fee) = txFee();");
P("        require(reserveConsumed <= fee);");
P("        requireExactSuccessorValue(newState.feeReserve);");
P("    }");
P("");

// ---- tokenAgentSpend -----------------------------------------------------
P("    #[covenant.singleton]");
P("    function tokenAgentSpend(");
P("        State prevState,");
P("        State newState,");
P("        KCC20State selfNew,");
P("        KCC20State recipientNew,");
P("        pubkey agentPk,");
P("        int tokenMaxPerSpend,");
P("        int tokenPeriodBudget,");
P("        int periodLengthDaa,");
P("        int periodStartDaa,");
P("        int tokenPeriodSpent,");
P("        int agentMaxFeePerTx,");
P("        int agentMaxCarryKas,");
P("        byte[32] agentRecipientRoot,");
P("        byte[] policySiblings,");
P("        int policyPathBits,");
P("        int periodsElapsed,");
P("        pubkey recipientPk,");
P("        byte[] recipientSiblings,");
P("        int recipientPathBits,");
P("        sig agentSig");
P("    ) {");
P("        require(prevState.paused == 0);");
P("        /* the LEAF is the sole key->policy authority */");
P("        require(checkSig(agentSig, agentPk));");
P("");
P("        /* BINDING A — exact pinned token family, exact shape (1 in, 2 out:");
P("         * self continuation + single recipient), no foreign covenants. */");
P("        require(OpCovInputCount(tokenCovenantId) == 1);");
P("        require(OpCovOutputCount(tokenCovenantId) == 2);");
P("        int tokIn = OpCovInputIdx(tokenCovenantId, 0);");
P("        requireNoForeignCovenantInputs(tokIn);");
P("");
P("        /* BINDING B — the token input's revealed redeem is proven (pinned");
P("         * hash + pinned geometry + P2SH) BEFORE its state is trusted. */");
P("        KCC20State prevTok = readInputStateWithTemplate(");
P("            tokIn,");
P("            templatePrefixLen,");
P("            templateSuffixLen,");
P("            templateVmHash");
P("        );");
P("");
P("        /* TRANSACTION-DERIVED VERIFIED TEMPLATE CARRIAGE — slice the proven");
P("         * prefix/suffix out of the token input's signature script. */");
P("        int sigLen = OpTxInputScriptSigLen(tokIn);");
P("        int redeemStart = sigLen - (templatePrefixLen + templateStateLen + templateSuffixLen);");
P("        byte[] templatePrefix = OpTxInputScriptSigSubstr(tokIn, redeemStart, redeemStart + templatePrefixLen);");
P("        byte[] templateSuffix = OpTxInputScriptSigSubstr(tokIn, sigLen - templateSuffixLen, sigLen);");
P("");
P("        /* Ownership: the position is ours via covenant-id/v1 and STAYS ours");
P("         * at family output 0; the recipient output is owned by the");
P("         * allowlisted recipient key (p2pk scheme); nobody becomes a minter. */");
P("        byte[32] selfId = OpInputCovenantId(this.activeInputIndex);");
P("        require(prevTok.ownerIdentifier == selfId);");
P("        require(prevTok.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!prevTok.isMinter);");
P("        require(selfNew.ownerIdentifier == selfId);");
P("        require(selfNew.identifierType == IDENTIFIER_COVENANT_ID);");
P("        require(!selfNew.isMinter);");
P("        require(bytes(selfNew.ownerIdentifier) != bytes(recipientPk));");
P("        require(bytes(recipientNew.ownerIdentifier) == bytes(recipientPk));");
P("        require(recipientNew.identifierType == IDENTIFIER_PUBKEY);");
P("        require(!recipientNew.isMinter);");
P("");
P("        /* TOKEN DOMAIN — exact conservation + token-denominated policy. */");
P("        int spendAmount = recipientNew.amount;");
P("        require(spendAmount > 0);");
P("        require(selfNew.amount >= 0);");
P("        require(selfNew.amount == prevTok.amount - spendAmount);");
P("        requireTokenAgentTransition(prevState, newState, spendAmount, agentPk, tokenMaxPerSpend, tokenPeriodBudget, periodLengthDaa, periodStartDaa, tokenPeriodSpent, agentMaxFeePerTx, agentMaxCarryKas, agentRecipientRoot, policySiblings, policyPathBits, periodsElapsed);");
P("        requireAgentRecipient(agentRecipientRoot, recipientPk, recipientSiblings, recipientPathBits);");
P("");
P("        /* BINDING B — both continuation outputs reconstructed from the");
P("         * proven template bytes (hash re-verified at use). */");
P("        validateOutputStateWithTemplate(");
P("            OpCovOutputIdx(tokenCovenantId, 0),");
P("            selfNew,");
P("            templatePrefix,");
P("            templateSuffix,");
P("            templateVmHash");
P("        );");
P("        validateOutputStateWithTemplate(");
P("            OpCovOutputIdx(tokenCovenantId, 1),");
P("            recipientNew,");
P("            templatePrefix,");
P("            templateSuffix,");
P("            templateVmHash");
P("        );");
P("");
P("        /* KAS DOMAIN + vault-global continuity. */");
P("        requireKasDomains(prevState, newState, tokIn, agentMaxFeePerTx, agentMaxCarryKas);");
P("        requireVaultGlobalPreserved(prevState, newState);");
P("    }");
P("");

// ---- ownerControl (4 selectors, one checkSig) -----------------------------
P("    /* Owner operations behind ONE entrypoint + bounded opSelector (v0.4.1");
P("     * standardness pattern; static sig-ops: 1 tokenAgentSpend + 1 ownerControl");
P("     * + 1 ownerRecover = 3 <= 15). Owner operations NEVER move tokens: no");
P("     * covenant input other than this one may be present. The successor");
P("     * state is pinned by the signed covenant output; mutually exclusive");
P("     * per-selector rules make a substituted selector reject. */");
P("    #[covenant.singleton]");
P("    function ownerControl(State prevState, State newState, int opSelector, sig ownerSig) {");
P("        require(checkSig(ownerSig, owner));");
P("        require(opSelector >= 0);");
P("        require(opSelector <= 3);");
P("        requireNoForeignCovenantInputs(this.activeInputIndex);");
P("        require(newState.boundVaultId == prevState.boundVaultId);");
P(`        require(bytes(descriptorHash) != bytes(${ZERO}));`);
P("        if (opSelector == 0) {");
P("            /* setAgentRoot: replace agentRoot; nonce +1; all else preserved */");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.paused == prevState.paused);");
P("            require(newState.policyNonce == prevState.policyNonce + 1);");
P("        } else {");
P("        if (opSelector == 1) {");
P("            /* topUpReserve: increase fee reserve only */");
P("            require(newState.feeReserve > prevState.feeReserve);");
P("            require(newState.paused == prevState.paused);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        } else {");
P("        if (opSelector == 2) {");
P("            /* pause: paused 0 -> 1 */");
P("            require(prevState.paused == 0);");
P("            require(newState.paused == 1);");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        } else {");
P("            /* opSelector == 3 (bounded to [0,3]): unpause 1 -> 0 */");
P("            require(prevState.paused == 1);");
P("            require(newState.paused == 0);");
P("            require(newState.feeReserve == prevState.feeReserve);");
P("            require(newState.agentRoot == prevState.agentRoot);");
P("            require(newState.policyNonce == prevState.policyNonce);");
P("        }");
P("        }");
P("        }");
P("        requireExactSuccessorValue(newState.feeReserve);");
P("    }");
P("");

// ---- ownerRecover (terminal; tokens return to the owner key) ---------------
P("    /* Break-glass recovery: the controller terminates, its fee reserve pays");
P("     * out to the owner (output 0), and — if the position exists in this");
P("     * transaction — the ENTIRE token amount moves to the owner's own key");
P("     * (p2pk scheme) through a template-verified continuation, so tokens can");
P("     * never be stranded under a dissolved covenant id. No other covenant");
P("     * family may be present. */");
P("    #[covenant.singleton(");
P("        mode = transition,");
P("        termination = allowed");
P("    )]");
P("    function ownerRecover(State prevState, State[] nextStates, sig ownerSig, KCC20State recipientNew) : (State[]) {");
P("        require(checkSig(ownerSig, owner));");
P("        require(nextStates.length == 0);");
P("        require(tx.outputs[0].scriptPubKey == new ScriptPubKeyP2PK(owner));");
P("        require(tx.outputs[0].value == prevState.feeReserve);");
P(`        require(bytes(descriptorHash) != bytes(${ZERO}));`);
P("        int familyInputs = OpCovInputCount(tokenCovenantId);");
P("        require(familyInputs <= 1);");
P("        if (familyInputs == 1) {");
P("            require(OpCovOutputCount(tokenCovenantId) == 1);");
P("            int tokIn = OpCovInputIdx(tokenCovenantId, 0);");
P("            requireNoForeignCovenantInputs(tokIn);");
P("            KCC20State prevTok = readInputStateWithTemplate(");
P("                tokIn,");
P("                templatePrefixLen,");
P("                templateSuffixLen,");
P("                templateVmHash");
P("            );");
P("            int sigLen = OpTxInputScriptSigLen(tokIn);");
P("            int redeemStart = sigLen - (templatePrefixLen + templateStateLen + templateSuffixLen);");
P("            byte[] templatePrefix = OpTxInputScriptSigSubstr(tokIn, redeemStart, redeemStart + templatePrefixLen);");
P("            byte[] templateSuffix = OpTxInputScriptSigSubstr(tokIn, sigLen - templateSuffixLen, sigLen);");
P("            byte[32] selfId = OpInputCovenantId(this.activeInputIndex);");
P("            require(prevTok.ownerIdentifier == selfId);");
P("            require(prevTok.identifierType == IDENTIFIER_COVENANT_ID);");
P("            require(bytes(recipientNew.ownerIdentifier) == bytes(owner));");
P("            require(recipientNew.identifierType == IDENTIFIER_PUBKEY);");
P("            require(!recipientNew.isMinter);");
P("            require(recipientNew.amount == prevTok.amount);");
P("            validateOutputStateWithTemplate(");
P("                OpCovOutputIdx(tokenCovenantId, 0),");
P("                recipientNew,");
P("                templatePrefix,");
P("                templateSuffix,");
P("                templateVmHash");
P("            );");
P("        } else {");
P("            requireNoForeignCovenantInputs(this.activeInputIndex);");
P("        }");
P("        return(nextStates);");
P("    }");
P("}");

if (!process.env.OUT) {
  console.error("set OUT to the destination path");
  process.exit(1);
}
require("fs").writeFileSync(process.env.OUT, out.join("\n") + "\n");
console.log("wrote", out.length, "lines");
